# -*- coding: utf-8 -*-
"""七年级 英语（仁爱版·科普版）期末试卷 5 套"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from paper_common import save, base, Q, A
out = []

# ================= A卷 =================
m = base("七年级英语", "第一学期期末质量检测", "（仁爱版·科普版　2025—2026学年　第一学期　满分120分）", fs=120, dur=100)
p = [
 {"name":"一、单项选择（每题1分，共15分）","questions":[
   Q(1,"— Nice to meet you.　— ________",1,
     opts=["A. Nice to meet you, too.　B. Good morning.　C. Thank you.　D. Fine, thanks."], kind="交际"),
   Q(2,"— What's ________ name?　— My name is Kangkang.",1,
     opts=["A. you　B. your　C. yours　D. yourself"], kind="物主代词"),
   Q(3,"This is ________ apple. It's very sweet.",1,
     opts=["A. a　B. an　C. the　D. /"], kind="冠词"),
   Q(4,"— Where ________ you from?　— I'm from China.",1,
     opts=["A. is　B. am　C. are　D. be"], kind="be动词"),
   Q(5,"Jane ________ long hair and big eyes.",1,
     opts=["A. have　B. has　C. is　D. are"], kind="主谓一致"),
   Q(6,"— ________ is your schoolbag?　— It's red.",1,
     opts=["A. What colour　B. How many　C. How old　D. What time"], kind="疑问词"),
   Q(7,"There ________ a pen and two books on the desk.",1,
     opts=["A. is　B. are　C. have　D. has"], kind="There be"),
   Q(8,"— What ________ your father do?　— He is a doctor.",1,
     opts=["A. do　B. does　C. is　D. are"], kind="一般现在时"),
   Q(9,"Look! The children ________ football on the playground.",1,
     opts=["A. play　B. plays　C. are playing　D. played"], kind="现在进行时"),
   Q(10,"— ________ do you go to school?　— By bike.",1,
     opts=["A. What　B. How　C. Where　D. When"], kind="疑问词"),
   Q(11,"My mother often ________ TV in the evening.",1,
     opts=["A. watch　B. watches　C. watching　D. is watching"], kind="主谓一致"),
   Q(12,"— Would you like ________ tea?　— Yes, please.",1,
     opts=["A. some　B. any　C. many　D. a"], kind="some/any"),
   Q(13,"The library is ________ the classroom building.",1,
     opts=["A. next　B. next to　C. next of　D. near to"], kind="介词短语"),
   Q(14,"— Whose book is this?　— It's ________.",1,
     opts=["A. she　B. her　C. hers　D. she's"], kind="名词性物主代词"),
   Q(15,"— Thank you very much.　— ________",1,
     opts=["A. You're welcome.　B. Thank you.　C. That's right.　D. All right."], kind="交际"),
 ]},
 {"name":"二、完形填空（每题1.5分，共15分）","questions":[
   Q(1,"阅读下面短文，从每小题所给的 A、B、C、D 四个选项中选出最佳答案，使短文完整通顺。（共 10 小题，15 分）",15,
     kind="完形填空", blanks=10),
 ]},
 {"name":"三、阅读理解（每题2分，共30分）","questions":[
   Q(1,"（A）阅读短文，判断正（T）误（F）。（每小题2分，共10分）",10, kind="阅读理解", blanks=5),
   Q(2,"（B）阅读短文，选择最佳答案。（每小题2分，共10分）",10, kind="阅读理解", blanks=5),
   Q(3,"（C）阅读短文，回答问题。（每小题2分，共10分）",10, kind="任务型阅读", blanks=5),
 ]},
 {"name":"四、词汇与句型（共30分）","questions":[
   Q(1,"（一）根据句意及首字母提示，补全单词。（每题1分，共5分）\n1. My family name is Li. I'm a Chinese s________.\n2. — What's the w________ like today? — It's sunny.\n3. My brother likes l________ to music.\n4. There are twelve m________ in a year.\n5. She goes to school on f________.",5, kind="词汇", blanks=5),
   Q(2,"（二）用所给词的适当形式填空。（每题1分，共5分）\n1. My sister ________ (have) a nice bag.\n2. Look! They ________ (play) games.\n3. There are five ________ (tomato) on the table.\n4. This is ________ (I) new pen.\n5. He often ________ (go) to school by bus.",5, kind="词形变化", blanks=5),
   Q(3,"（三）按要求完成句子。（每题2分，共10分）\n1. My name is Jane. (对划线部分提问) ________ ________ your name?\n2. He is a teacher. (改为一般疑问句) ________ he a teacher?\n3. This is my book. (改为复数句) ________ are my ________.\n4. I like English. (改为否定句) I ________ ________ English.\n5. She goes to school at seven. (对划线部分提问) ________ ________ she go to school?",10, kind="句型转换", blanks=10),
   Q(4,"（四）根据汉语意思完成句子。（每题2分，共10分）\n1. 你的电话号码是多少？\nWhat's your ________ ________?\n2. 这是我的父母。\n________ ________ my parents.\n3. 他每天早上六点起床。\nHe ________ ________ at six every morning.\n4. 我们班有四十五名学生。\nThere are ________ ________ students in our class.\n5. 你最喜欢的颜色是什么？\nWhat's your ________ ________?",10, kind="翻译", blanks=10),
 ]},
 {"name":"五、书面表达（共15分）","questions":[
   Q(1,"请以「Myself」为题，根据下列提示写一篇60—80词的英语短文介绍自己。\n提示：姓名、年龄、班级、外貌、爱好、最喜欢的科目。\n要求：1. 语句通顺，语法正确；2. 书写规范，卷面整洁。",15, kind="书面表达", blanks=0),
 ]},
]
a = [
 A(1,"A","「Nice to meet you.」的标准回答是「Nice to meet you, too.」"),
 A(2,"B","name 前用形容词性物主代词 your。"),
 A(3,"B","apple 以元音音素开头，用 an。"),
 A(4,"C","主语是 you，be 动词用 are。"),
 A(5,"B","主语 Jane 是第三人称单数，用 has。"),
 A(6,"A","问颜色用 What colour。"),
 A(7,"A","There be 句型遵循就近原则，a pen 是单数，用 is。"),
 A(8,"B","主语 your father 是第三人称单数，助动词用 does。"),
 A(9,"C","Look! 提示现在进行时，结构为 be + doing。"),
 A(10,"B","问交通方式用 How。"),
 A(11,"B","主语 My mother 是第三人称单数，用 watches。"),
 A(12,"A","在表示邀请或期望得到肯定回答的疑问句中，用 some 而不用 any。"),
 A(13,"B","next to 意为「紧挨着、在……旁边」。"),
 A(14,"C","hers 是名词性物主代词，相当于 her book。"),
 A(15,"A","「Thank you very much.」的回答是「You're welcome.」"),
 A(1,"【参考短文】\nHello! My name is Li Hua. I'm thirteen years old. I'm a student in Class One, Grade Seven. I'm tall and thin. I have short black hair and big eyes. I like playing basketball and reading books. My favourite subject is English, because it's very interesting. I have a happy family. We love each other very much. Nice to meet you!", "完形填空需根据上下文语境选择，注意时态、词性与搭配。"),
 A(1,"【A篇参考】\nMike is a middle school student in Beijing. He is thirteen years old. He gets up at six thirty every morning. He has breakfast at seven and then goes to school. He has four classes in the morning and two in the afternoon. His favourite subject is math. After school, he likes playing football with his friends. He usually does his homework at seven in the evening. He goes to bed at nine thirty.\n判断：1. Mike is thirteen years old. (T)\n2. Mike gets up at seven. (F)\n3. Mike has six classes a day. (T)\n4. Mike's favourite subject is English. (F)\n5. Mike goes to bed at nine thirty. (T)", "判断题要回到原文核对细节。"),
 A(2,"【B篇参考】\nTom has a happy family. His father is a doctor. He works in a big hospital. His mother is a teacher. She teaches English in a middle school. Tom has a sister. Her name is Mary. She is a student. They live in Shanghai. On Sundays, they often go to the park. They like flying kites there. Tom's favourite sport is swimming. Mary likes dancing.\n选择：\n1. What's Tom's father? (A. A doctor. B. A teacher. C. A driver.) → A\n2. Where do they live? (A. Beijing. B. Shanghai. C. Nanjing.) → B\n3. What's Tom's favourite sport? (A. Football. B. Swimming. C. Basketball.) → B\n4. What does Mary like? (A. Dancing. B. Singing. C. Drawing.) → A\n5. When do they often go to the park? (A. On Mondays. B. On Saturdays. C. On Sundays.) → C", "选择题要抓住关键词定位原文。"),
 A(3,"【C篇参考】\nHello, I'm Jane. I'm a student in a middle school. Our school is very big and beautiful. There is a library, a playground and two classroom buildings in our school. I like the library best. I often read books there. There are many kinds of books in the library. My favourite books are storybooks. I go to the library twice a week.\n回答：\n1. What does Jane like best? → The library.\n2. What kind of books does Jane like? → Storybooks.\n3. How often does Jane go to the library? → Twice a week.\n4. Where does Jane often read books? → In the library.\n5. Is Jane's school big and beautiful? → Yes, it is.", "回答问题时用完整句子或关键短语，注意时态。"),
 A(1,"1. student　2. weather　3. listening　4. months　5. foot","根据首字母与句意补全单词。"),
 A(2,"1. has　2. are playing　3. tomatoes　4. my　5. goes","注意第三人称单数、复数变化与现在进行时。"),
 A(3,"1. What is　2. Is　3. These; books　4. don't like　5. When does","句型转换注意时态与人称的一致性。"),
 A(4,"1. telephone number　2. These are　3. gets up　4. forty-five　5. favourite colour","翻译时注意固定搭配与拼写。"),
 A(1,"【范文】\nMyself\nHello, everyone! My name is Wang Fang. I'm twelve years old. I'm in Class Two, Grade Seven. I'm a little short, but I'm very strong. I have long hair and big eyes. I like sports very much. My favourite sport is basketball. I also like reading and singing. My favourite subject is English, because it's interesting and useful. I want to be a teacher in the future. I'm very happy to make friends with you!\n【评分标准】\n一类（13-15分）：内容完整，语言准确流畅，书写规范；\n二类（10-12分）：内容较完整，有少量语法错误；\n三类（7-9分）：内容基本完整，语法错误较多；\n四类（0-6分）：内容不完整，语言错误多。","书面表达要有要点齐全、语法正确、书写工整。"),
]
out.append(save(m, p, a, "期末质量检测A卷")); print("英语A卷完成")

# ================= B卷 =================
m = base("七年级英语", "上学期期末学业水平测试", "（仁爱版·科普版　2025—2026学年　第一学期　满分120分）", fs=120, dur=100)
p = [
 {"name":"一、单项选择（每题1分，共15分）","questions":[
   Q(1,"— How are you?　— ________",1,
     opts=["A. I'm fine, thank you.　B. How do you do?　C. Yes, I am.　D. That's OK."], kind="交际"),
   Q(2,"Kate is ________ English girl.",1,
     opts=["A. a　B. an　C. the　D. /"], kind="冠词"),
   Q(3,"— ________ is the boy in blue?　— He is my brother.",1,
     opts=["A. What　B. Who　C. Where　D. How"], kind="疑问词"),
   Q(4,"We ________ in the same class.",1,
     opts=["A. am　B. is　C. are　D. be"], kind="be动词"),
   Q(5,"— What's this in English?　— It's ________ eraser.",1,
     opts=["A. a　B. an　C. the　D. /"], kind="冠词"),
   Q(6,"My father ________ a new car.",1,
     opts=["A. have　B. has　C. is　D. are"], kind="主谓一致"),
   Q(7,"— ________ do you usually get up?　— At six.",1,
     opts=["A. What time　B. What colour　C. How many　D. How much"], kind="疑问词"),
   Q(8,"Listen! Someone ________ in the next room.",1,
     opts=["A. sing　B. sings　C. is singing　D. sang"], kind="现在进行时"),
   Q(9,"— Can you spell it, please?　— ________",1,
     opts=["A. Yes, I can.　B. Yes, I do.　C. No, I don't.　D. Yes, it is."], kind="情态动词"),
   Q(10,"There ________ some milk in the glass.",1,
     opts=["A. is　B. are　C. have　D. has"], kind="There be"),
   Q(11,"— ________ is your school?　— It's near the bank.",1,
     opts=["A. What　B. Where　C. Who　D. When"], kind="疑问词"),
   Q(12,"I'd like ________ orange juice, please.",1,
     opts=["A. a　B. an　C. some　D. many"], kind="some"),
   Q(13,"— Whose bike is that?　— It's ________.",1,
     opts=["A. Jim　B. Jim's　C. Jims　D. Jims'"], kind="名词所有格"),
   Q(14,"My sister ________ TV now.",1,
     opts=["A. watch　B. watches　C. is watching　D. watched"], kind="现在进行时"),
   Q(15,"— What does your mother do?　— ________",1,
     opts=["A. She is fine.　B. She is a nurse.　C. She likes red.　D. She is at home."], kind="职业"),
 ]},
 {"name":"二、完形填空（每题1.5分，共15分）","questions":[
   Q(1,"阅读下面短文，从每小题所给的 A、B、C、D 四个选项中选出最佳答案。（共 10 小题，15 分）",15, kind="完形填空", blanks=10),
 ]},
 {"name":"三、阅读理解（每题2分，共30分）","questions":[
   Q(1,"（A）判断正（T）误（F）。（每小题2分，共10分）",10, kind="阅读理解", blanks=5),
   Q(2,"（B）选择最佳答案。（每小题2分，共10分）",10, kind="阅读理解", blanks=5),
   Q(3,"（C）回答问题。（每小题2分，共10分）",10, kind="任务型阅读", blanks=5),
 ]},
 {"name":"四、词汇与句型（共30分）","questions":[
   Q(1,"（一）根据句意及首字母提示补全单词。（每题1分，共5分）\n1. My uncle is a d________. He works in a hospital.\n2. There are seven d________ in a week.\n3. — What's your f________ subject? — English.\n4. Look! The birds are f________ in the sky.\n5. I usually go to school by b________.",5, kind="词汇", blanks=5),
   Q(2,"（二）用所给词的适当形式填空。（每题1分，共5分）\n1. There are many ________ (child) on the playground.\n2. My brother ________ (like) playing football.\n3. Listen! She ________ (sing) an English song.\n4. This is ________ (we) classroom.\n5. He ________ (go) to Beijing next week.",5, kind="词形变化", blanks=5),
   Q(3,"（三）按要求完成句子。（每题2分，共10分）\n1. She is my sister. (改为一般疑问句) ________ ________ your sister?\n2. They are playing football. (对划线部分提问) ________ ________ they doing?\n3. I have some books. (改为否定句) I ________ ________ any books.\n4. This is a box. (改为复数句) ________ are ________.\n5. He goes to school on foot. (改为同义句) He ________ ________ school.",10, kind="句型转换", blanks=10),
   Q(4,"（四）根据汉语完成句子。（每题2分，共10分）\n1. 他来自加拿大。\nHe ________ ________ Canada.\n2. 你通常什么时候吃早饭？\nWhen do you usually ________ ________?\n3. 我们班有五十名学生。\nThere are ________ students ________ our class.\n4. 他正在做作业。\nHe ________ ________ his homework.\n5. 你的书包是什么颜色的？\nWhat colour ________ your ________?",10, kind="翻译", blanks=10),
 ]},
 {"name":"五、书面表达（共15分）","questions":[
   Q(1,"请以「My Family」为题，根据提示写一篇 60—80 词的英语短文。\n提示：家庭成员（父母、兄弟姐妹）、职业、外貌、爱好。\n要求：语句通顺，语法正确，书写规范。",15, kind="书面表达", blanks=0),
 ]},
]
a = [
 A(1,"A","「How are you?」的标准回答是「I'm fine, thank you.」"),
 A(2,"B","English 以元音音素开头，用 an。"),
 A(3,"B","问人是谁用 Who。"),
 A(4,"C","主语 We 是复数，be 动词用 are。"),
 A(5,"B","eraser 以元音音素开头，用 an。"),
 A(6,"B","主语 My father 是第三人称单数，用 has。"),
 A(7,"A","问具体时间点用 What time。"),
 A(8,"C","Listen! 提示现在进行时。"),
 A(9,"A","「Can you...?」的回答用 Yes, I can. / No, I can't."),
 A(10,"A","milk 是不可数名词，用 is。"),
 A(11,"B","问地点用 Where。"),
 A(12,"C","orange juice 是不可数名词，用 some。"),
 A(13,"B","表示所属用名词所有格 Jim's。"),
 A(14,"C","now 提示现在进行时。"),
 A(15,"B","问职业的回答是 She is a nurse."),
 A(1,"【参考短文】\nHello! I'm Li Ming. I'm a student. I get up at six every morning. Then I have breakfast at half past six. I go to school at seven. I have four classes in the morning. I like English best. At twelve, I have lunch at school. In the afternoon, I have two classes. After school, I play basketball with my friends. I go home at five. I do my homework in the evening. I go to bed at nine.", "完形填空注意上下文逻辑与时态一致。"),
 A(1,"【A篇参考】\nMary is an American girl. She is in Beijing now. She studies in a middle school. She has many friends in China. She likes Chinese food very much. She often has noodles and dumplings. Her favourite Chinese food is dumplings. She can speak a little Chinese. She wants to learn it well.\n判断：\n1. Mary is an American girl. (T)\n2. Mary is in Shanghai now. (F)\n3. Mary likes Chinese food very much. (T)\n4. Mary's favourite Chinese food is noodles. (F)\n5. Mary can speak Chinese very well. (F)", "判断题回到原文核对细节。"),
 A(2,"【B篇参考】\nIt's Sunday today. The weather is fine. Lucy and her family are at the park. Her father is boating on the lake. Her mother is talking with a friend. Her brother is playing football with his friends. Lucy is drawing a picture under a big tree. She is drawing the beautiful lake. They are all having a good time.\n选择：\n1. What day is it today? (A. Saturday. B. Sunday.) → B\n2. Where are Lucy's family? (A. At home. B. At the park.) → B\n3. What is Lucy's father doing? (A. Boating. B. Reading.) → A\n4. What is Lucy doing? (A. Playing football. B. Drawing.) → B\n5. How do they feel? (A. Happy. B. Tired.) → A", "抓住现在进行时的描述，对应人物与动作。"),
 A(3,"【C篇参考】\nMy name is Peter. I'm from England. I'm now in China. I'm a student in Grade Seven. I have a good friend. His name is Zhang Hua. He is a Chinese boy. He often helps me with my Chinese. I help him with his English. We often play basketball together after school. We are good friends.\n回答：\n1. Where is Peter from? → England.\n2. What grade is Peter in? → Grade Seven.\n3. Who is Peter's good friend? → Zhang Hua.\n4. What does Zhang Hua help Peter with? → Chinese.\n5. What do they often do after school? → They often play basketball together.", "回到原文找答案，注意人称转换。"),
 A(1,"1. doctor　2. days　3. favourite　4. flying　5. bike","根据首字母与句意判断。"),
 A(2,"1. children　2. likes　3. is singing　4. our　5. is going / will go","注意复数、第三人称单数、现在进行时与一般将来时。"),
 A(3,"1. Is she　2. What are　3. don't have　4. These; boxes　5. walks to","句型转换注意时态与人称一致。"),
 A(4,"1. is from / comes from　2. have breakfast　3. fifty; in　4. is doing　5. is; schoolbag","注意固定搭配与拼写。"),
 A(1,"【范文】\nMy Family\nHello! I'm Wang Ming. Let me tell you about my family. There are four people in my family: my father, my mother, my sister and I. My father is a doctor. He is tall and strong. He likes reading. My mother is a teacher. She is beautiful and kind. She likes cooking. My sister is a student. She is twelve. We study in the same school. We all love each other. I have a happy family.","书面表达要点齐全、语句通顺。"),
]
out.append(save(m, p, a, "学业水平测试B卷")); print("英语B卷完成")

# ================= C卷 =================
m = base("七年级英语", "下学期期末综合检测", "（仁爱版·科普版　2025—2026学年　第二学期　满分120分）", fs=120, dur=100)
p = [
 {"name":"一、单项选择（每题1分，共15分）","questions":[
   Q(1,"— What's the weather like today?　— ________",1,
     opts=["A. It's sunny.　B. It's Monday.　C. It's June 1st.　D. It's ten."], kind="天气"),
   Q(2,"— ________ is it from here to the bank?　— About five minutes' walk.",1,
     opts=["A. How long　B. How far　C. How often　D. How many"], kind="疑问词"),
   Q(3,"There ________ a basketball match next week.",1,
     opts=["A. is going to have　B. is going to be　C. are going to be　D. will have"], kind="将来时"),
   Q(4,"— Did you go to the zoo yesterday?　— No, I ________.",1,
     opts=["A. don't　B. didn't　C. wasn't　D. haven't"], kind="一般过去时"),
   Q(5,"The teacher told us ________ hard.",1,
     opts=["A. study　B. to study　C. studying　D. studied"], kind="非谓语"),
   Q(6,"— Would you like to go swimming with me?　— ________",1,
     opts=["A. Yes, I'd love to.　B. Yes, I do.　C. No, I can't.　D. You're welcome."], kind="交际"),
   Q(7,"My hometown is ________ the south of China.",1,
     opts=["A. on　B. in　C. at　D. to"], kind="介词"),
   Q(8,"— How ________ is the book?　— It's twenty yuan.",1,
     opts=["A. much　B. many　C. long　D. far"], kind="疑问词"),
   Q(9,"It's important ________ English well.",1,
     opts=["A. learn　B. to learn　C. learning　D. learns"], kind="非谓语"),
   Q(10,"The boy ________ short hair is my cousin.",1,
     opts=["A. in　B. with　C. of　D. on"], kind="介词"),
   Q(11,"— What happened to you?　— I ________ my leg.",1,
     opts=["A. hurt　B. hurts　C. hurting　D. to hurt"], kind="一般过去时"),
   Q(12,"She is good ________ singing.",1,
     opts=["A. at　B. in　C. for　D. with"], kind="介词短语"),
   Q(13,"— ________ I use your pen?　— Sure, here you are.",1,
     opts=["A. Must　B. May　C. Should　D. Need"], kind="情态动词"),
   Q(14,"There is ________ water in the bottle. Let's drink it.",1,
     opts=["A. a few　B. a little　C. many　D. few"], kind="量词"),
   Q(15,"— Thank you for helping me.　— ________",1,
     opts=["A. Not at all.　B. Don't say so.　C. That's right.　D. Yes, please."], kind="交际"),
 ]},
 {"name":"二、完形填空（每题1.5分，共15分）","questions":[
   Q(1,"阅读短文，选择最佳答案。（共 10 小题，15 分）",15, kind="完形填空", blanks=10),
 ]},
 {"name":"三、阅读理解（每题2分，共30分）","questions":[
   Q(1,"（A）判断正（T）误（F）。（每小题2分，共10分）",10, kind="阅读理解", blanks=5),
   Q(2,"（B）选择最佳答案。（每小题2分，共10分）",10, kind="阅读理解", blanks=5),
   Q(3,"（C）回答问题。（每小题2分，共10分）",10, kind="任务型阅读", blanks=5),
 ]},
 {"name":"四、词汇与句型（共30分）","questions":[
   Q(1,"（一）根据句意及首字母提示补全单词。（每题1分，共5分）\n1. I'm going to visit the G________ Wall this summer.\n2. Be careful! The road is d________.\n3. My father often goes to w________ by car.\n4. Would you like to go s________ with me this Sunday?\n5. She is good at d________ pictures.",5, kind="词汇", blanks=5),
   Q(2,"（二）用所给词的适当形式填空。（每题1分，共5分）\n1. We ________ (visit) the museum last Sunday.\n2. Look! The children ________ (swim) in the river.\n3. She is interested in ________ (play) the piano.\n4. There ________ (be) a lot of rain last year.\n5. He is ________ (good) at math than me.",5, kind="词形变化", blanks=5),
   Q(3,"（三）按要求完成句子。（每题2分，共10分）\n1. I went to the park yesterday. (改为一般疑问句) ________ you ________ to the park yesterday?\n2. She is reading a book. (对划线部分提问) ________ is she ________?\n3. He will come back tomorrow. (改为否定句) He ________ ________ come back tomorrow.\n4. This is an interesting book. (改为感叹句) ________ ________ interesting book it is!\n5. The boy is very tall. (改为同义句) The boy is ________ ________.",10, kind="句型转换", blanks=10),
   Q(4,"（四）根据汉语完成句子。（每题2分，共10分）\n1. 昨天我去了动物园。\nI ________ to the zoo yesterday.\n2. 我打算下周去看电影。\nI ________ ________ to see a film next week.\n3. 昨天天气怎么样？\nWhat ________ the weather ________ yesterday?\n4. 他昨天没有做作业。\nHe ________ ________ his homework yesterday.\n5. 你愿意和我一起去吗？\nWould you like to go ________ ________?",10, kind="翻译", blanks=10),
 ]},
 {"name":"五、书面表达（共15分）","questions":[
   Q(1,"假如你是李华，请根据下面的提示，以「My Favourite Season」为题，写一篇 70—90 词的英语短文。\n提示：最喜欢的季节、原因、这个季节可以做的事、你的感受。\n要求：语句通顺，语法正确，书写规范。",15, kind="书面表达", blanks=0),
 ]},
]
a = [
 A(1,"A","问天气的回答是 It's sunny. 等。"),
 A(2,"B","问距离用 How far。"),
 A(3,"B","There be 句型的将来时：There is going to be..."),
 A(4,"B","Did you...? 的回答用 did 的相应形式，否定用 didn't。"),
 A(5,"B","tell sb to do sth：告诉某人做某事。"),
 A(6,"A","「Would you like to...?」的接受回答是 Yes, I'd love to."),
 A(7,"B","「在中国南部」用 in the south of China（internal）。"),
 A(8,"A","问价格用 How much。"),
 A(9,"B","「It is + adj. + to do sth.」是固定句型。"),
 A(10,"B","with short hair 表示「留着短发」，作定语。"),
 A(11,"A","happen 是过去发生的事，用一般过去时 hurt。"),
 A(12,"A","be good at 意为「擅长」。"),
 A(13,"B","请求许可用 May I...?"),
 A(14,"B","a little 修饰不可数名词，表示「有一点」。"),
 A(15,"A","「Thank you for...」的回答是「Not at all.」或「You're welcome.」"),
 A(1,"【参考短文】\nIt was Sunday yesterday. The weather was fine. Li Ming and his friends went to the park. They played games and had a picnic there. Li Ming took many photos. They saw some birds singing in the trees. Everyone had a good time. In the afternoon, they went home at five. Li Ming was tired but very happy.", "完形填空注意前后文逻辑与动词时态。"),
 A(1,"【A篇参考】\nBeijing is the capital of China. It is a very old city. There are many places of interest in Beijing, such as the Great Wall, the Palace Museum and Tian'anmen Square. Every year, millions of people come to visit Beijing. The weather in Beijing is different in four seasons. It is hot in summer and cold in winter. Autumn is the best season to visit Beijing.\n判断：\n1. Beijing is the capital of China. (T)\n2. There are few places of interest in Beijing. (F)\n3. The weather in Beijing is hot in winter. (F)\n4. Autumn is the best season to visit Beijing. (T)\n5. Millions of people come to Beijing every year. (T)", "判断题要核对原文的肯定与否定表述。"),
 A(2,"【B篇参考】\nHello! I'm Wang Lin. I live in a small village in the countryside. There is a river in front of my house. The water is clean and there are many fish in it. Behind my house, there is a big mountain. We can see many trees and flowers on the mountain. In spring, the mountain is green and beautiful. I like my village very much. It is quieter and more beautiful than the city.\n选择：\n1. Where does Wang Lin live? (A. In a city. B. In a village.) → B\n2. What's in front of his house? (A. A river. B. A mountain.) → A\n3. What's behind his house? (A. A river. B. A mountain.) → B\n4. What's the village like in spring? (A. Green and beautiful. B. White and cold.) → A\n5. Which does Wang Lin like better? (A. The city. B. His village.) → B", "抓住方位词与比较关系。"),
 A(3,"【C篇参考】\nDear Li Hua,\nHow are you? I'm writing to tell you about my summer holiday plan. I'm going to visit Beijing with my parents. We will go there by train. We are going to visit the Great Wall and the Palace Museum. I'm also going to try some Chinese food. I hope to see you in Beijing. Please write back soon.\nYours,\nTom\n回答：\n1. Who is Tom going to Beijing with? → His parents.\n2. How will they go there? → By train.\n3. What places are they going to visit? → The Great Wall and the Palace Museum.\n4. What is Tom also going to try? → Some Chinese food.\n5. Who is Tom writing to? → Li Hua.", "书信类阅读要注意写信人与收信人。"),
 A(1,"1. Great　2. dangerous　3. work　4. swimming　5. drawing","根据首字母与语境判断。"),
 A(2,"1. visited　2. are swimming　3. playing　4. was　5. better","注意一般过去时、现在进行时、固定搭配与比较级。"),
 A(3,"1. Did; go　2. What; doing　3. will not / won't　4. What an　5. not short","句型转换注意时态与固定句式。"),
 A(4,"1. went　2. am going to　3. was; like　4. didn't do　5. with me","翻译注意时态与固定搭配。"),
 A(1,"【范文】\nMy Favourite Season\nMy favourite season is spring. Spring comes in March, April and May. In spring, the weather is warm and the days are longer. The trees turn green and the flowers come out. Everything comes back to life. I like flying kites with my friends in the park. I can also go hiking and enjoy the beautiful scenery. Spring is full of hope. I love spring best because it makes me happy and energetic.","突出季节特点与个人感受，语言丰富。"),
]
out.append(save(m, p, a, "综合检测C卷")); print("英语C卷完成")

# ================= D卷 =================
m = base("七年级英语", "期末复习质量检测", "（仁爱版·科普版　2025—2026学年　全册　满分120分）", fs=120, dur=100)
p = [
 {"name":"一、单项选择（每题1分，共15分）","questions":[
   Q(1,"— Hello! ________?　— Yes, I'm Li Ming.",1,
     opts=["A. Are you Li Ming　B. What's your name　C. How old are you　D. Where are you from"], kind="交际"),
   Q(2,"This is ________ old photo of my family.",1,
     opts=["A. a　B. an　C. the　D. /"], kind="冠词"),
   Q(3,"My brother ________ to school at seven o'clock every day.",1,
     opts=["A. go　B. goes　C. going　D. went"], kind="主谓一致"),
   Q(4,"Look at the boy. He ________ a red coat.",1,
     opts=["A. wear　B. wears　C. is wearing　D. wore"], kind="时态"),
   Q(5,"— ________ is your new teacher?　— She is from Canada.",1,
     opts=["A. Where　B. What　C. Who　D. How"], kind="疑问词"),
   Q(6,"There ________ some water and two apples on the table.",1,
     opts=["A. is　B. are　C. have　D. has"], kind="There be"),
   Q(7,"We often play ________ basketball after school.",1,
     opts=["A. a　B. an　C. the　D. /"], kind="冠词"),
   Q(8,"My mother is a nurse. She works in a ________.",1,
     opts=["A. school　B. hospital　C. bank　D. factory"], kind="职业场所"),
   Q(9,"— ________ do you usually have lunch?　— At school.",1,
     opts=["A. What　B. Where　C. When　D. Who"], kind="疑问词"),
   Q(10,"Jane and I ________ good friends.",1,
     opts=["A. am　B. is　C. are　D. be"], kind="be动词"),
   Q(11,"The students are ________ an English class now.",1,
     opts=["A. have　B. has　C. having　D. had"], kind="现在进行时"),
   Q(12,"— ________ is the weather in Beijing?　— It's cold.",1,
     opts=["A. What　B. How　C. Where　D. Who"], kind="天气"),
   Q(13,"I go to school ________ my bike every day.",1,
     opts=["A. by　B. on　C. in　D. with"], kind="介词"),
   Q(14,"— ________ you like some coffee?　— No, thanks.",1,
     opts=["A. Do　B. Would　C. Are　D. Will"], kind="情态动词"),
   Q(15,"— I'm sorry I'm late.　— ________",1,
     opts=["A. That's all right.　B. Yes, you are late.　C. Thank you.　D. You are welcome."], kind="交际"),
 ]},
 {"name":"二、完形填空（每题1.5分，共15分）","questions":[
   Q(1,"阅读短文，选择最佳答案。（共 10 小题，15 分）",15, kind="完形填空", blanks=10),
 ]},
 {"name":"三、阅读理解（每题2分，共30分）","questions":[
   Q(1,"（A）判断正（T）误（F）。（每小题2分，共10分）",10, kind="阅读理解", blanks=5),
   Q(2,"（B）选择最佳答案。（每小题2分，共10分）",10, kind="阅读理解", blanks=5),
   Q(3,"（C）回答问题。（每小题2分，共10分）",10, kind="任务型阅读", blanks=5),
 ]},
 {"name":"四、词汇与句型（共30分）","questions":[
   Q(1,"（一）根据句意及首字母提示补全单词。（每题1分，共5分）\n1. There are eleven p________ in our football team.\n2. My father is a farm worker. He works on a f________.\n3. — What's the d________ today? — It's June 1st.\n4. I'm hungry. Let's have some n________.\n5. She likes music and can play the p________.",5, kind="词汇", blanks=5),
   Q(2,"（二）用所给词的适当形式填空。（每题1分，共5分）\n1. My father ________ (work) in a hospital.\n2. There are two ________ (library) in our school.\n3. Look! The girl ________ (have) a nice dress.\n4. I want ________ (be) a teacher.\n5. She ________ (not like) eggs.",5, kind="词形变化", blanks=5),
   Q(3,"（三）按要求完成句子。（每题2分，共10分）\n1. My name is Li Lei. (对划线部分提问) ________ your name?\n2. He is from England. (改为一般疑问句) ________ he from England?\n3. They have some apples. (改为否定句) They ________ ________ any apples.\n4. She goes to school by bus. (对划线部分提问) ________ ________ she go to school?\n5. This is my pen. (改为一般疑问句) ________ this ________ pen?",10, kind="句型转换", blanks=10),
   Q(4,"（四）根据汉语完成句子。（每题2分，共10分）\n1. 我家有四口人。\nThere are ________ people in my family.\n2. 他每天六点半起床。\nHe ________ ________ at half past six every day.\n3. 你最喜欢的科目是什么？\nWhat's your ________ ________?\n4. 他们正在踢足球。\nThey ________ ________ football.\n5. 请把它拼写出来。\nPlease ________ it, ________.",10, kind="翻译", blanks=10),
 ]},
 {"name":"五、书面表达（共15分）","questions":[
   Q(1,"请以「My School Day」为题，写一篇 70—90 词的英语短文，介绍你一天的学校生活。\n提示：起床、上学、课程、午餐、放学、作业。\n要求：语句通顺，语法正确，书写规范。",15, kind="书面表达", blanks=0),
 ]},
]
a = [
 A(1,"A","从回答「Yes, I'm Li Ming.」判断，问句应为「Are you Li Ming?」"),
 A(2,"B","old 以元音音素开头，用 an。"),
 A(3,"B","主语 My brother 是第三人称单数，且 every day 提示一般现在时，用 goes。"),
 A(4,"C","Look at... 提示现在正在发生，用现在进行时 is wearing。"),
 A(5,"A","问来自哪里用 Where。"),
 A(6,"A","There be 就近原则，some water 是不可数名词，用 is。"),
 A(7,"D","play 后接球类运动时不加冠词。"),
 A(8,"B","nurse（护士）在医院工作。"),
 A(9,"B","问地点用 Where。"),
 A(10,"C","主语 Jane and I 是复数，用 are。"),
 A(11,"C","now 提示现在进行时，have an English class → are having。"),
 A(12,"B","问天气可用 What's the weather like? 或 How is the weather?"),
 A(13,"B","「骑自行车」可用 by bike 或 on one's bike。此处有 my bike，用 on。"),
 A(14,"B","邀请用 Would you like...?"),
 A(15,"A","对道歉的回答是 That's all right. / Never mind."),
 A(1,"【参考短文】\nHi, I'm Kate. I'm a student in Beijing. I usually get up at six in the morning. I have breakfast at six thirty. Then I go to school at seven. Classes begin at eight. I have four classes in the morning. My favourite subject is English. I have lunch at school at twelve. In the afternoon, I have two classes. School is over at four thirty. After school, I often play basketball with my friends. I go home at five and do my homework in the evening.", "完形填空注意上下文的时态与语义连贯。"),
 A(1,"【A篇参考】\nSam is a middle school student. He is from Australia. Now he lives in Hubei with his parents. He likes Chinese food. He often has rice and vegetables for lunch. He can speak a little Chinese. He goes to school by bike. He has many Chinese friends. He often plays basketball with them after school. He likes China very much.\n判断：\n1. Sam is from Australia. (T)\n2. Sam lives in Hubei now. (T)\n3. Sam doesn't like Chinese food. (F)\n4. Sam goes to school on foot. (F)\n5. Sam has many Chinese friends. (T)", "判断题要在原文中找到对应依据。"),
 A(2,"【B篇参考】\nThere is a big shop near my home. It's called Sunshine Shop. It opens at eight in the morning and closes at nine in the evening. You can buy many things there, such as food, drinks, school things and clothes. The things in the shop are good and cheap. The shopkeepers are very friendly. Many people like shopping there. I often buy some books and pens there.\n选择：\n1. What's the name of the shop? (A. Sunshine Shop. B. Sun Shop.) → A\n2. When does the shop open? (A. At 8 a.m. B. At 9 a.m.) → A\n3. What can you buy there? (A. Food and clothes. B. Only books.) → A\n4. What are the things in the shop like? (A. Good and cheap. B. Bad and expensive.) → A\n5. How are the shopkeepers? (A. Friendly. B. Strict.) → A", "抓住商店的基本信息（名称、时间、商品、服务）。"),
 A(3,"【C篇参考】\nDear Jim,\nHow are you? I'm in Hubei now. I'm studying in a middle school here. I like my school very much. It is big and beautiful. My teachers are kind and my classmates are friendly. I have eight classes a day. My favourite subject is Chinese. I'm learning Chinese now. It's a little difficult, but I like it. I hope you can come to China one day.\nYours,\nPeter\n回答：\n1. Where is Peter now? → In Hubei.\n2. What does Peter think of his school? → Big and beautiful.\n3. How many classes does Peter have a day? → Eight.\n4. What's Peter's favourite subject? → Chinese.\n5. What does Peter hope? → He hopes Jim can come to China one day.", "书信阅读要理清内容要点。"),
 A(1,"1. players　2. farm　3. date　4. noodles　5. piano","根据首字母与语境判断。"),
 A(2,"1. works　2. libraries　3. has　4. to be　5. doesn't like","注意第三人称单数、复数、want to do 与否定句。"),
 A(3,"1. What's　2. Is　3. don't have　4. How does　5. Is; your","句型转换注意助动词、人称与物主代词。"),
 A(4,"1. four　2. gets up　3. favourite subject　4. are playing　5. spell; please","翻译注意固定搭配与语序。"),
 A(1,"【范文】\nMy School Day\nI'm a student in Grade Seven. Every day, I get up at six thirty. I have breakfast at seven and then go to school at seven thirty. Classes begin at eight o'clock. I have four classes in the morning. I have lunch at school at twelve. In the afternoon, I have three classes. School is over at five. After school, I do my homework at home. In the evening, I sometimes watch TV or read books. I go to bed at ten. I have a happy school day.","按时间顺序叙述，条理清晰。"),
]
out.append(save(m, p, a, "复习质量检测D卷")); print("英语D卷完成")

# ================= E卷 =================
m = base("七年级英语", "期末学业质量监测", "（仁爱版·科普版　2025—2026学年　全册　满分120分）", fs=120, dur=100)
p = [
 {"name":"一、单项选择（每题1分，共15分）","questions":[
   Q(1,"— Excuse me, ________?　— Yes, it's next to the bank.",1,
     opts=["A. is there a post office near here　B. where is the bank",
           "C. how can I get there　D. what's your name"], kind="交际"),
   Q(2,"There is ________ orange on the table. ________ orange is very sweet.",1,
     opts=["A. an; An　B. an; The　C. the; An　D. a; The"], kind="冠词"),
   Q(3,"— What ________ your mother do?　— She is a teacher.",1,
     opts=["A. do　B. does　C. is　D. are"], kind="主谓一致"),
   Q(4,"It's 8 o'clock. The students ________ morning reading now.",1,
     opts=["A. do　B. does　C. are doing　D. did"], kind="现在进行时"),
   Q(5,"— ________ do you like English?　— Because it's interesting.",1,
     opts=["A. What　B. Why　C. How　D. Where"], kind="疑问词"),
   Q(6,"My sister and I ________ TV together last night.",1,
     opts=["A. watch　B. watches　C. watched　D. is watching"], kind="一般过去时"),
   Q(7,"The bank is ________ the supermarket and the hospital.",1,
     opts=["A. next　B. between　C. among　D. in"], kind="介词"),
   Q(8,"— Would you like something to drink?　— ________",1,
     opts=["A. Yes, some water, please.　B. Yes, I would.　C. No, I don't.　D. You're welcome."], kind="交际"),
   Q(9,"The children are ________ a good time in the park.",1,
     opts=["A. have　B. has　C. having　D. had"], kind="现在进行时"),
   Q(10,"— ________ is the T-shirt?　— It's 80 yuan.",1,
     opts=["A. How much　B. How many　C. How long　D. How old"], kind="疑问词"),
   Q(11,"You'd better ________ some water. You look thirsty.",1,
     opts=["A. drink　B. to drink　C. drinking　D. drank"], kind="情态动词"),
   Q(12,"It's important for us ________ healthy food.",1,
     opts=["A. eat　B. to eat　C. eating　D. ate"], kind="非谓语"),
   Q(13,"— ________ your father like sports?　— Yes, he likes football.",1,
     opts=["A. Do　B. Does　C. Is　D. Are"], kind="一般现在时"),
   Q(14,"There are ________ books in our library.",1,
     opts=["A. two thousands　B. thousands of　C. thousand of　D. two thousand of"], kind="数词"),
   Q(15,"— Have a good weekend!　— ________",1,
     opts=["A. The same to you.　B. You're welcome.　C. That's all right.　D. Yes, I do."], kind="交际"),
 ]},
 {"name":"二、完形填空（每题1.5分，共15分）","questions":[
   Q(1,"阅读短文，选择最佳答案。（共 10 小题，15 分）",15, kind="完形填空", blanks=10),
 ]},
 {"name":"三、阅读理解（每题2分，共30分）","questions":[
   Q(1,"（A）判断正（T）误（F）。（每小题2分，共10分）",10, kind="阅读理解", blanks=5),
   Q(2,"（B）选择最佳答案。（每小题2分，共10分）",10, kind="阅读理解", blanks=5),
   Q(3,"（C）回答问题。（每小题2分，共10分）",10, kind="任务型阅读", blanks=5),
 ]},
 {"name":"四、词汇与句型（共30分）","questions":[
   Q(1,"（一）根据句意及首字母提示补全单词。（每题1分，共5分）\n1. China is a large country with a long h________.\n2. My birthday is in O________. It's the tenth month of the year.\n3. It's very hot today. Let's go s________.\n4. There are sixty m________ in an hour.\n5. The girl is very c________. She often gets good grades.",5, kind="词汇", blanks=5),
   Q(2,"（二）用所给词的适当形式填空。（每题1分，共5分）\n1. He often ________ (help) his mother at home.\n2. There ________ (be) a lot of books on the shelf.\n3. Look! The children ________ (play) games.\n4. This is my ________ (sister) room.\n5. We ________ (have) a good time yesterday.",5, kind="词形变化", blanks=5),
   Q(3,"（三）按要求完成句子。（每题2分，共10分）\n1. She has a new bike. (改为一般疑问句) ________ she ________ a new bike?\n2. They are playing football. (改为否定句) They ________ ________ football.\n3. My birthday is on May 1st. (对划线部分提问) ________ ________ your birthday?\n4. He goes to work by subway. (改为同义句) He ________ the subway ________ work.\n5. It's a beautiful city. (改为感叹句) ________ ________ beautiful city it is!",10, kind="句型转换", blanks=10),
   Q(4,"（四）根据汉语完成句子。（每题2分，共10分）\n1. 他正在看书。\nHe ________ ________ a book.\n2. 昨天你去了哪里？\nWhere ________ you ________ yesterday?\n3. 我喜欢听音乐。\nI like ________ ________ music.\n4. 你多久去一次图书馆？\n________ ________ do you go to the library?\n5. 谢谢你帮助我。\nThank you for ________ ________.",10, kind="翻译", blanks=10),
 ]},
 {"name":"五、书面表达（共15分）","questions":[
   Q(1,"请以「My Favourite Festival」为题，写一篇 70—90 词的英语短文。\n提示：最喜欢的节日、时间、人们的活动、你的感受。\n要求：语句通顺，语法正确，书写规范。",15, kind="书面表达", blanks=0),
 ]},
]
a = [
 A(1,"A","从「Yes, it's next to the bank.」判断，问句应为询问某地是否存在。"),
 A(2,"B","第一次提到 orange 用 an，第二次特指同一个用 The。"),
 A(3,"B","主语 your mother 是第三人称单数，助动词用 does。"),
 A(4,"C","now 提示现在进行时。"),
 A(5,"B","回答「Because...」，问句用 Why。"),
 A(6,"C","last night 提示一般过去时，用 watched。"),
 A(7,"B","between...and... 意为「在……和……之间」。"),
 A(8,"A","对「Would you like...?」的接受回答可以是 Yes, some water, please."),
 A(9,"C","have a good time 的进行时：are having a good time。"),
 A(10,"A","问价格用 How much。"),
 A(11,"A","had better do sth：最好做某事。"),
 A(12,"B","It is + adj. + for sb + to do sth 句型。"),
 A(13,"B","主语 your father 是第三人称单数，用 Does。"),
 A(14,"B","thousands of 意为「成千上万的」。"),
 A(15,"A","对「Have a good weekend!」的回应是「The same to you.」"),
 A(1,"【参考短文】\nMy name is Lin Tao. I'm a student in Grade Seven. I like sports very much. Every morning, I get up early and run for half an hour. I think running is good for my health. I also like playing basketball. I often play it with my friends after school. On weekends, I sometimes go swimming with my father. Sports make me strong and happy. I hope everyone can do more sports.", "完形填空注意语义连贯与固定搭配。"),
 A(1,"【A篇参考】\nHelen is a middle school student. She has a healthy lifestyle. She gets up at six every day and does morning exercises. She eats lots of fruit and vegetables. She doesn't eat junk food. She thinks it's bad for her health. She often plays sports with her friends. She goes to bed before ten. She is always full of energy.\n判断：\n1. Helen has a healthy lifestyle. (T)\n2. Helen gets up at eight every day. (F)\n3. Helen likes eating junk food. (F)\n4. Helen often plays sports with her friends. (T)\n5. Helen goes to bed before ten. (T)", "判断题要回到原文找依据。"),
 A(2,"【B篇参考】\nDo you know the Spring Festival? It is the most important festival in China. It usually comes in January or February. Before the festival, people clean their houses and buy new clothes. On the eve of the festival, families get together and have a big dinner. Dumplings are a traditional food. Children can get red packets from their parents. People also set off fireworks. Everyone is very happy.\n选择：\n1. When does the Spring Festival usually come? (A. In January or February. B. In June.) → A\n2. What do people do before the festival? (A. Clean houses and buy new clothes. B. Go to school.) → A\n3. What's the traditional food? (A. Dumplings. B. Noodles.) → A\n4. What can children get? (A. Red packets. B. New books.) → A\n5. How do people feel? (A. Happy. B. Sad.) → A", "抓住节日的时间、习俗与情感。"),
 A(3,"【C篇参考】\nDear Li Mei,\nThank you for your email. You asked me about my favourite festival. My favourite festival is the Mid-Autumn Festival. It comes in September or October. On that day, families get together. We eat mooncakes and watch the moon at night. The moon is round and bright. It means family reunion. I like it because I can be with my family. What's your favourite festival? Please write to me soon.\nYours,\nAnna\n回答：\n1. What's Anna's favourite festival? → The Mid-Autumn Festival.\n2. When does it come? → In September or October.\n3. What do people eat on that day? → Mooncakes.\n4. What does the round moon mean? → Family reunion.\n5. Why does Anna like this festival? → Because she can be with her family.", "书信阅读要理清要点。"),
 A(1,"1. history　2. October　3. swimming　4. minutes　5. clever","根据首字母与语境判断。"),
 A(2,"1. helps　2. are　3. are playing　4. sister's　5. had","注意第三人称单数、There be、现在进行时、所有格与一般过去时。"),
 A(3,"1. Does; have　2. aren't playing　3. When is　4. takes; to　5. What a","句型转换注意助动词、否定形式与感叹句结构。"),
 A(4,"1. is reading　2. did; go　3. listening to　4. How often　5. helping me","翻译注意固定搭配与语序。"),
 A(1,"【范文】\nMy Favourite Festival\nMy favourite festival is the Spring Festival. It is the most important festival in China. It usually comes in January or February. Before the festival, my family clean our house and buy new clothes. On the eve of the festival, we have a big dinner together. We eat dumplings and watch the Spring Festival Gala on TV. Children can get red packets. I like it because I can be with my family and have a lot of fun.","突出节日气氛与个人感受。"),
]
out.append(save(m, p, a, "学业质量监测E卷")); print("英语E卷完成")

for f in out:
    print("已生成:", f)
