# -*- coding: utf-8 -*-
"""六年级 英语（人教版PEP）期末试卷（5套）"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from paper_common import save, base, Q, A
out = []

# ================= A卷 =================
m = base("六年级英语", "第一学期期末质量检测", "（人教版PEP　三年级起点　2025—2026学年　第一学期）")
p = [
 {"name":"一、判断下列单词划线部分读音是否相同（相同写S，不同写D）（10分）","questions":[
   Q(1,"（　）chair　care",2), Q(2,"（　）hear　deer",2), Q(3,"（　）light　pie",2),
   Q(4,"（　）think　three",2), Q(5,"（　）who　whose",2),
 ]},
 {"name":"二、看图选词，把序号填在括号里（10分）","questions":[
   Q(1,"交通与出行：by plane（　）　by train（　）　by subway（　）　by ship（　）　on foot（　）",5,
     opts=["A. 乘飞机　B. 乘火车　C. 乘地铁　D. 乘轮船　E. 步行"], blanks=5),
   Q(2,"地点与方向：post office（　）　bookstore（　）　cinema（　）　hospital（　）　crossing（　）",5,
     opts=["A. 邮局　B. 书店　C. 电影院　D. 医院　E. 十字路口"], blanks=5),
 ]},
 {"name":"三、选出不同类的一项（10分）","questions":[
   Q(1,"（　）",2, opts=["A. by bus　B. by bike　C. traffic light"]),
   Q(2,"（　）",2, opts=["A. happy　B. sad　C. feel"]),
   Q(3,"（　）",2, opts=["A. teacher　B. doctor　C. hospital"]),
   Q(4,"（　）",2, opts=["A. spring　B. summer　C. season"]),
   Q(5,"（　）",2, opts=["A. take　B. took　C. saw"]),
 ]},
 {"name":"四、单项选择（20分）","questions":[
   Q(1,"—— How do you go to school?　—— I go to school ________.",2, opts=["A. by bike　B. on bike　C. in bike"]),
   Q(2,"—— Where is the hospital?　—— It's ________ the bookstore.",2, opts=["A. next to　B. next　C. near to"]),
   Q(3,"Turn left ________ the crossing.",2, opts=["A. at　B. on　C. in"]),
   Q(4,"—— What are you going to do?　—— I'm going to ________.",2, opts=["A. see a film　B. seeing a film　C. saw a film"]),
   Q(5,"—— How do you feel?　—— I feel ________. I lost my key.",2, opts=["A. sad　B. happy　C. excited"]),
   Q(6,"—— What does your father do?　—— He's a ________.",2, opts=["A. policeman　B. police　C. post office"]),
   Q(7,"I have to ________ my homework first.",2, opts=["A. do　B. does　C. doing"]),
   Q(8,"—— What's the matter?　—— I ________ a headache.",2, opts=["A. have　B. has　C. am"]),
   Q(9,"—— What do you want to be?　—— I want to be a ________.",2, opts=["A. scientist　B. science　C. science museum"]),
   Q(10,"—— How can I get to the cinema?　—— ________.",2, opts=["A. Go straight and turn right.　B. It's a cinema.　C. Yes, please."]),
 ]},
 {"name":"五、情景选择（15分）","questions":[
   Q(1,"你想问对方怎么去北京，应该说：________",3, opts=["A. How do you go to Beijing?　B. Where is Beijing?　C. When do you go to Beijing?"]),
   Q(2,"你想问「医院在哪里」，应该说：________",3, opts=["A. Where is the hospital?　B. What is the hospital?　C. How is the hospital?"]),
   Q(3,"你想表达「我打算去看电影」，应该说：________",3, opts=["A. I'm going to see a film.　B. I see a film.　C. I saw a film."]),
   Q(4,"你想问「你感觉怎么样」，应该说：________",3, opts=["A. How do you feel?　B. How old are you?　C. How are you?"]),
   Q(5,"你想表达「我想成为一名科学家」，应该说：________",3, opts=["A. I want to be a scientist.　B. I am a scientist.　C. I like science."]),
 ]},
 {"name":"六、连词成句（注意大小写和标点）（15分）","questions":[
   Q(1,"do / How / to / you / school / go / ?",3, blanks=1),
   Q(2,"is / Where / hospital / the / ?",3, blanks=1),
   Q(3,"going / I'm / see / to / film / a / .",3, blanks=1),
   Q(4,"feel / do / How / you / ?",3, blanks=1),
   Q(5,"want / I / be / to / scientist / a / .",3, blanks=1),
 ]},
 {"name":"七、阅读理解（判断正误，正确写T，错误写F）（20分）","questions":[
   Q(1,"阅读短文，判断下列句子正（T）误（F）。",20, blanks=5,
     opts=["　　Hello! I'm Mike. I'm a student. I often go to school by bus. But sometimes I go on foot, because my home is near the school. On the weekend, I'm going to visit my grandparents. I miss them very much. Yesterday I had a cold, but now I feel better. My dream is to be a doctor, because I want to help sick people.",
           "（1）Mike often goes to school by bus.（　）",
           "（2）Mike's home is far from the school.（　）",
           "（3）Mike is going to visit his grandparents on the weekend.（　）",
           "（4）Mike had a cold yesterday.（　）",
           "（5）Mike wants to be a teacher.（　）"]),
 ]},
]
a = [
 A(1,"S", "air和are均读/eə/。"),
 A(2,"S", "ear和eer均读/ɪə/。"),
 A(3,"S", "igh和ie均读/aɪ/。"),
 A(4,"S", "th均读/θ/。"),
 A(5,"S", "wh均读/h/。"),
 A(1,"A B C D E", "by plane乘飞机、by train乘火车、by subway乘地铁、by ship乘轮船、on foot步行。"),
 A(2,"A B C D E", "post office邮局、bookstore书店、cinema电影院、hospital医院、crossing十字路口。"),
 A(1,"C", "traffic light是名词，其余是交通方式。"),
 A(2,"C", "feel是动词，其余是形容词。"),
 A(3,"C", "hospital是地点，其余是职业。"),
 A(4,"C", "season是总称，其余是具体季节。"),
 A(5,"A", "take是动词原形，其余是过去式。"),
 A(1,"A", "by bike表示骑自行车。"),
 A(2,"A", "next to表示紧挨着。"),
 A(3,"A", "at the crossing在十字路口。"),
 A(4,"A", "be going to后接动词原形。"),
 A(5,"A", "丢了钥匙感到难过，用sad。"),
 A(6,"A", "问职业答职业。"),
 A(7,"A", "have to后接动词原形。"),
 A(8,"A", "主语I用have。"),
 A(9,"A", "想成为科学家用scientist。"),
 A(10,"A", "问路答指路。"),
 A(1,"A", "询问交通方式。"),
 A(2,"A", "询问地点。"),
 A(3,"A", "be going to表示打算。"),
 A(4,"A", "询问感受。"),
 A(5,"A", "want to be表示想成为。"),
 A(1,"How do you go to school?", "疑问词how开头。"),
 A(2,"Where is the hospital?", "询问地点。"),
 A(3,"I'm going to see a film.", "be going to结构。"),
 A(4,"How do you feel?", "询问感受。"),
 A(5,"I want to be a scientist.", "want to be结构。"),
 A(1,"T", "Mike常乘公共汽车上学。"),
 A(2,"F", "Mike家离学校很近。"),
 A(3,"T", "Mike周末打算看望祖父母。"),
 A(4,"T", "Mike昨天感冒了。"),
 A(5,"F", "Mike想成为一名医生。"),
]
out.append(save(m, p, a, "期末质量检测A卷")); print("英语A卷完成")

# ================= B卷 =================
m = base("六年级英语", "上学期期末学业水平测试", "（人教版PEP　三年级起点　2025—2026学年　第一学期）")
p = [
 {"name":"一、判断下列单词划线部分读音是否相同（相同写S，不同写D）（10分）","questions":[
   Q(1,"（　）book　look",2), Q(2,"（　）food　moon",2), Q(3,"（　）this　that",2),
   Q(4,"（　）what　who",2), Q(5,"（　）learn　her",2),
 ]},
 {"name":"二、看图选词，把序号填在括号里（10分）","questions":[
   Q(1,"周末活动：see a film（　）　take a trip（　）　go to the supermarket（　）　have an English lesson（　）　draw pictures（　）",5,
     opts=["A. 看电影　B. 去旅行　C. 去超市　D. 上英语课　E. 画画"], blanks=5),
   Q(2,"心情感受：happy（　）　sad（　）　angry（　）　worried（　）　excited（　）",5,
     opts=["A. 高兴的　B. 难过的　C. 生气的　D. 担心的　E. 兴奋的"], blanks=5),
 ]},
 {"name":"三、选出不同类的一项（10分）","questions":[
   Q(1,"（　）",2, opts=["A. subway　B. plane　C. museum"]),
   Q(2,"（　）",2, opts=["A. worried　B. angry　C. worry"]),
   Q(3,"（　）",2, opts=["A. cinema　B. bookstore　C. singer"]),
   Q(4,"（　）",2, opts=["A. went　B. saw　C. take"]),
   Q(5,"（　）",2, opts=["A. tonight　B. tomorrow　C. yesterday"]),
 ]},
 {"name":"四、单项选择（20分）","questions":[
   Q(1,"—— ________ are you going?　—— To the cinema.",2, opts=["A. Where　B. When　C. What"]),
   Q(2,"I'm going to ________ my grandparents this weekend.",2, opts=["A. visit　B. visited　C. visiting"]),
   Q(3,"—— What did you do last weekend?　—— I ________ a film.",2, opts=["A. saw　B. see　C. sees"]),
   Q(4,"You look sad. What's ________?",2, opts=["A. wrong　B. matter　C. the wrong"]),
   Q(5,"—— How ________ he feel?　—— He feels happy.",2, opts=["A. does　B. do　C. is"]),
   Q(6,"Don't be ________. Everything will be fine.",2, opts=["A. worried　B. worry　C. worries"]),
   Q(7,"—— What are you going to be?　—— I'm going to be a ________.",2, opts=["A. writer　B. write　C. writing"]),
   Q(8,"We should ________ our homework on time.",2, opts=["A. finish　B. finished　C. finishing"]),
   Q(9,"—— ________ your father go to work?　—— By car.",2, opts=["A. How does　B. How do　C. How is"]),
   Q(10,"—— Where is the post office?　—— Go ________ and turn left.",2, opts=["A. straight　B. straightly　C. straighten"]),
 ]},
 {"name":"五、情景选择（15分）","questions":[
   Q(1,"你想问对方周末做了什么，应该说：________",3, opts=["A. What did you do last weekend?　B. What do you do on the weekend?　C. What are you doing?"]),
   Q(2,"你想表达「我打算去看望我的祖父母」，应该说：________",3, opts=["A. I'm going to visit my grandparents.　B. I visited my grandparents.　C. I visit my grandparents."]),
   Q(3,"你想劝对方不要担心，应该说：________",3, opts=["A. Don't worry.　B. Don't be happy.　C. Don't go."]),
   Q(4,"你想问对方「你打算做什么工作」，应该说：________",3, opts=["A. What are you going to be?　B. What do you do?　C. What did you do?"]),
   Q(5,"你想表达「我们应该按时完成作业」，应该说：________",3, opts=["A. We should finish our homework on time.　B. We finished our homework.　C. We are finishing our homework."]),
 ]},
 {"name":"六、连词成句（注意大小写和标点）（15分）","questions":[
   Q(1,"going / Where / you / are / ?",3, blanks=1),
   Q(2,"going / I'm / visit / to / grandparents / my / .",3, blanks=1),
   Q(3,"did / What / do / you / weekend / last / ?",3, blanks=1),
   Q(4,"be / Don't / worried / .",3, blanks=1),
   Q(5,"should / We / our / finish / homework / .",3, blanks=1),
 ]},
 {"name":"七、阅读理解（判断正误，正确写T，错误写F）（20分）","questions":[
   Q(1,"阅读短文，判断下列句子正（T）误（F）。",20, blanks=5,
     opts=["　　Hi! I'm Amy. Last weekend I was very busy. On Saturday morning, I cleaned my room. In the afternoon, I visited my aunt. On Sunday, I went to the bookstore and bought some books. I like reading very much. I'm going to be a writer when I grow up. Next weekend, I'm going to the science museum with my friends.",
           "（1）Amy was very busy last weekend.（　）",
           "（2）Amy cleaned her room on Sunday morning.（　）",
           "（3）Amy visited her aunt on Saturday afternoon.（　）",
           "（4）Amy bought some books on Sunday.（　）",
           "（5）Amy wants to be a doctor.（　）"]),
 ]},
]
a2 = [
 A(1,"S", "oo均读/ʊ/。"),
 A(2,"S", "oo均读/uː/。"),
 A(3,"S", "th均读/ð/。"),
 A(4,"D", "wh在what中读/w/，在who中读/h/。"),
 A(5,"S", "ear和er均读/ɜː/。"),
 A(1,"A B C D E", "see a film看电影、take a trip去旅行、go to the supermarket去超市、have an English lesson上英语课、draw pictures画画。"),
 A(2,"A B C D E", "happy高兴的、sad难过的、angry生气的、worried担心的、excited兴奋的。"),
 A(1,"C", "museum是地点，其余是交通工具。"),
 A(2,"C", "worry是动词，其余是形容词。"),
 A(3,"C", "singer是职业，其余是地点。"),
 A(4,"C", "take是原形，其余是过去式。"),
 A(5,"C", "yesterday是过去时间，其余是将来时间。"),
 A(1,"A", "询问去哪里。"),
 A(2,"A", "be going to后接动词原形。"),
 A(3,"A", "last weekend提示用过去式。"),
 A(4,"A", "What's wrong?表示「怎么了」。"),
 A(5,"A", "主语he用does。"),
 A(6,"A", "Don't be后接形容词。"),
 A(7,"A", "想成为作家用writer。"),
 A(8,"A", "should后接动词原形。"),
 A(9,"A", "主语father是第三人称单数，用does。"),
 A(10,"A", "go straight表示直走。"),
 A(1,"A", "询问过去做了什么。"),
 A(2,"A", "be going to表示打算。"),
 A(3,"A", "劝人不要担心。"),
 A(4,"A", "询问打算做什么工作。"),
 A(5,"A", "should表示应该。"),
 A(1,"Where are you going?", "疑问词where开头。"),
 A(2,"I'm going to visit my grandparents.", "be going to结构。"),
 A(3,"What did you do last weekend?", "一般过去时特殊疑问句。"),
 A(4,"Don't be worried.", "祈使句否定式。"),
 A(5,"We should finish our homework.", "should后接动词原形。"),
 A(1,"T", "Amy上周末很忙。"),
 A(2,"F", "Amy周六上午打扫房间。"),
 A(3,"T", "Amy周六下午看望了姑姑。"),
 A(4,"T", "Amy周日去了书店买书。"),
 A(5,"F", "Amy想成为作家。"),
]
out.append(save(m, p, a2, "学业水平测试B卷")); print("英语B卷完成")

# ================= C卷 =================
m = base("六年级英语", "下学期期末综合检测", "（人教版PEP　三年级起点　2025—2026学年　第二学期）")
p = [
 {"name":"一、判断下列单词划线部分读音是否相同（相同写S，不同写D）（10分）","questions":[
   Q(1,"（　）slow　snow",2), Q(2,"（　）how　window",2), Q(3,"（　）ride　big",2),
   Q(4,"（　）child　china",2), Q(5,"（　）third　bird",2),
 ]},
 {"name":"二、看图选词，把序号填在括号里（10分）","questions":[
   Q(1,"自然环境：air（　）　water（　）　rubbish（　）　smoke（　）　factory（　）",5,
     opts=["A. 空气　B. 水　C. 垃圾　D. 烟　E. 工厂"], blanks=5),
   Q(2,"身体部位：head（　）　arm（　）　leg（　）　tooth（　）　stomach（　）",5,
     opts=["A. 头　B. 手臂　C. 腿　D. 牙齿　E. 胃"], blanks=5),
 ]},
 {"name":"三、选出不同类的一项（10分）","questions":[
   Q(1,"（　）",2, opts=["A. air　B. water　C. clean"]),
   Q(2,"（　）",2, opts=["A. head　B. arm　C. doctor"]),
   Q(3,"（　）",2, opts=["A. rubbish　B. smoke　C. protect"]),
   Q(4,"（　）",2, opts=["A. should　B. must　C. maybe"]),
   Q(5,"（　）",2, opts=["A. careful　B. careless　C. care"]),
 ]},
 {"name":"四、单项选择（20分）","questions":[
   Q(1,"We should ________ the air clean.",2, opts=["A. keep　B. keeps　C. keeping"]),
   Q(2,"Don't ________ water. It's precious.",2, opts=["A. waste　B. wastes　C. wasting"]),
   Q(3,"—— What's the matter with you?　—— I have a ________.",2, opts=["A. headache　B. head　C. heads"]),
   Q(4,"You should ________ a doctor.",2, opts=["A. see　B. sees　C. seeing"]),
   Q(5,"There ________ some rubbish on the ground.",2, opts=["A. is　B. are　C. be"]),
   Q(6,"We should keep our classroom ________.",2, opts=["A. clean　B. cleans　C. cleaning"]),
   Q(7,"Trees can ________ the air clean.",2, opts=["A. make　B. makes　C. making"]),
   Q(8,"—— How can we protect the environment?　—— We should ________.",2, opts=["A. recycle things　B. waste water　C. throw rubbish"]),
   Q(9,"If you are ill, you ________ stay in bed.",2, opts=["A. should　B. should not　C. are not"]),
   Q(10,"—— What should I do?　—— You should take some ________.",2, opts=["A. medicine　B. medicines　C. a medicine"]),
 ]},
 {"name":"五、情景选择（15分）","questions":[
   Q(1,"你想表达「我们应该保持空气清新」，应该说：________",3, opts=["A. We should keep the air clean.　B. We should waste water.　C. We should throw rubbish."]),
   Q(2,"你想问对方「你怎么了」，应该说：________",3, opts=["A. What's the matter with you?　B. How old are you?　C. Where are you from?"]),
   Q(3,"你想告诉对方「你应该去看医生」，应该说：________",3, opts=["A. You should see a doctor.　B. You should stay home.　C. You should eat more."]),
   Q(4,"你想问「我们怎样保护环境」，应该说：________",3, opts=["A. How can we protect the environment?　B. Where is the environment?　C. What is the environment?"]),
   Q(5,"你想表达「树木能使空气清新」，应该说：________",3, opts=["A. Trees can make the air clean.　B. Trees can waste water.　C. Trees are beautiful."]),
 ]},
 {"name":"六、连词成句（注意大小写和标点）（15分）","questions":[
   Q(1,"should / We / air / the / keep / clean / .",3, blanks=1),
   Q(2,"the / What's / with / matter / you / ?",3, blanks=1),
   Q(3,"should / You / doctor / see / a / .",3, blanks=1),
   Q(4,"can / How / protect / we / environment / the / ?",3, blanks=1),
   Q(5,"can / Trees / air / the / make / clean / .",3, blanks=1),
 ]},
 {"name":"七、阅读理解（判断正误，正确写T，错误写F）（20分）","questions":[
   Q(1,"阅读短文，判断下列句子正（T）误（F）。",20, blanks=5,
     opts=["　　Hello! I'm Lily. Our environment is very important. But there are many problems now. Some factories produce smoke. Cars make the air dirty. People throw rubbish everywhere. We should do something to protect the environment. We should plant more trees. We should keep the air and water clean. We should not waste water or electricity. If everyone does a little, our city will be more beautiful.",
           "（1）The environment is very important.（　）",
           "（2）Factories and cars can make the air dirty.（　）",
           "（3）We should throw rubbish everywhere.（　）",
           "（4）We should plant more trees.（　）",
           "（5）Only some people should protect the environment.（　）"]),
 ]},
]
a3 = [
 A(1,"S", "ow均读/əʊ/。"),
 A(2,"D", "ow在how中读/aʊ/，在window中读/əʊ/。"),
 A(3,"D", "i在ride中读/aɪ/，在big中读/ɪ/。"),
 A(4,"D", "ch在child中读/tʃaɪ/（i不发字母音的组合不同），在china中读/tʃ/，读音不同。"),
 A(5,"S", "ir均读/ɜː/。"),
 A(1,"A B C D E", "air空气、water水、rubbish垃圾、smoke烟、factory工厂。"),
 A(2,"A B C D E", "head头、arm手臂、leg腿、tooth牙齿、stomach胃。"),
 A(1,"C", "clean是形容词/动词，其余是名词。"),
 A(2,"C", "doctor是职业，其余是身体部位。"),
 A(3,"C", "protect是动词，其余是名词。"),
 A(4,"C", "maybe是副词，其余是情态动词。"),
 A(5,"C", "care是动词/名词，其余是形容词。"),
 A(1,"A", "should后接动词原形。"),
 A(2,"A", "Don't后接动词原形。"),
 A(3,"A", "have a headache表示头疼。"),
 A(4,"A", "should后接动词原形。"),
 A(5,"A", "rubbish是不可数名词，用is。"),
 A(6,"A", "keep+宾语+形容词。"),
 A(7,"A", "can后接动词原形。"),
 A(8,"A", "保护环境应回收东西。"),
 A(9,"A", "生病了应该卧床休息。"),
 A(10,"A", "take some medicine吃药。"),
 A(1,"A", "保持空气清新。"),
 A(2,"A", "询问怎么了。"),
 A(3,"A", "建议看医生。"),
 A(4,"A", "询问如何保护环境。"),
 A(5,"A", "树木使空气清新。"),
 A(1,"We should keep the air clean.", "should后接动词原形。"),
 A(2,"What's the matter with you?", "固定句型。"),
 A(3,"You should see a doctor.", "建议句型。"),
 A(4,"How can we protect the environment?", "疑问词how开头。"),
 A(5,"Trees can make the air clean.", "can后接动词原形。"),
 A(1,"T", "环境非常重要。"),
 A(2,"T", "工厂和汽车会使空气变脏。"),
 A(3,"F", "我们不应该随处乱扔垃圾。"),
 A(4,"T", "我们应该多种树。"),
 A(5,"F", "每个人都应该保护环境。"),
]
out.append(save(m, p, a3, "综合检测C卷")); print("英语C卷完成")

# ================= D卷 =================
m = base("六年级英语", "期末复习质量检测", "（人教版PEP　三年级起点　2025—2026学年　第二学期）")
p = [
 {"name":"一、判断下列单词划线部分读音是否相同（相同写S，不同写D）（10分）","questions":[
   Q(1,"（　）cat　cake",2), Q(2,"（　）bike　like",2), Q(3,"（　）nose　not",2),
   Q(4,"（　）cute　cup",2), Q(5,"（　）name　game",2),
 ]},
 {"name":"二、看图选词，把序号填在括号里（10分）","questions":[
   Q(1,"职业：singer（　）　writer（　）　scientist（　）　engineer（　）　pilot（　）",5,
     opts=["A. 歌手　B. 作家　C. 科学家　D. 工程师　E. 飞行员"], blanks=5),
   Q(2,"动词过去式：went（　）　saw（　）　took（　）　did（　）　had（　）",5,
     opts=["A. go的过去式　B. see的过去式　C. take的过去式　D. do的过去式　E. have的过去式"], blanks=5),
 ]},
 {"name":"三、选出不同类的一项（10分）","questions":[
   Q(1,"（　）",2, opts=["A. singer　B. writer　C. sing"]),
   Q(2,"（　）",2, opts=["A. went　B. saw　C. go"]),
   Q(3,"（　）",2, opts=["A. our　B. their　C. we"]),
   Q(4,"（　）",2, opts=["A. worry　B. happy　C. excited"]),
   Q(5,"（　）",2, opts=["A. tonight　B. tomorrow　C. last night"]),
 ]},
 {"name":"四、单项选择（20分）","questions":[
   Q(1,"—— What ________ you do yesterday?　—— I went swimming.",2, opts=["A. did　B. do　C. does"]),
   Q(2,"I ________ to the park with my parents last Sunday.",2, opts=["A. went　B. go　C. going"]),
   Q(3,"—— ________ are you going to do tomorrow?　—— I'm going to read books.",2, opts=["A. What　B. Where　C. When"]),
   Q(4,"He ________ his homework last night.",2, opts=["A. did　B. does　C. do"]),
   Q(5,"—— How was your weekend?　—— It ________ great!",2, opts=["A. was　B. is　C. were"]),
   Q(6,"My brother is good at ________.",2, opts=["A. singing　B. sing　C. sings"]),
   Q(7,"—— ________ did you go last summer holiday?　—— I went to Beijing.",2, opts=["A. Where　B. What　C. How"]),
   Q(8,"I'm going to ________ a trip next week.",2, opts=["A. take　B. took　C. taking"]),
   Q(9,"—— What does your mother do?　—— She is a ________.",2, opts=["A. teacher　B. teach　C. teaches"]),
   Q(10,"—— Did you ________ your homework?　—— Yes, I did.",2, opts=["A. finish　B. finished　C. finishing"]),
 ]},
 {"name":"五、情景选择（15分）","questions":[
   Q(1,"你想问对方「上个周末你做了什么」，应该说：________",3, opts=["A. What did you do last weekend?　B. What are you doing?　C. What will you do?"]),
   Q(2,"你想表达「上周日我和父母去了公园」，应该说：________",3, opts=["A. I went to the park with my parents last Sunday.　B. I go to the park.　C. I am going to the park."]),
   Q(3,"你想问对方「明天你打算做什么」，应该说：________",3, opts=["A. What are you going to do tomorrow?　B. What did you do?　C. How are you?"]),
   Q(4,"你想问对方「去年暑假你去了哪里」，应该说：________",3, opts=["A. Where did you go last summer holiday?　B. Where are you going?　C. Where do you go?"]),
   Q(5,"你想表达「我的弟弟擅长唱歌」，应该说：________",3, opts=["A. My brother is good at singing.　B. My brother likes sing.　C. My brother can singing."]),
 ]},
 {"name":"六、连词成句（注意大小写和标点）（15分）","questions":[
   Q(1,"did / What / do / you / yesterday / ?",3, blanks=1),
   Q(2,"went / I / to / park / the / .",3, blanks=1),
   Q(3,"are / What / going / you / to / do / ?",3, blanks=1),
   Q(4,"is / brother / My / at / good / singing / .",3, blanks=1),
   Q(5,"you / Did / finish / homework / your / ?",3, blanks=1),
 ]},
 {"name":"七、阅读理解（判断正误，正确写T，错误写F）（20分）","questions":[
   Q(1,"阅读短文，判断下列句子正（T）误（F）。",20, blanks=5,
     opts=["　　Hi! I'm Tom. Last summer holiday, I went to Sanya with my family. We went there by plane. The weather was sunny and hot. We swam in the sea and played on the beach. We also ate some delicious seafood. I took many photos. We had a good time. Next summer holiday, we are going to visit Beijing. We are going to see the Great Wall.",
           "（1）Tom went to Sanya last summer holiday.（　）",
           "（2）Tom went to Sanya by train.（　）",
           "（3）The weather in Sanya was sunny and hot.（　）",
           "（4）Tom swam in the sea.（　）",
           "（5）Tom is going to visit Beijing next summer holiday.（　）"]),
 ]},
]
a4 = [
 A(1,"D", "a在cat中读/æ/，在cake中读/eɪ/。"),
 A(2,"S", "i均读/aɪ/。"),
 A(3,"D", "o在nose中读/əʊ/，在not中读/ɒ/。"),
 A(4,"D", "u在cute中读/juː/，在cup中读/ʌ/。"),
 A(5,"S", "a均读/eɪ/。"),
 A(1,"A B C D E", "singer歌手、writer作家、scientist科学家、engineer工程师、pilot飞行员。"),
 A(2,"A B C D E", "went（go的过去式）、saw（see的过去式）、took（take的过去式）、did（do的过去式）、had（have的过去式）。"),
 A(1,"C", "sing是动词，其余是职业名词。"),
 A(2,"C", "go是原形，其余是过去式。"),
 A(3,"C", "we是人称代词主格，其余是形容词性物主代词。"),
 A(4,"A", "worry是动词，其余是形容词。"),
 A(5,"C", "last night是过去时间，其余是将来时间。"),
 A(1,"A", "yesterday提示用一般过去时。"),
 A(2,"A", "last Sunday提示用过去式。"),
 A(3,"A", "询问打算做什么。"),
 A(4,"A", "last night提示用过去式。"),
 A(5,"A", "was是is的过去式。"),
 A(6,"A", "be good at后接动词-ing形式。"),
 A(7,"A", "询问地点用where。"),
 A(8,"A", "be going to后接动词原形。"),
 A(9,"A", "问职业答职业。"),
 A(10,"A", "did后接动词原形。"),
 A(1,"A", "询问过去做了什么。"),
 A(2,"A", "一般过去时。"),
 A(3,"A", "be going to表示打算。"),
 A(4,"A", "一般过去时，询问地点。"),
 A(5,"A", "be good at doing sth。"),
 A(1,"What did you do yesterday?", "一般过去时特殊疑问句。"),
 A(2,"I went to the park.", "一般过去时。"),
 A(3,"What are you going to do?", "be going to结构。"),
 A(4,"My brother is good at singing.", "be good at doing sth。"),
 A(5,"Did you finish your homework?", "一般过去时一般疑问句。"),
 A(1,"T", "Tom去年暑假去了三亚。"),
 A(2,"F", "Tom乘飞机去了三亚。"),
 A(3,"T", "三亚的天气晴朗炎热。"),
 A(4,"T", "Tom在海里游泳。"),
 A(5,"T", "Tom打算明年暑假去北京。"),
]
out.append(save(m, p, a4, "复习质量检测D卷")); print("英语D卷完成")

# ================= E卷 =================
m = base("六年级英语", "期末学业质量监测", "（人教版PEP　三年级起点　2025—2026学年　全学年）")
p = [
 {"name":"一、判断下列单词划线部分读音是否相同（相同写S，不同写D）（10分）","questions":[
   Q(1,"（　）sea　tea",2), Q(2,"（　）high　big",2), Q(3,"（　）how　now",2),
   Q(4,"（　）nurse　horse",2), Q(5,"（　）tree　three",2),
 ]},
 {"name":"二、看图选词，把序号填在括号里（10分）","questions":[
   Q(1,"学校设施：library（　）　playground（　）　gym（　）　art room（　）　computer room（　）",5,
     opts=["A. 图书馆　B. 操场　C. 体育馆　D. 美术室　E. 计算机房"], blanks=5),
   Q(2,"学习用品：schoolbag（　）　notebook（　）　storybook（　）　dictionary（　）　ruler（　）",5,
     opts=["A. 书包　B. 笔记本　C. 故事书　D. 字典　E. 尺子"], blanks=5),
 ]},
 {"name":"三、选出不同类的一项（10分）","questions":[
   Q(1,"（　）",2, opts=["A. Monday　B. Tuesday　C. holiday"]),
   Q(2,"（　）",2, opts=["A. swimming　B. running　C. run"]),
   Q(3,"（　）",2, opts=["A. him　B. her　C. I"]),
   Q(4,"（　）",2, opts=["A. small　B. big　C. size"]),
   Q(5,"（　）",2, opts=["A. bought　B. taught　C. teach"]),
 ]},
 {"name":"四、单项选择（20分）","questions":[
   Q(1,"There ________ a lot of books in the library.",2, opts=["A. are　B. is　C. be"]),
   Q(2,"—— ________ is the weather in winter?　—— It's cold.",2, opts=["A. How　B. What　C. Where"]),
   Q(3,"I usually go to school ________ foot.",2, opts=["A. on　B. by　C. in"]),
   Q(4,"—— What's your ________ sport?　—— Basketball.",2, opts=["A. favourite　B. like　C. love"]),
   Q(5,"My mother ________ shopping every Sunday.",2, opts=["A. goes　B. go　C. going"]),
   Q(6,"—— ________ do you go to bed?　—— At ten o'clock.",2, opts=["A. When　B. Where　C. What"]),
   Q(7,"There ________ some water in the glass.",2, opts=["A. is　B. are　C. be"]),
   Q(8,"—— ________ is your English teacher?　—— Miss Li.",2, opts=["A. Who　B. Whose　C. What"]),
   Q(9,"I'm ________ than my brother.",2, opts=["A. taller　B. tall　C. tallest"]),
   Q(10,"—— ________ you like apples?　—— Yes, I do.",2, opts=["A. Do　B. Are　C. Is"]),
 ]},
 {"name":"五、情景选择（15分）","questions":[
   Q(1,"你想问「图书馆里有多少本书」，应该说：________",3, opts=["A. How many books are there in the library?　B. Where is the library?　C. What is a library?"]),
   Q(2,"你想问「冬天天气怎么样」，应该说：________",3, opts=["A. What's the weather like in winter?　B. When is winter?　C. Where is winter?"]),
   Q(3,"你想问「你最喜欢什么运动」，应该说：________",3, opts=["A. What's your favourite sport?　B. Do you like sports?　C. Can you play sports?"]),
   Q(4,"你想表达「我通常步行去上学」，应该说：________",3, opts=["A. I usually go to school on foot.　B. I usually go to school by bus.　C. I usually go to school by bike."]),
   Q(5,"你想问「你什么时候睡觉」，应该说：________",3, opts=["A. When do you go to bed?　B. Where do you go to bed?　C. What do you do?"]),
 ]},
 {"name":"六、连词成句（注意大小写和标点）（15分）","questions":[
   Q(1,"many / How / are / books / there / ?",3, blanks=1),
   Q(2,"the / What's / like / weather / winter / in / ?",3, blanks=1),
   Q(3,"is / favourite / What / sport / your / ?",3, blanks=1),
   Q(4,"school / I / to / on / foot / go / usually / .",3, blanks=1),
   Q(5,"do / When / you / go / bed / to / ?",3, blanks=1),
 ]},
 {"name":"七、阅读理解（判断正误，正确写T，错误写F）（20分）","questions":[
   Q(1,"阅读短文，判断下列句子正（T）误（F）。",20, blanks=5,
     opts=["　　Hello! I'm Sarah. I'm a student in Grade Six. I have a happy family. My father is a doctor. He works in a big hospital. My mother is a teacher. She teaches English. I have a little brother. He is only five. He likes playing with toys. I love my family very much. On Sundays, we often go to the park together. My favourite season is spring, because it's warm and beautiful.",
           "（1）Sarah is a student in Grade Six.（　）",
           "（2）Sarah's father is a teacher.（　）",
           "（3）Sarah's mother teaches English.（　）",
           "（4）Sarah has a little brother.（　）",
           "（5）Sarah's favourite season is winter.（　）"]),
 ]},
]
a5 = [
 A(1,"S", "ea均读/iː/。"),
 A(2,"D", "igh读/aɪ/，i在big中读/ɪ/。"),
 A(3,"S", "ow均读/aʊ/。"),
 A(4,"D", "ur读/ɜː/，or读/ɔː/。"),
 A(5,"D", "tree中tr读/tr/，three中th读/θ/。"),
 A(1,"A B C D E", "library图书馆、playground操场、gym体育馆、art room美术室、computer room计算机房。"),
 A(2,"A B C D E", "schoolbag书包、notebook笔记本、storybook故事书、dictionary字典、ruler尺子。"),
 A(1,"C", "holiday是总称，其余是星期。"),
 A(2,"C", "run是动词原形，其余是动词-ing形式。"),
 A(3,"C", "I是人称代词主格，其余是宾格。"),
 A(4,"C", "size是名词，其余是形容词。"),
 A(5,"C", "teach是原形，其余是过去式。"),
 A(1,"A", "books是可数名词复数，用are。"),
 A(2,"A", "询问天气用how。"),
 A(3,"A", "on foot表示步行。"),
 A(4,"A", "最喜欢的运动用favourite。"),
 A(5,"A", "主语mother是单数，用goes。"),
 A(6,"A", "询问时间用when。"),
 A(7,"A", "water是不可数名词，用is。"),
 A(8,"A", "询问人物用who。"),
 A(9,"A", "than提示用比较级taller。"),
 A(10,"A", "实义动词like用do提问。"),
 A(1,"A", "询问数量。"),
 A(2,"A", "询问天气。"),
 A(3,"A", "询问最喜欢的运动。"),
 A(4,"A", "步行上学。"),
 A(5,"A", "询问时间。"),
 A(1,"How many books are there?", "there be句型的特殊疑问句。"),
 A(2,"What's the weather like in winter?", "固定句型。"),
 A(3,"What is your favourite sport?", "询问最喜欢的运动。"),
 A(4,"I usually go to school on foot.", "on foot表示步行。"),
 A(5,"When do you go to bed?", "疑问词when开头。"),
 A(1,"T", "Sarah是六年级学生。"),
 A(2,"F", "Sarah的爸爸是医生。"),
 A(3,"T", "Sarah的妈妈教英语。"),
 A(4,"T", "Sarah有一个弟弟。"),
 A(5,"F", "Sarah最喜欢的季节是春天。"),
]
out.append(save(m, p, a5, "学业质量监测E卷")); print("英语E卷完成")

for f in out:
    print("已生成:", f)
