# -*- coding: utf-8 -*-
"""五年级 英语（人教版PEP）期末试卷（5套）"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from paper_common import save, base, Q, A
out = []

# ================= A卷 =================
m = base("五年级英语", "第一学期期末质量检测", "（人教版PEP　三年级起点　2025—2026学年　第一学期）")
p = [
 {"name":"一、判断下列单词划线部分读音是否相同（相同写S，不同写D）（10分）","questions":[
   Q(1,"（　）tea　read",2), Q(2,"（　）book　food",2), Q(3,"（　）how　house",2),
   Q(4,"（　）rain　day",2), Q(5,"（　）car　for",2),
 ]},
 {"name":"二、看图选词，把序号填在括号里（10分）","questions":[
   Q(1,"日常活动：get up（　）　have breakfast（　）　go to school（　）　do homework（　）　go to bed（　）",5,
     opts=["A. 起床　B. 吃早饭　C. 去上学　D. 做作业　E. 上床睡觉"], blanks=5),
   Q(2,"周末活动：visit grandparents（　）　go shopping（　）　climb mountains（　）　take a dancing class（　）　play sports（　）",5,
     opts=["A. 看望祖父母　B. 去购物　C. 爬山　D. 上舞蹈课　E. 做运动"], blanks=5),
 ]},
 {"name":"三、选出不同类的一项（10分）","questions":[
   Q(1,"（　）",2, opts=["A. Monday　B. Sunday　C. spring"]),
   Q(2,"（　）",2, opts=["A. spring　B. summer　C. weekend"]),
   Q(3,"（　）",2, opts=["A. by bus　B. on foot　C. library"]),
   Q(4,"（　）",2, opts=["A. teacher　B. doctor　C. hospital"]),
   Q(5,"（　）",2, opts=["A. windy　B. rainy　C. wind"]),
 ]},
 {"name":"四、单项选择（20分）","questions":[
   Q(1,"—— When do you get up?　—— I get up ________ six o'clock.",2, opts=["A. at　B. in　C. on"]),
   Q(2,"—— What do you do on the weekend?　—— I often ________.",2, opts=["A. play football　B. plays football　C. playing football"]),
   Q(3,"I usually go to school ________ foot.",2, opts=["A. by　B. on　C. in"]),
   Q(4,"—— Why do you like summer?　—— ________ I can swim.",2, opts=["A. Because　B. So　C. But"]),
   Q(5,"—— Whose book is this?　—— It's ________.",2, opts=["A. Mike　B. Mike's　C. Mikes"]),
   Q(6,"My birthday is ________ October.",2, opts=["A. in　B. on　C. at"]),
   Q(7,"There ________ a library in my school.",2, opts=["A. is　B. are　C. be"]),
   Q(8,"—— Is there a hospital near here?　—— Yes, ________.",2, opts=["A. there is　B. it is　C. there are"]),
   Q(9,"—— How do you go to Beijing?　—— ________.",2, opts=["A. By train.　B. On train.　C. In train."]),
   Q(10,"—— What is your father?　—— He is a ________.",2, opts=["A. doctor　B. hospital　C. big"]),
 ]},
 {"name":"五、情景选择（15分）","questions":[
   Q(1,"你想问对方周末做什么，应该问：________",3, opts=["A. What do you do on the weekend?　B. Where are you?　C. How old are you?"]),
   Q(2,"你想表达「我通常七点吃早饭」，应该说：________",3, opts=["A. I usually have breakfast at seven.　B. I usually get up at seven.　C. I usually go to bed at seven."]),
   Q(3,"你想问对方怎么去上学，应该问：________",3, opts=["A. How do you go to school?　B. Where is your school?　C. When do you go to school?"]),
   Q(4,"你想说「我最喜欢的季节是秋天」，应该说：________",3, opts=["A. My favourite season is autumn.　B. I like autumn very much.　C. Autumn is a season."]),
   Q(5,"你想说明「图书馆在书店旁边」，应该说：________",3, opts=["A. The library is next to the bookstore.　B. The library is a bookstore.　C. The library is far from the bookstore."]),
 ]},
 {"name":"六、连词成句（注意大小写和标点）（15分）","questions":[
   Q(1,"do / What / you / on / do / the / weekend / ?",3, blanks=1),
   Q(2,"to / I / school / go / foot / on / usually / .",3, blanks=1),
   Q(3,"season / is / favourite / My / autumn / .",3, blanks=1),
   Q(4,"there / Is / a / near / park / here / ?",3, blanks=1),
   Q(5,"birthday / is / When / your / ?",3, blanks=1),
 ]},
 {"name":"七、阅读理解（判断正误，正确写T，错误写F）（20分）","questions":[
   Q(1,"阅读短文，判断下列句子正（T）误（F）。",20, blanks=5,
     opts=["　　Hello! I'm Tom. I'm a student. On weekdays, I get up at six thirty. I go to school at seven. I have four classes in the morning. I like Fridays, because I have PE class. On the weekend, I often visit my grandparents. Sometimes I go shopping with my mother. My favourite season is summer, because I can swim in the river.",
           "（1）Tom gets up at six thirty on weekdays.（　）",
           "（2）Tom has PE class on Fridays.（　）",
           "（3）Tom often visits his grandparents on the weekend.（　）",
           "（4）Tom's favourite season is winter.（　）",
           "（5）Tom can swim in the river in summer.（　）"]),
 ]},
]
a = [
 A(1,"S", "ea读/iː/。"),
 A(2,"D", "oo在book中读/ʊ/，在food中读/uː/。"),
 A(3,"S", "ou和ow均读/aʊ/。"),
 A(4,"S", "ai和ay均读/eɪ/。"),
 A(5,"D", "ar读/ɑː/，or读/ɔː/。"),
 A(1,"A B C D E", "get up起床、have breakfast吃早饭、go to school去上学、do homework做作业、go to bed上床睡觉。"),
 A(2,"A B C D E", "visit grandparents看望祖父母、go shopping去购物、climb mountains爬山、take a dancing class上舞蹈课、play sports做运动。"),
 A(1,"C", "spring是季节，其余是星期。"),
 A(2,"C", "weekend是周末，其余是季节。"),
 A(3,"C", "library是地点，其余是交通方式。"),
 A(4,"C", "hospital是地点，其余是职业。"),
 A(5,"C", "wind是名词，其余是形容词。"),
 A(1,"A", "具体时刻前用at。"),
 A(2,"A", "often后接动词原形。"),
 A(3,"B", "on foot表示步行。"),
 A(4,"A", "why提问用because回答。"),
 A(5,"B", "表示所属用名词所有格Mike's。"),
 A(6,"A", "月份前用in。"),
 A(7,"A", "a library是单数，用is。"),
 A(8,"A", "there be句型肯定回答用there is。"),
 A(9,"A", "by train表示乘火车。"),
 A(10,"A", "问职业答职业。"),
 A(1,"A", "询问周末活动。"),
 A(2,"A", "吃早饭have breakfast。"),
 A(3,"A", "询问交通方式用how。"),
 A(4,"A", "最喜欢的季节my favourite season。"),
 A(5,"A", "next to表示旁边。"),
 A(1,"What do you do on the weekend?", "注意句首字母大写。"),
 A(2,"I usually go to school on foot.", "usually位于be动词后、实义动词前。"),
 A(3,"My favourite season is autumn.", "注意拼写favourite。"),
 A(4,"Is there a park near here?", "there be句型一般疑问句。"),
 A(5,"When is your birthday?", "疑问词when开头。"),
 A(1,"T", "Tom工作日起床时间是六点半。"),
 A(2,"T", "Tom周五有体育课。"),
 A(3,"T", "Tom周末常看望祖父母。"),
 A(4,"F", "Tom最喜欢的季节是夏天。"),
 A(5,"T", "Tom夏天可以在河里游泳。"),
]
out.append(save(m, p, a, "期末质量检测A卷")); print("英语A卷完成")

# ================= B卷 =================
m = base("五年级英语", "上学期期末学业水平测试", "（人教版PEP　三年级起点　2025—2026学年　第一学期）")
p = [
 {"name":"一、判断下列单词划线部分读音是否相同（相同写S，不同写D）（10分）","questions":[
   Q(1,"（　）see　tree",2), Q(2,"（　）moon　look",2), Q(3,"（　）snow　window",2),
   Q(4,"（　）high　pie",2), Q(5,"（　）her　bird",2),
 ]},
 {"name":"二、看图选词，把序号填在括号里（10分）","questions":[
   Q(1,"地点：library（　）　hospital（　）　cinema（　）　bookstore（　）　post office（　）",5,
     opts=["A. 图书馆　B. 医院　C. 电影院　D. 书店　E. 邮局"], blanks=5),
   Q(2,"方向位置：in front of（　）　behind（　）　beside（　）　between（　）　next to（　）",5,
     opts=["A. 在……前面　B. 在……后面　C. 在……旁边　D. 在……之间　E. 紧挨着"], blanks=5),
 ]},
 {"name":"三、选出不同类的一项（10分）","questions":[
   Q(1,"（　）",2, opts=["A. January　B. February　C. Monday"]),
   Q(2,"（　）",2, opts=["A. National Day　B. Children's Day　C. holiday"]),
   Q(3,"（　）",2, opts=["A. by subway　B. by plane　C. on the left"]),
   Q(4,"（　）",2, opts=["A. cooking　B. singer　C. writer"]),
   Q(5,"（　）",2, opts=["A. cloudy　B. snowy　C. cloud"]),
 ]},
 {"name":"四、单项选择（20分）","questions":[
   Q(1,"—— ________ is the library?　—— It's next to the bank.",2, opts=["A. Where　B. When　C. What"]),
   Q(2,"I go to Shanghai ________ plane.",2, opts=["A. by　B. on　C. take"]),
   Q(3,"—— ________ books are these?　—— They're mine.",2, opts=["A. Whose　B. Who　C. What"]),
   Q(4,"—— How ________ you go to school?　—— By bike.",2, opts=["A. do　B. does　C. is"]),
   Q(5,"Turn right ________ the traffic lights.",2, opts=["A. at　B. on　C. in"]),
   Q(6,"—— What's the weather like in spring?　—— ________.",2, opts=["A. It's warm.　B. It's Tuesday.　C. It's autumn."]),
   Q(7,"—— ________ is your birthday?　—— It's in May.",2, opts=["A. When　B. Where　C. What"]),
   Q(8,"There ________ two cinemas in my city.",2, opts=["A. are　B. is　C. be"]),
   Q(9,"—— What does your mother do?　—— She's a ________.",2, opts=["A. nurse　B. hospital　C. shop"]),
   Q(10,"—— ________ is it?　—— It's eight o'clock.",2, opts=["A. What time　B. How many　C. How old"]),
 ]},
 {"name":"五、情景选择（15分）","questions":[
   Q(1,"你想问对方「图书馆在哪里」，应该说：________",3, opts=["A. Where is the library?　B. What is the library?　C. How is the library?"]),
   Q(2,"你想表达「我坐地铁去上学」，应该说：________",3, opts=["A. I go to school by subway.　B. I go to school on subway.　C. I go to school in subway."]),
   Q(3,"你想问对方「你的生日在什么时候」，应该说：________",3, opts=["A. When is your birthday?　B. Where is your birthday?　C. What is your birthday?"]),
   Q(4,"你想表达「在春天天气很暖和」，应该说：________",3, opts=["A. It's warm in spring.　B. It's cold in spring.　C. It's hot in spring."]),
   Q(5,"你想告诉对方「在邮局向左转」，应该说：________",3, opts=["A. Turn left at the post office.　B. Turn right at the post office.　C. Go straight at the post office."]),
 ]},
 {"name":"六、连词成句（注意大小写和标点）（15分）","questions":[
   Q(1,"is / Where / library / the / ?",3, blanks=1),
   Q(2,"school / I / to / by / go / bike / .",3, blanks=1),
   Q(3,"is / birthday / When / your / ?",3, blanks=1),
   Q(4,"warm / in / It / is / spring / .",3, blanks=1),
   Q(5,"left / Turn / post / the / at / office / .",3, blanks=1),
 ]},
 {"name":"七、阅读理解（判断正误，正确写T，错误写F）（20分）","questions":[
   Q(1,"阅读短文，判断下列句子正（T）误（F）。",20, blanks=5,
     opts=["　　Hello! I'm Lily. I live in a big city. There is a big library near my home. I often read books there on the weekend. There is a cinema behind the library. My favourite season is winter, because I can make a snowman. My birthday is in December. In winter, I usually wear a coat and a scarf.",
           "（1）Lily lives in a small city.（　）",
           "（2）There is a big library near Lily's home.（　）",
           "（3）The cinema is behind the library.（　）",
           "（4）Lily's favourite season is winter.（　）",
           "（5）Lily's birthday is in November.（　）"]),
 ]},
]
a2 = [
 A(1,"S", "ee读/iː/。"),
 A(2,"D", "oo在moon中读/uː/，在look中读/ʊ/。"),
 A(3,"S", "ow均读/əʊ/。"),
 A(4,"S", "igh和ie均读/aɪ/。"),
 A(5,"S", "er和ir均读/ɜː/。"),
 A(1,"A B C D E", "library图书馆、hospital医院、cinema电影院、bookstore书店、post office邮局。"),
 A(2,"A B C D E", "in front of在……前面、behind在……后面、beside在……旁边、between在……之间、next to紧挨着。"),
 A(1,"C", "Monday是星期，其余是月份。"),
 A(2,"C", "holiday是节日总称，其余是具体节日。"),
 A(3,"C", "on the left是方位，其余是交通方式。"),
 A(4,"A", "cooking是「烹饪」（动词-ing形式），singer和writer是表示职业的名词。"),
 A(5,"C", "cloud是名词，其余是形容词。"),
 A(1,"A", "询问地点用where。"),
 A(2,"A", "by plane表示乘飞机。"),
 A(3,"A", "询问所属用whose。"),
 A(4,"A", "主语you用助动词do。"),
 A(5,"A", "at the traffic lights在红绿灯处。"),
 A(6,"A", "询问天气答天气。"),
 A(7,"A", "询问时间用when。"),
 A(8,"A", "two cinemas是复数，用are。"),
 A(9,"A", "问职业答职业。"),
 A(10,"A", "询问时间用what time。"),
 A(1,"A", "询问地点。"),
 A(2,"A", "by subway表示乘地铁。"),
 A(3,"A", "询问时间。"),
 A(4,"A", "spring暖warm。"),
 A(5,"A", "向左转用turn left。"),
 A(1,"Where is the library?", "注意语序。"),
 A(2,"I go to school by bike.", "by+交通工具。"),
 A(3,"When is your birthday?", "疑问词开头。"),
 A(4,"It is warm in spring.", "主语it指天气。"),
 A(5,"Turn left at the post office.", "祈使句。"),
 A(1,"F", "Lily住在一个大城市。"),
 A(2,"T", "Lily家附近有一个大图书馆。"),
 A(3,"T", "电影院在图书馆后面。"),
 A(4,"T", "Lily最喜欢的季节是冬天。"),
 A(5,"F", "Lily的生日在十二月。"),
]
out.append(save(m, p, a2, "学业水平测试B卷")); print("英语B卷完成")

# ================= C卷 =================
m = base("五年级英语", "下学期期末综合检测", "（人教版PEP　三年级起点　2025—2026学年　第二学期）")
p = [
 {"name":"一、判断下列单词划线部分读音是否相同（相同写S，不同写D）（10分）","questions":[
   Q(1,"（　）arm　card",2), Q(2,"（　）nurse　horse",2), Q(3,"（　）blue　student",2),
   Q(4,"（　）eight　light",2), Q(5,"（　）coat　goat",2),
 ]},
 {"name":"二、看图选词，把序号填在括号里（10分）","questions":[
   Q(1,"月份：January（　）　March（　）　June（　）　September（　）　December（　）",5,
     opts=["A. 一月　B. 三月　C. 六月　D. 九月　E. 十二月"], blanks=5),
   Q(2,"天气：sunny（　）　windy（　）　cloudy（　）　rainy（　）　snowy（　）　",5,
     opts=["A. 晴朗的　B. 有风的　C. 多云的　D. 下雨的　E. 下雪的"], blanks=5),
 ]},
 {"name":"三、选出不同类的一项（10分）","questions":[
   Q(1,"（　）",2, opts=["A. Spring Festival　B. Mid-Autumn Day　C. Christmas tree"]),
   Q(2,"（　）",2, opts=["A. sunny　B. cloudy　C. weather"]),
   Q(3,"（　）",2, opts=["A. always　B. usually　C. walk"]),
   Q(4,"（　）",2, opts=["A. brother　B. sister　C. woman"]),
   Q(5,"（　）",2, opts=["A. sleeping　B. reading　C. book"]),
 ]},
 {"name":"四、单项选择（20分）","questions":[
   Q(1,"—— What ________ you doing?　—— I'm reading a book.",2, opts=["A. are　B. is　C. do"]),
   Q(2,"Look! The children ________ football on the playground.",2, opts=["A. are playing　B. play　C. plays"]),
   Q(3,"—— Whose bag is this?　—— It's ________.",2, opts=["A. Amy's　B. Amy　C. Amys"]),
   Q(4,"My mother is ________ TV now.",2, opts=["A. watching　B. watch　C. watches"]),
   Q(5,"—— Are they sleeping?　—— No, ________.",2, opts=["A. they aren't　B. they are　C. it isn't"]),
   Q(6,"What's ________ like in autumn?　—— It's cool.",2, opts=["A. the weather　B. weather　C. a weather"]),
   Q(7,"—— ________ is he doing?　—— He's writing an email.",2, opts=["A. What　B. Where　C. When"]),
   Q(8,"I like ________ in the snow.",2, opts=["A. playing　B. play　C. plays"]),
   Q(9,"—— Can you ________?　—— Yes, I can.",2, opts=["A. swim　B. swimming　C. swims"]),
   Q(10,"—— When is Christmas?　—— It's in ________.",2, opts=["A. December　B. November　C. October"]),
 ]},
 {"name":"五、情景选择（15分）","questions":[
   Q(1,"你想问对方在做什么，应该说：________",3, opts=["A. What are you doing?　B. Where are you?　C. How are you?"]),
   Q(2,"你想表达「我正在看一本书」，应该说：________",3, opts=["A. I'm reading a book.　B. I read a book.　C. I like books."]),
   Q(3,"你想问对方秋天的天气怎么样，应该说：________",3, opts=["A. What's the weather like in autumn?　B. When is autumn?　C. Where is autumn?"]),
   Q(4,"你想表达「春节在一月或二月」，应该说：________",3, opts=["A. Spring Festival is in January or February.　B. Spring Festival is in July.　C. Spring Festival is in October."]),
   Q(5,"你想问对方会不会游泳，应该说：________",3, opts=["A. Can you swim?　B. Do you swim?　C. Are you swimming?"]),
 ]},
 {"name":"六、连词成句（注意大小写和标点）（15分）","questions":[
   Q(1,"are / What / doing / you / ?",3, blanks=1),
   Q(2,"is / My / TV / mother / watching / .",3, blanks=1),
   Q(3,"the / What's / in / weather / like / autumn / ?",3, blanks=1),
   Q(4,"reading / I / book / a / am / .",3, blanks=1),
   Q(5,"can / you / swim / ?",3, blanks=1),
 ]},
 {"name":"七、阅读理解（判断正误，正确写T，错误写F）（20分）","questions":[
   Q(1,"阅读短文，判断下列句子正（T）误（F）。",20, blanks=5,
     opts=["　　Hello! I'm Amy. It's Sunday today. My family are all at home. My father is reading a newspaper. My mother is cooking in the kitchen. My brother is playing computer games. I'm doing my homework. My sister is listening to music. We are all very happy. In the afternoon, we are going to the park. We like autumn, because the weather is cool.",
           "（1）It's Saturday today.（　）",
           "（2）Amy's father is reading a newspaper.（　）",
           "（3）Amy's mother is cooking in the kitchen.（　）",
           "（4）Amy's brother is doing his homework.（　）",
           "（5）Amy's family like autumn.（　）"]),
 ]},
]
a3 = [
 A(1,"S", "ar均读/ɑː/。"),
 A(2,"D", "ur读/ɜː/，or读/ɔː/。"),
 A(3,"D", "u在blue中读/uː/，在student中读/juː/。"),
 A(4,"D", "eigh读/eɪ/，igh读/aɪ/。"),
 A(5,"S", "oa均读/əʊ/。"),
 A(1,"A B C D E", "January一月、March三月、June六月、September九月、December十二月。"),
 A(2,"A B C D E", "sunny晴朗的、windy有风的、cloudy多云的、rainy下雨的、snowy下雪的。"),
 A(1,"C", "Christmas tree是物品，其余是节日。"),
 A(2,"C", "weather是天气总称，其余是具体天气。"),
 A(3,"C", "walk是动词，其余是频度副词。"),
 A(4,"C", "woman指成年女性，其余是家庭成员称谓。"),
 A(5,"C", "book是名词，其余是动词-ing形式。"),
 A(1,"A", "主语you用are。"),
 A(2,"A", "Look!提示现在进行时。"),
 A(3,"A", "表示所属用名词所有格。"),
 A(4,"A", "now提示现在进行时。"),
 A(5,"A", "they的否定回答用they aren't。"),
 A(6,"A", "询问天气用what's the weather like。"),
 A(7,"A", "询问正在做什么用what。"),
 A(8,"A", "like后接动词-ing形式。"),
 A(9,"A", "情态动词can后接动词原形。"),
 A(10,"A", "圣诞节在十二月。"),
 A(1,"A", "询问正在做什么。"),
 A(2,"A", "现在进行时。"),
 A(3,"A", "询问天气。"),
 A(4,"A", "春节在一月或二月。"),
 A(5,"A", "询问能力用can。"),
 A(1,"What are you doing?", "现在进行时特殊疑问句。"),
 A(2,"My mother is watching TV.", "主语my mother是单数。"),
 A(3,"What's the weather like in autumn?", "固定句型。"),
 A(4,"I am reading a book.", "现在进行时。"),
 A(5,"Can you swim?", "情态动词can提前。"),
 A(1,"F", "今天是星期天。"),
 A(2,"T", "Amy的爸爸在看报纸。"),
 A(3,"T", "Amy的妈妈在厨房做饭。"),
 A(4,"F", "Amy的弟弟在玩电脑游戏。"),
 A(5,"T", "Amy一家喜欢秋天。"),
]
out.append(save(m, p, a3, "综合检测C卷")); print("英语C卷完成")

# ================= D卷 =================
m = base("五年级英语", "期末复习质量检测", "（人教版PEP　三年级起点　2025—2026学年　第二学期）")
p = [
 {"name":"一、判断下列单词划线部分读音是否相同（相同写S，不同写D）（10分）","questions":[
   Q(1,"（　）horse　short",2), Q(2,"（　）now　snow",2), Q(3,"（　）food　noodle",2),
   Q(4,"（　）boy　toy",2), Q(5,"（　）cat　cage",2),
 ]},
 {"name":"二、看图选词，把序号填在括号里（10分）","questions":[
   Q(1,"职业：policeman（　）　driver（　）　farmer（　）　nurse（　）　writer（　）",5,
     opts=["A. 警察　B. 司机　C. 农民　D. 护士　E. 作家"], blanks=5),
   Q(2,"现在分词：sleeping（　）　reading（　）　writing（　）　running（　）　swimming（　）",5,
     opts=["A. 睡觉　B. 阅读　C. 书写　D. 跑　E. 游泳"], blanks=5),
 ]},
 {"name":"三、选出不同类的一项（10分）","questions":[
   Q(1,"（　）",2, opts=["A. reading　B. singing　C. sing"]),
   Q(2,"（　）",2, opts=["A. he　B. she　C. his"]),
   Q(3,"（　）",2, opts=["A. bear　B. elephant　C. animal"]),
   Q(4,"（　）",2, opts=["A. spring　B. season　C. winter"]),
   Q(5,"（　）",2, opts=["A. first　B. second　C. one"]),
 ]},
 {"name":"四、单项选择（20分）","questions":[
   Q(1,"—— What's your father doing?　—— He ________ TV.",2, opts=["A. is watching　B. watch　C. watches"]),
   Q(2,"—— ________ are the children doing?　—— They're playing.",2, opts=["A. What　B. Where　C. When"]),
   Q(3,"Look! The rabbit ________ a carrot.",2, opts=["A. is eating　B. eat　C. eats"]),
   Q(4,"—— Is she dancing?　—— Yes, ________.",2, opts=["A. she is　B. she isn't　C. it is"]),
   Q(5,"It's 7:00. Time to ________ up.",2, opts=["A. get　B. gets　C. getting"]),
   Q(6,"What ________ your mother doing?",2, opts=["A. is　B. are　C. do"]),
   Q(7,"—— Whose bike is this?　—— It's ________.",2, opts=["A. Peter's　B. Peter　C. Peters"]),
   Q(8,"The elephant ________ a long nose.",2, opts=["A. has　B. have　C. is"]),
   Q(9,"I want ________ a picture.",2, opts=["A. to draw　B. draw　C. draws"]),
   Q(10,"—— Are you sleeping?　—— No, I'm ________.",2, opts=["A. not　B. no　C. don't"]),
 ]},
 {"name":"五、情景选择（15分）","questions":[
   Q(1,"你想问对方「你的爸爸正在做什么」，应该说：________",3, opts=["A. What's your father doing?　B. Where is your father?　C. Who is your father?"]),
   Q(2,"你想表达「兔子正在吃胡萝卜」，应该说：________",3, opts=["A. The rabbit is eating a carrot.　B. The rabbit eats a carrot.　C. The rabbit like carrots."]),
   Q(3,"你想问对方「她正在跳舞吗」，应该说：________",3, opts=["A. Is she dancing?　B. Does she dance?　C. Can she dance?"]),
   Q(4,"你想表达「大象有一个长鼻子」，应该说：________",3, opts=["A. The elephant has a long nose.　B. The elephant have a long nose.　C. The elephant is a long nose."]),
   Q(5,"你想说「我想要画一幅画」，应该说：________",3, opts=["A. I want to draw a picture.　B. I want draw a picture.　C. I want drawing a picture."]),
 ]},
 {"name":"六、连词成句（注意大小写和标点）（15分）","questions":[
   Q(1,"father / What / your / doing / is / ?",3, blanks=1),
   Q(2,"is / She / dancing / .",3, blanks=1),
   Q(3,"rabbit / The / eating / is / carrot / a / .",3, blanks=1),
   Q(4,"bike / Whose / this / is / ?",3, blanks=1),
   Q(5,"to / I / draw / want / picture / a / .",3, blanks=1),
 ]},
 {"name":"七、阅读理解（判断正误，正确写T，错误写F）（20分）","questions":[
   Q(1,"阅读短文，判断下列句子正（T）误（F）。",20, blanks=5,
     opts=["　　Hello! Welcome to the zoo. Look! There are many animals here. The panda is eating bamboo. The elephant is drinking water with its long nose. The monkeys are climbing trees. Some birds are singing in the trees. A big tiger is sleeping under a tree. How lovely they are!",
           "（1）The panda is eating bamboo.（　）",
           "（2）The elephant is drinking water with its long nose.（　）",
           "（3）The monkeys are sleeping.（　）",
           "（4）Some birds are singing in the trees.（　）",
           "（5）A big tiger is running.（　）"]),
 ]},
]
a4 = [
 A(1,"S", "or均读/ɔː/。"),
 A(2,"D", "ow在now中读/aʊ/，在snow中读/əʊ/。"),
 A(3,"S", "oo均读/uː/。"),
 A(4,"S", "oy均读/ɔɪ/。"),
 A(5,"D", "a在cat中读/æ/，在cage中读/eɪ/。"),
 A(1,"A B C D E", "policeman警察、driver司机、farmer农民、nurse护士、writer作家。"),
 A(2,"A B C D E", "sleeping睡觉、reading阅读、writing书写、running跑、swimming游泳。"),
 A(1,"C", "sing是动词原形，其余是动词-ing形式。"),
 A(2,"C", "his是物主代词，其余是人称代词主格。"),
 A(3,"C", "animal是动物总称，其余是具体动物。"),
 A(4,"B", "season是季节总称，其余是具体季节。"),
 A(5,"C", "one是基数词，其余是序数词。"),
 A(1,"A", "主语he是单数，用is。"),
 A(2,"A", "询问正在做什么用what。"),
 A(3,"A", "Look!提示现在进行时。"),
 A(4,"A", "she的肯定回答用she is。"),
 A(5,"A", "It's time to后接动词原形。"),
 A(6,"A", "主语mother是单数，用is。"),
 A(7,"A", "表示所属用名词所有格。"),
 A(8,"A", "主语the elephant是单数，用has。"),
 A(9,"A", "want to do sth想要做某事。"),
 A(10,"A", "现在进行时的否定回答。"),
 A(1,"A", "询问正在做什么。"),
 A(2,"A", "现在进行时。"),
 A(3,"A", "现在进行时一般疑问句。"),
 A(4,"A", "第三人称单数用has。"),
 A(5,"A", "want to do sth。"),
 A(1,"What is your father doing?", "现在进行时特殊疑问句。"),
 A(2,"She is dancing.", "现在进行时。"),
 A(3,"The rabbit is eating a carrot.", "注意语序。"),
 A(4,"Whose bike is this?", "询问所属。"),
 A(5,"I want to draw a picture.", "want to do sth。"),
 A(1,"T", "熊猫在吃竹子。"),
 A(2,"T", "大象用长鼻子喝水。"),
 A(3,"F", "猴子在爬树。"),
 A(4,"T", "一些鸟在树上唱歌。"),
 A(5,"F", "一只大老虎在睡觉。"),
]
out.append(save(m, p, a4, "复习质量检测D卷")); print("英语D卷完成")

# ================= E卷 =================
m = base("五年级英语", "期末学业质量监测", "（人教版PEP　三年级起点　2025—2026学年　全学年）")
p = [
 {"name":"一、判断下列单词划线部分读音是否相同（相同写S，不同写D）（10分）","questions":[
   Q(1,"（　）work　word",2), Q(2,"（　）cold　hot",2), Q(3,"（　）chair　hair",2),
   Q(4,"（　）young　mouth",2), Q(5,"（　）green　tree",2),
 ]},
 {"name":"二、看图选词，把序号填在括号里（10分）","questions":[
   Q(1,"学校设施：playground（　）　gym（　）　art room（　）　music room（　）　computer room（　）",5,
     opts=["A. 操场　B. 体育馆　C. 美术室　D. 音乐室　E. 计算机房"], blanks=5),
   Q(2,"食物饮品：rice（　）　noodles（　）　vegetables（　）　chicken（　）　milk（　）",5,
     opts=["A. 米饭　B. 面条　C. 蔬菜　D. 鸡肉　E. 牛奶"], blanks=5),
 ]},
 {"name":"三、选出不同类的一项（10分）","questions":[
   Q(1,"（　）",2, opts=["A. breakfast　B. lunch　C. dumpling"]),
   Q(2,"（　）",2, opts=["A. rice　B. bread　C. milk"]),
   Q(3,"（　）",2, opts=["A. under　B. behind　C. table"]),
   Q(4,"（　）",2, opts=["A. I　B. teacher　C. student"]),
   Q(5,"（　）",2, opts=["A. twelve　B. twenty　C. third"]),
 ]},
 {"name":"四、单项选择（20分）","questions":[
   Q(1,"—— ________ do you have lunch?　—— At twelve o'clock.",2, opts=["A. When　B. Where　C. What"]),
   Q(2,"I'd like some ________, please.",2, opts=["A. noodles　B. noodle　C. a noodle"]),
   Q(3,"—— What would you like to drink?　—— ________.",2, opts=["A. Some juice, please.　B. Yes, please.　C. It's nice."]),
   Q(4,"—— ________ is that man?　—— He's my uncle.",2, opts=["A. Who　B. Whose　C. What"]),
   Q(5,"There are ________ months in a year.",2, opts=["A. twelve　B. twelfth　C. twelve's"]),
   Q(6,"—— How much ________ the book?　—— It's ten yuan.",2, opts=["A. is　B. are　C. be"]),
   Q(7,"Let's ________ a look.",2, opts=["A. have　B. has　C. having"]),
   Q(8,"—— What's your favourite ________?　—— Apples.",2, opts=["A. fruit　B. food　C. drink"]),
   Q(9,"My birthday is ________ the first of May.",2, opts=["A. on　B. in　C. at"]),
   Q(10,"—— ________ you like apples?　—— Yes, I do.",2, opts=["A. Do　B. Are　C. Is"]),
 ]},
 {"name":"五、情景选择（15分）","questions":[
   Q(1,"你想问对方什么时候吃午饭，应该说：________",3, opts=["A. When do you have lunch?　B. Where do you have lunch?　C. What do you have for lunch?"]),
   Q(2,"你想表达「我想要一些面条」，应该说：________",3, opts=["A. I'd like some noodles.　B. I like noodles.　C. I'd like some rice."]),
   Q(3,"你想问「那个男人是谁」，应该说：________",3, opts=["A. Who is that man?　B. Whose is that man?　C. How is that man?"]),
   Q(4,"你想问「这本书多少钱」，应该说：________",3, opts=["A. How much is the book?　B. How many books?　C. Where is the book?"]),
   Q(5,"你想表达「我的生日在五月一日」，应该说：________",3, opts=["A. My birthday is on May 1st.　B. My birthday is in May.　C. My birthday is May 1st."]),
 ]},
 {"name":"六、连词成句（注意大小写和标点）（15分）","questions":[
   Q(1,"you / When / do / lunch / have / ?",3, blanks=1),
   Q(2,"like / I'd / some / noodles / .",3, blanks=1),
   Q(3,"is / Who / man / that / ?",3, blanks=1),
   Q(4,"much / is / How / book / the / ?",3, blanks=1),
   Q(5,"birthday / is / My / May / on / 1st / .",3, blanks=1),
 ]},
 {"name":"七、阅读理解（判断正误，正确写T，错误写F）（20分）","questions":[
   Q(1,"阅读短文，判断下列句子正（T）误（F）。",20, blanks=5,
     opts=["　　Hi! I'm Mike. I'm a student. I have breakfast at seven. I have bread and milk for breakfast. I have lunch at twelve at school. I like noodles and vegetables for lunch. My favourite food is chicken. I don't like eggs. After school, I often play football with my friends. My favourite day is Friday, because I have music class. My birthday is in June.",
           "（1）Mike has breakfast at seven.（　）",
           "（2）Mike has bread and milk for breakfast.（　）",
           "（3）Mike's favourite food is fish.（　）",
           "（4）Mike's favourite day is Friday.（　）",
           "（5）Mike's birthday is in July.（　）"]),
 ]},
]
a5 = [
 A(1,"S", "or均读/ɜː/。"),
 A(2,"D", "o在cold中读/əʊ/，在hot中读/ɒ/。"),
 A(3,"S", "air均读/eə/。"),
 A(4,"D", "ou在young中读/ʌ/，在mouth中读/aʊ/。"),
 A(5,"S", "ee均读/iː/。"),
 A(1,"A B C D E", "playground操场、gym体育馆、art room美术室、music room音乐室、computer room计算机房。"),
 A(2,"A B C D E", "rice米饭、noodles面条、vegetables蔬菜、chicken鸡肉、milk牛奶。"),
 A(1,"C", "dumpling是食物，其余是三餐名称。"),
 A(2,"C", "milk是饮品，其余是主食。"),
 A(3,"C", "table是名词，其余是方位介词。"),
 A(4,"A", "I是人称代词主格，teacher和student是表示人的名词。"),
 A(5,"C", "third是序数词，其余是基数词。"),
 A(1,"A", "询问时间用when。"),
 A(2,"A", "noodles常以复数形式出现。"),
 A(3,"A", "问想喝什么答饮品。"),
 A(4,"A", "询问人物用who。"),
 A(5,"A", "一年有12个月，用基数词twelve。"),
 A(6,"A", "the book是单数，用is。"),
 A(7,"A", "Let's后接动词原形。"),
 A(8,"A", "apples是水果，问favourite fruit。"),
 A(9,"A", "具体日期前用on。"),
 A(10,"A", "实义动词like用助动词do提问。"),
 A(1,"A", "询问时间。"),
 A(2,"A", "I'd like some noodles。"),
 A(3,"A", "询问人物。"),
 A(4,"A", "询问价格用how much。"),
 A(5,"A", "具体日期前用on。"),
 A(1,"When do you have lunch?", "疑问词when开头。"),
 A(2,"I'd like some noodles.", "I'd = I would。"),
 A(3,"Who is that man?", "询问人物。"),
 A(4,"How much is the book?", "询问价格。"),
 A(5,"My birthday is on May 1st.", "具体日期用on。"),
 A(1,"T", "Mike七点吃早饭。"),
 A(2,"T", "Mike早饭吃面包喝牛奶。"),
 A(3,"F", "Mike最喜欢的食物是鸡肉。"),
 A(4,"T", "Mike最喜欢的日子是周五。"),
 A(5,"F", "Mike的生日在六月。"),
]
out.append(save(m, p, a5, "学业质量监测E卷")); print("英语E卷完成")

for f in out:
    print("已生成:", f)
