# -*- coding: utf-8 -*-
"""八年级 英语（仁爱版·科普版）期末试卷 5 套"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from paper_common import save, base, Q, A
out = []

# ================= A卷 =================
m = base("八年级英语", "第一学期期末质量检测", "（仁爱版　2025—2026学年　第一学期　满分120分　时间120分钟）", fs=120, dur=120)
p = [
 {"name":"一、单项选择（每题1分，共15分）","questions":[
   Q(1,"— What ______ you ______ this time tomorrow?\n— I'll be visiting my grandparents.",1,
     opts=["A. will; do　B. will; be doing　C. do; do　D. are; doing"], kind="将来进行时"),
   Q(2,"My brother is good ______ playing football.",1,
     opts=["A. for　B. at　C. with　D. on"], kind="介词搭配"),
   Q(3,"— ______ does it take you to get to school?\n— About twenty minutes.",1,
     opts=["A. How long　B. How often　C. How soon　D. How far"], kind="疑问词"),
   Q(4,"If it ______ tomorrow, we will stay at home.",1,
     opts=["A. will rain　B. rains　C. rained　D. is raining"], kind="主将从现"),
   Q(5,"The book is ______ interesting that I want to read it again.",1,
     opts=["A. such　B. so　C. very　D. too"], kind="so...that"),
   Q(6,"— How many students ______ in our school?\n— About two thousand.",1,
     opts=["A. there are　B. are there　C. there is　D. is there"], kind="there be 句型"),
   Q(7,"My mother often tells me ______ computer games for too long.",1,
     opts=["A. to not play　B. not to play　C. don't play　D. not play"], kind="不定式否定"),
   Q(8,"— Would you like ______ with me?\n— Yes, I'd love to.",1,
     opts=["A. go shopping　B. to go shopping　C. going shopping　D. went shopping"], kind="不定式"),
   Q(9,"He ______ his homework when I got home.",1,
     opts=["A. does　B. did　C. was doing　D. is doing"], kind="过去进行时"),
   Q(10,"The population of our city ______ about 3 million.",1,
     opts=["A. are　B. is　C. have　D. has"], kind="主谓一致"),
   Q(11,"— I have never been to Beijing.\n— ______.",1,
     opts=["A. So have I　B. Neither have I　C. So I have　D. Neither I have"], kind="倒装句"),
   Q(12,"Our teacher asked us ______ the school rules.",1,
     opts=["A. to obey　B. obey　C. obeying　D. obeyed"], kind="不定式作宾补"),
   Q(13,"— How long have you ______ this bike?\n— For two years.",1,
     opts=["A. bought　B. had　C. borrowed　D. got"], kind="现在完成时"),
   Q(14,"It's important ______ us to learn English well.",1,
     opts=["A. of　B. for　C. to　D. with"], kind="It's + adj + for sb"),
   Q(15,"— Thanks for helping me.\n— ______.",1,
     opts=["A. That's right　B. No thanks　C. You're welcome　D. Never mind"], kind="情景交际"),
 ]},
 {"name":"二、完形填空（每题1.5分，共15分）","questions":[
   Q(16,"阅读下面短文，从每题所给的选项中选出最佳答案。\nLast summer, I went to a small village to visit my grandparents. The village was quiet and beautiful. Every morning, I got up early and 16 with my grandfather in the mountains. We could see many birds and 17 there. One day, I saw an old man 18 a big box on his back. He walked slowly. I asked my grandfather who he was. He told me the old man was a teacher. He had taught in the village 19 more than forty years. I was deeply 20. Later, I went to visit him. His house was small 21 clean. There were many books in it. He said, 'I love children. I want to help them 22 a better future.' I asked him 23 he felt lonely. He said, 'No, never. The children bring me happiness.' When I left, he gave me a book and said, 'Read more, and you will 24 more.' Now I still keep that book. It always 25 me of that kind teacher.\n16.",1.5,
     opts=["A. walked　B. walk　C. am walking　D. will walk"], kind="完形填空"),
   Q(17,"17.",1.5,
     opts=["A. flowers　B. animals　C. cars　D. buildings"], kind="完形填空"),
   Q(18,"18.",1.5,
     opts=["A. carry　B. carries　C. carrying　D. carried"], kind="完形填空"),
   Q(19,"19.",1.5,
     opts=["A. in　B. for　C. at　D. on"], kind="完形填空"),
   Q(20,"20.",1.5,
     opts=["A. moved　B. moving　C. move　D. moves"], kind="完形填空"),
   Q(21,"21.",1.5,
     opts=["A. and　B. or　C. but　D. so"], kind="完形填空"),
   Q(22,"22.",1.5,
     opts=["A. have　B. has　C. having　D. had"], kind="完形填空"),
   Q(23,"23.",1.5,
     opts=["A. that　B. if　C. what　D. why"], kind="完形填空"),
   Q(24,"24.",1.5,
     opts=["A. know　B. knew　C. knowing　D. knows"], kind="完形填空"),
   Q(25,"25.",1.5,
     opts=["A. remind　B. reminds　C. reminded　D. reminding"], kind="完形填空"),
 ]},
 {"name":"三、阅读理解（每题2分，共30分）","questions":[
   Q(26,"阅读下面短文，选择正确答案。\n（A）\nDo you know how to keep healthy? Here are some tips.\nFirst, eat healthy food. You should eat more fruit and vegetables, and less meat. Don't eat too much junk food, because it's bad for your health.\nSecond, do exercise every day. You can run, swim, or play ball games. Exercise makes your body strong and helps you feel happy.\nThird, get enough sleep. Students should sleep for at least eight hours every night. If you don't sleep well, you will feel tired and can't study well.\nFinally, keep a good mood. Smiling is the best medicine. Learn to relax when you feel stressed.\n（　）1. How many tips are mentioned in the passage?\nA. Three.　B. Four.　C. Five.　D. Six.\n（　）2. What should we eat less according to the passage?\nA. Fruit.　B. Vegetables.　C. Meat.　D. Water.\n（　）3. Why is junk food bad for us?\nA. It's expensive.　B. It's bad for our health.　C. It's not delicious.　D. It's hard to buy.\n（　）4. How long should students sleep every night?\nA. At least 6 hours.　B. At least 7 hours.　C. At least 8 hours.　D. At least 10 hours.\n（　）5. What is the best medicine according to the passage?\nA. Exercise.　B. Sleep.　C. Food.　D. Smiling.",10,
     kind="阅读理解A"),
   Q(27,"（B）\nHenry is a middle school student in Beijing. He is 14 years old. He likes sports very much. His favorite sport is basketball. He plays basketball with his friends every Saturday afternoon.\nHenry also likes reading. He has read more than 200 books. His favorite book is《Journey to the West》. He says he learns a lot from it.\nHenry wants to be a PE teacher when he grows up. He wants to help more children love sports.\n（　）1. How old is Henry?\nA. 12.　B. 13.　C. 14.　D. 15.\n（　）2. What is Henry's favorite sport?\nA. Football.　B. Basketball.　C. Swimming.　D. Running.\n（　）3. When does Henry play basketball?\nA. Every day.　B. Every Friday.　C. Every Saturday afternoon.　D. Every Sunday morning.\n（　）4. How many books has Henry read?\nA. More than 100.　B. More than 200.　C. More than 300.　D. More than 500.\n（　）5. What does Henry want to be?\nA. A doctor.　B. A writer.　C. A PE teacher.　D. A basketball player.",10,
     kind="阅读理解B"),
   Q(28,"（C）任务型阅读\nMost people like travelling. Travelling is a good way to relax and learn. But do you know how to be a good traveller?\nFirst, plan your trip carefully. Decide where to go and how to get there. Make a list of things you need to take.\nSecond, learn about the local culture. Before you go, read some books or search online. Try to understand the local customs and habits. This will help you avoid trouble.\nThird, be polite. When you visit a place, remember to respect the local people and their way of life. Don't make noise in public places. Don't throw rubbish everywhere.\nFinally, protect the environment. Take your rubbish with you. Don't pick flowers or break branches.\nTravel can make our life richer. Let's be good travellers!\n1. What is travelling a good way to do? (1)\n2. What should you do before you go to a new place? (2)\n3. Why should we be polite when travelling? (2)\n4. What should you do with your rubbish? (2)\n5. What's the main idea of the passage? (3)",10,
     kind="任务型阅读"),
 ]},
 {"name":"四、词汇与句型（共30分）","questions":[
   Q(29,"根据首字母提示补全单词。（每题1分，共10分）\n1. Beijing is the c______ of China.\n2. We should protect the e______.\n3. My father is a d______. He works in a hospital.\n4. It's i______ for us to eat breakfast every day.\n5. The Great Wall is one of the most famous places of i______ in China.\n6. Please be q______. The baby is sleeping.\n7. My sister is i______ in music.\n8. We have four s______ in a year.\n9. He is very h______, so he always helps others.\n10. It takes me half an hour to get to school by u______ (地铁).",10,
     kind="词汇"),
   Q(30,"用括号内所给词的适当形式填空。（每题1分，共10分）\n1. Look! The children ______ (play) football on the playground.\n2. My mother ______ (cook) when I got home yesterday.\n3. If it ______ (not rain) tomorrow, we will go hiking.\n4. He has ______ (be) to Beijing twice.\n5. I think English is ______ (use) than French.\n6. The students are ______ (interest) in the story.\n7. My father is busy ______ (work) every day.\n8. It's important for us ______ (learn) a foreign language.\n9. There ______ (be) a lot of water in the bottle.\n10. Listen! Someone ______ (sing) in the next room.",10,
     kind="词形变化"),
   Q(31,"按要求完成句子。（每题2分，共10分）\n1. He goes to school by bike.（对画线部分提问）\n______ ______ he go to school?\n2. She is good at English.（改为同义句）\nShe ______ ______ ______ English.\n3. The boy is so young that he can't go to school.（改为同义句）\nThe boy is ______ young ______ go to school.\n4. I have lived here for ten years.（对画线部分提问）\n______ ______ have you lived here?\n5. They will visit the museum tomorrow.（改为一般疑问句）\n______ they ______ the museum tomorrow?",10,
     kind="句型转换"),
 ]},
 {"name":"五、书面表达（共30分）","questions":[
   Q(32,"（10分）请以「My Best Friend」为题，写一篇短文介绍你的好朋友。\n要求：①词数80左右；②内容包括外貌、性格、兴趣爱好、你们的友谊；③不得出现真实姓名。",10,
     kind="书面表达"),
   Q(33,"（20分）请根据以下提示，以「How to Keep Healthy」为题写一篇短文，谈谈保持健康的方法。\n提示：①健康饮食（多吃蔬菜水果，少吃垃圾食品）；②坚持锻炼（如跑步、打球）；③充足睡眠（每天至少8小时）；④保持好心情。\n要求：①词数100左右；②语句通顺，意思连贯；③不得出现真实姓名。",20,
     kind="书面表达"),
 ]},
]
answers = [
 A(1,"B","this time tomorrow 表示将来某时间点，用将来进行时 will be doing。"),
 A(2,"B","be good at 意为「擅长」，固定搭配。"),
 A(3,"A","回答是时间段「About twenty minutes」，故用 How long 提问。"),
 A(4,"B","if 引导条件状语从句，主将从现，从句用一般现在时。"),
 A(5,"B","so + adj. + that 引导结果状语从句。such 后接名词短语。"),
 A(6,"B","「某地有某物」用 there be 句型，复数用 are there。"),
 A(7,"B","tell sb. not to do sth. 告诉某人不要做某事。"),
 A(8,"B","would like to do sth. 想要做某事。"),
 A(9,"C","when I got home 表示过去某时间点，用过去进行时。"),
 A(10,"B","The population of ... 作主语时谓语用单数 is。"),
 A(11,"B","「我也没去过」用 Neither have I，表示否定呼应。"),
 A(12,"A","ask sb. to do sth. 要求某人做某事。"),
 A(13,"B","How long 提问时，短暂性动词 bought 需改为延续性动词 had。"),
 A(14,"B","It's + adj. + for sb. + to do sth. 是固定句型，描述事情的性质用 for。"),
 A(15,"C","回应感谢用 You're welcome（不用谢）。"),
 A(16,"A","Last summer 表示过去，叙述用一般过去时 walked。"),
 A(17,"B","在山上能看到许多鸟和其他「动物」，且指代前面 birds 的同类，用 animals。"),
 A(18,"C","see sb. doing sth. 看见某人正在做某事。"),
 A(19,"B","for + 时间段，表示持续四十多年。"),
 A(20,"A","系动词 was + 形容词 moved（感动的），构成被动意义的形容词。"),
 A(21,"C","small 与 clean 之间是转折关系，用 but。"),
 A(22,"A","help sb. (to) do sth. 帮助某人做某事。"),
 A(23,"B","宾语从句表示「是否」，用 if。"),
 A(24,"A","will + 动词原形，用 know。"),
 A(25,"B","主语 It 为第三人称单数，一般现在时用 reminds。"),
 A(26,"1. B（文中提到四条建议：健康饮食、锻炼、睡眠、好心情）　2. C（should eat less meat）　3. B（it's bad for our health）　4. C（at least eight hours）　5. D（Smiling is the best medicine）","评分：每题2分。"),
 A(27,"1. C（He is 14 years old）　2. B（His favorite sport is basketball）　3. C（every Saturday afternoon）　4. B（more than 200 books）　5. C（He wants to be a PE teacher）","评分：每题2分。"),
 A(28,"1. It is a good way to relax and learn.（1分）\n2. We should learn about the local culture (read books or search online).（2分）\n3. Because it helps us avoid trouble / respect the local people.（2分）\n4. We should take our rubbish with us.（2分）\n5. The passage tells us how to be a good traveller.（3分）","评分：见上，意思相近即可。"),
 A(29,"1. capital　2. environment　3. doctor　4. important　5. interest　6. quiet　7. interested　8. seasons　9. helpful　10. underground","评分：每题1分。"),
 A(30,"1. are playing　2. was cooking　3. doesn't rain　4. been　5. more useful　6. interested　7. working　8. to learn　9. is　10. is singing","评分：每题1分。"),
 A(31,"1. How does　2. does well in　3. too; to　4. How long　5. Will; visit","评分：每题2分。"),
 A(32,"范文：\nMy Best Friend\nI have a good friend. His name is Li Ming. He is 14 years old.\nLi Ming is tall and strong. He has short black hair and big eyes. He is friendly and helpful. He often helps others. Everyone likes him.\nHe likes sports very much. He is good at basketball and he plays it every weekend. He also likes reading books in his free time.\nWe have been friends for many years. We study together and play together. I think he is really a good friend. I hope our friendship will last forever.","评分标准：内容完整4分，语言准确4分，书写规范2分。词数明显不足或过多酌减。"),
 A(33,"范文：\nHow to Keep Healthy\nHealth is very important to us. How can we keep healthy? Here are some suggestions.\nFirst, we should eat healthy food. We'd better eat more fruit and vegetables, and eat less junk food. Junk food is bad for our health.\nSecond, we should do exercise every day. We can run, swim or play ball games. Exercise makes us strong and happy.\nThird, we need to get enough sleep. We should sleep for at least eight hours every night.\nFinally, we should keep a good mood. Smiling is the best medicine. When we feel stressed, we should learn to relax.\nIf we follow these suggestions, I believe we will be healthier and happier.","评分标准：\n一类（17—20分）：要点齐全，语言流畅，语法正确，衔接自然。\n二类（13—16分）：要点较全，语言基本通顺，有少量语法错误。\n三类（9—12分）：要点基本齐全，语言有较多错误，但能达意。\n四类（8分以下）：要点不全，语言错误多，影响理解。"),
]
out.append(save(m, p, answers, "期末质量检测A卷"))

# ================= B卷 =================
m = base("八年级英语", "第二学期期末学业水平测试", "（仁爱版　2025—2026学年　第二学期　满分120分　时间120分钟）", fs=120, dur=120)
p = [
 {"name":"一、单项选择（每题1分，共15分）","questions":[
   Q(1,"The classroom ______ every day.",1,
     opts=["A. cleans　B. is cleaned　C. cleaned　D. is cleaning"], kind="被动语态"),
   Q(2,"— Where is Tom?\n— He ______ to the library.",1,
     opts=["A. has been　B. has gone　C. went　D. goes"], kind="have been to / gone to"),
   Q(3,"This is the boy ______ won the first prize.",1,
     opts=["A. which　B. who　C. whom　D. whose"], kind="定语从句"),
   Q(4,"— ______ I take a photo here?\n— Sorry, you can't.",1,
     opts=["A. Must　B. Should　C. May　D. Need"], kind="情态动词"),
   Q(5,"He speaks English ______ than his brother.",1,
     opts=["A. good　B. well　C. better　D. best"], kind="比较级"),
   Q(6,"The more you read, ______ you will learn.",1,
     opts=["A. the more　B. more　C. much　D. the most"], kind="the比较级the比较级"),
   Q(7,"I don't know ______ he will come or not.",1,
     opts=["A. if　B. whether　C. that　D. what"], kind="whether or not"),
   Q(8,"The trees ______ by the students last year.",1,
     opts=["A. plant　B. planted　C. were planted　D. are planted"], kind="被动语态"),
   Q(9,"— How long ______ you ______ in this city?\n— Since 2015.",1,
     opts=["A. did; live　B. have; lived　C. do; live　D. are; living"], kind="现在完成时"),
   Q(10,"It's very cold outside. You'd better ______ more clothes.",1,
     opts=["A. put on　B. to put on　C. putting on　D. puts on"], kind="had better"),
   Q(11,"He is ______ young ______ he can't carry the box.",1,
     opts=["A. so; that　B. too; to　C. such; that　D. enough; to"], kind="too...to"),
   Q(12,"I'm looking forward to ______ from you soon.",1,
     opts=["A. hear　B. hearing　C. heard　D. hears"], kind="look forward to doing"),
   Q(13,"— Would you mind ______ the window?\n— Of course not.",1,
     opts=["A. open　B. to open　C. opening　D. opened"], kind="mind doing"),
   Q(14,"My father ______ to Shanghai three times this year.",1,
     opts=["A. went　B. has been　C. has gone　D. goes"], kind="现在完成时"),
   Q(15,"— I'm sorry I'm late.\n— ______.",1,
     opts=["A. That's all right　B. You're welcome　C. Not at all　D. Thank you"], kind="情景交际"),
 ]},
 {"name":"二、完形填空（每题1.5分，共15分）","questions":[
   Q(16,"阅读下面短文，从每题所给的选项中选出最佳答案。\nMany students have problems with their study. Here is some 16 that may help you.\nFirst, make a plan. A good plan can help you 17 your time well. Decide what to do first and what to do later.\nSecond, find a good place to study. It should be 18 and quiet. Don't study in front of the TV or with your phone.\nThird, take notes in class. Write down the 19 points that your teacher says. Good notes are very useful when you review.\nFourth, ask for help when you need it. Don't be afraid to ask your teachers or classmates. They are 20 to help you.\nFinally, take a break. Don't study all the time. You should rest for a few minutes after studying for an hour.\nIf you 21 these ways, you may improve your study. Remember: practice makes 22.\n16.",1.5,
     opts=["A. advice　B. advices　C. advice's　D. advise"], kind="完形填空"),
   Q(17,"17.",1.5,
     opts=["A. use　B. uses　C. using　D. used"], kind="完形填空"),
   Q(18,"18.",1.5,
     opts=["A. noisy　B. clean　C. dark　D. crowded"], kind="完形填空"),
   Q(19,"19.",1.5,
     opts=["A. important　B. boring　C. difficult　D. easy"], kind="完形填空"),
   Q(20,"20.",1.5,
     opts=["A. happy　B. sad　C. angry　D. tired"], kind="完形填空"),
   Q(21,"21.",1.5,
     opts=["A. follow　B. follows　C. following　D. followed"], kind="完形填空"),
   Q(22,"22.",1.5,
     opts=["A. perfect　B. perfectly　C. imperfection　D. perfects"], kind="完形填空"),
   Q(23,"According to the passage, what should you not do while studying?（　）",1.5,
     opts=["A. Make a plan　B. Take notes　C. Watch TV　D. Take a break"], kind="完形填空"),
   Q(24,"What does the writer think of asking for help?（　）",1.5,
     opts=["A. It's useless　B. It's important　C. It's shameful　D. It's difficult"], kind="完形填空"),
   Q(25,"What's the best title for the passage?（　）",1.5,
     opts=["A. How to Make a Plan　B. How to Improve Your Study",
           "C. How to Take Notes　D. How to Ask for Help"], kind="完形填空"),
 ]},
 {"name":"三、阅读理解（每题2分，共30分）","questions":[
   Q(26,"（A）\nThe bicycle is a popular means of transport in China. It is easy to ride and doesn't pollute the air.\nRiding a bike has many advantages. First, it is good for your health. Riding a bike can make your body strong. Second, it doesn't cost much. You don't need to buy petrol. Third, it doesn't cause air pollution. Riding a bike is good for the environment.\nHowever, riding a bike also has some problems. It is slow. If you are in a hurry, you may be late. And in bad weather, riding a bike is not comfortable. Also, riding a bike on busy roads can be dangerous.\nSo we should ride carefully. We should obey the traffic rules. We should wear a helmet when we ride.\n（　）1. What is the passage mainly about?\nA. The history of bicycles.　B. The advantages and problems of riding a bike.\nC. How to buy a bike.　D. The best way to travel.\n（　）2. What is NOT an advantage of riding a bike?\nA. It is good for health.　B. It doesn't cost much.\nC. It doesn't pollute the air.　D. It is very fast.\n（　）3. Why can riding a bike be dangerous?\nA. Because bikes are expensive.　B. Because busy roads are dangerous.\nC. Because people don't like bikes.　D. Because bikes are heavy.\n（　）4. What should we wear when we ride a bike?\nA. A hat.　B. A helmet.　C. Gloves.　D. Sunglasses.\n（　）5. What does the writer advise us to do?\nA. Ride as fast as possible.　B. Ride on busy roads.\nC. Obey the traffic rules.　D. Never ride a bike.",10,
     kind="阅读理解A"),
   Q(27,"（B）\nLiu Wei is a famous Chinese pianist. He lost his arms when he was ten years old.\nWhen Liu Wei was young, he was very interested in music. But after the accident, he couldn't play with his hands. Most people thought he would give up. But he didn't.\nHe decided to learn to play the piano with his feet. It was very difficult at first. His toes hurt a lot. But he kept practicing every day. Two years later, he could play beautiful music with his feet.\nIn 2010, he took part in a talent show and became very famous. He said, 'I can lose my arms, but I can't lose my dream.'\nNow he gives concerts around the world. His story encourages millions of people.\n（　）1. When did Liu Wei lose his arms?\nA. At 8.　B. At 10.　C. At 12.　D. At 15.\n（　）2. What did Liu Wei learn to do after the accident?\nA. Play the piano with his feet.　B. Play basketball.\nC. Write with his mouth.　D. Swim.\n（　）3. How long did it take him to play beautiful music with his feet?\nA. One year.　B. Two years.　C. Three years.　D. Five years.\n（　）4. What does the sentence 'I can lose my arms, but I can't lose my dream' mean?\nA. He wants to have more dreams.　B. He will never give up his dream.\nC. He has lost his dream.　D. He doesn't need his dream.\n（　）5. What can we learn from Liu Wei?\nA. Keep a good mood.　B. Never give up.　C. Work hard at school.　D. Value our health.",10,
     kind="阅读理解B"),
   Q(28,"（C）任务型阅读\nVolunteering is a great way to help others. Many people spend their free time volunteering.\nYou can volunteer in many ways. You can help at a hospital, a school or an animal centre. You can also help clean up parks or teach children in poor areas.\nVolunteering is good for you, too. It can help you learn new skills. It can help you make new friends. It can also make you feel happy, because helping others makes people feel good.\nSome students worry that volunteering will take too much time. In fact, you can volunteer just a few hours a week. Even one hour can make a difference.\nSo why not start volunteering today?\n1. What is a great way to help others? (1)\n2. Where can you volunteer? (list two places) (2)\n3. Why is volunteering good for you? (list two reasons) (2)\n4. Why do some students worry about volunteering? (2)\n5. What does the writer suggest at the end? (3)",10,
     kind="任务型阅读"),
 ]},
 {"name":"四、词汇与句型（共30分）","questions":[
   Q(29,"根据首字母提示补全单词。（每题1分，共10分）\n1. There are many a______ in the zoo.\n2. We should r______ the old people.\n3. The Internet is very u______ in our daily life.\n4. Please t______ off your shoes before you enter.\n5. Remember to t______ care of yourself.\n6. I'm b______ preparing for the exam.\n7. Our teacher is very p______ with us.\n8. Chinese is one of the oldest l______ in the world.\n9. He made a big d______ to study abroad.\n10. Don't be n______. You can do it well.",10,
     kind="词汇"),
   Q(30,"用括号内所给词的适当形式填空。（每题1分，共10分）\n1. The students ______ (clean) the classroom now.\n2. These books ______ (write) by a famous writer.\n3. He is the boy ______ (who) helped me yesterday.\n4. I'm looking forward to ______ (see) you again.\n5. My parents want me ______ (study) harder.\n6. This is the ______ (good) film I have ever seen.\n7. If you ______ (not hurry), you will be late.\n8. He has already ______ (finish) his homework.\n9. The bridge ______ (build) in 1998.\n10. Would you mind ______ (close) the door?",10,
     kind="词形变化"),
   Q(31,"按要求完成句子。（每题2分，共10分）\n1. People speak English all over the world.（改为被动语态）\nEnglish ______ ______ all over the world.\n2. He has lived here since 2010.（对画线部分提问）\n______ ______ has he lived here?\n3. She is such a kind girl that everyone likes her.（改为同义句）\nShe is ______ kind ______ everyone likes her.\n4. I don't know. Will he come?（合并为宾语从句）\nI don't know ______ he ______ come.\n5. The boy is too young to go to school.（改为同义句）\nThe boy is ______ young ______ he can't go to school.",10,
     kind="句型转换"),
 ]},
 {"name":"五、书面表达（共30分）","questions":[
   Q(32,"（10分）请根据提示写一篇短文，介绍你的家乡。\n提示：位置、人口、气候、特产、景点、人们的活动等。要求：词数80左右，语句通顺。",10,
     kind="书面表达"),
   Q(33,"（20分）请以「My Dream」为题，写一篇短文。\n提示：①你的梦想是什么；②为什么有这个梦想；③你打算怎样实现它。\n要求：词数100左右；语句通顺，意思连贯；不得出现真实姓名。",20,
     kind="书面表达"),
 ]},
]
answers = [
 A(1,"B","classroom 是动作承受者，用被动语态 is cleaned，every day 表示一般现在时。"),
 A(2,"B","has gone to 表示「去了某地（还没回来）」，符合语境。"),
 A(3,"B","先行词 the boy 指人，关系代词在从句中作主语，用 who。"),
 A(4,"C","May I...? 用于请求许可。"),
 A(5,"C","than 前用比较级 better。"),
 A(6,"A","「the + 比较级, the + 比较级」表示「越……越……」。"),
 A(7,"B","whether...or not 是固定搭配。"),
 A(8,"C","trees 是动作承受者，last year 表示过去，用一般过去时被动语态。"),
 A(9,"B","How long 提问延续动作，用现在完成时；Since 2015 是回答标志。"),
 A(10,"A","had better 后接动词原形。"),
 A(11,"A","so + adj. + that 引导结果状语从句，符合句意。"),
 A(12,"B","look forward to 中 to 是介词，后接动名词 hearing。"),
 A(13,"C","mind doing sth. 介意做某事。"),
 A(14,"B","has been to 表示「去过某地（已回来）」，three times 是标志。"),
 A(15,"A","回应道歉用 That's all right（没关系）。"),
 A(16,"A","advice 是不可数名词，没有复数形式，也不能加 's。"),
 A(17,"A","help sb. do sth. 帮助某人做某事。"),
 A(18,"B","学习的地方应该「干净」且安静。"),
 A(19,"A","笔记应记「重要的」要点。"),
 A(20,"A","老师和同学「乐意」帮助你。"),
 A(21,"A","if 引导条件状语从句，主将从现，从句用一般现在时 follow。"),
 A(22,"A","practice makes perfect 是谚语，意为「熟能生巧」。"),
 A(23,"C","文中说 Don't study in front of the TV。"),
 A(24,"B","文中说 They are happy to help you，说明求助是重要且可行的。"),
 A(25,"B","全文围绕「如何提高学习成绩」展开。"),
 A(26,"1. B（文章讲骑自行车的优点和问题）　2. D（文中说自行车慢，不是优点）　3. B（在繁忙道路上骑车危险）　4. B（wear a helmet）　5. C（obey the traffic rules）","评分：每题2分。"),
 A(27,"1. B（when he was ten years old）　2. A（learn to play the piano with his feet）　3. B（Two years later）　4. B（表示永不放弃梦想）　5. B（从刘伟身上学到永不放弃）","评分：每题2分。"),
 A(28,"1. Volunteering.（1分）\n2. At a hospital and at a school. (Also: an animal centre, parks, poor areas.)（2分）\n3. It can help you learn new skills and make new friends.（2分）\n4. Because they worry that volunteering will take too much time.（2分）\n5. The writer suggests that we (should) start volunteering today.（3分）","评分：见上，意思相近即可。"),
 A(29,"1. animals　2. respect　3. useful　4. take　5. take　6. busy　7. patient　8. languages　9. decision　10. nervous","评分：每题1分。"),
 A(30,"1. are cleaning　2. were written　3. who　4. seeing　5. to study　6. best　7. don't hurry　8. finished　9. was built　10. closing","评分：每题1分。"),
 A(31,"1. is spoken　2. How long　3. so; that　4. whether/if; will　5. so; that","评分：每题2分。"),
 A(32,"范文：\nMy Hometown\nMy hometown is a small city in the south of China. It has a population of about 600,000.\nThe weather here is very nice. It is warm in spring and autumn, hot in summer and not very cold in winter. My hometown is famous for its oranges. Every autumn, many people come here to buy them.\nThere are also some beautiful places, such as the old park and the river. In the evening, people like to walk along the river or dance in the square.\nI love my hometown very much. Welcome to my hometown!","评分标准：要点完整4分，语言准确4分，书写规范2分。"),
 A(33,"范文：\nMy Dream\nEveryone has a dream. My dream is to be a doctor.\nWhy do I want to be a doctor? When I was ten, my grandmother was seriously ill. The doctors saved her life. From then on, I made up my mind to be a doctor. I want to help people who are ill and make them healthy again.\nTo make my dream come true, I will study hard, especially science subjects. I will also read more books about medicine. I believe that if I work hard, my dream will come true one day.","评分标准：\n一类（17—20分）：要点齐全，语言流畅，语法正确，衔接自然。\n二类（13—16分）：要点较全，语言基本通顺，有少量语法错误。\n三类（9—12分）：要点基本齐全，语言有较多错误，但能达意。\n四类（8分以下）：要点不全，语言错误多，影响理解。"),
]
out.append(save(m, p, answers, "学业水平测试B卷"))

# ================= C卷 =================
m = base("八年级英语", "期末综合能力提升测试", "（仁爱版　2025—2026学年　第一学期　满分120分　时间120分钟）", fs=120, dur=120)
p = [
 {"name":"一、单项选择（每题1分，共15分）","questions":[
   Q(1,"— How many people ______ the film last night?\n— About three hundred.",1,
     opts=["A. watched　B. watch　C. were watching　D. have watched"], kind="一般过去时"),
   Q(2,"The teacher told us that the earth ______ around the sun.",1,
     opts=["A. moved　B. moves　C. will move　D. is moving"], kind="宾语从句时态"),
   Q(3,"He is one of ______ students in our class.",1,
     opts=["A. the tallest　B. tallest　C. taller　D. the taller"], kind="最高级"),
   Q(4,"It's raining hard. ______ take an umbrella with you.",1,
     opts=["A. You'd better　B. You'd better not　C. You had better to　D. Better you"], kind="had better"),
   Q(5,"— Have you finished your homework ______?\n— Yes, I have ______ finished it.",1,
     opts=["A. yet; already　B. already; yet　C. yet; yet　D. already; already"], kind="already/yet"),
   Q(6,"Neither Tom nor I ______ good at swimming.",1,
     opts=["A. am　B. is　C. are　D. be"], kind="主谓一致"),
   Q(7,"The girl ______ long hair is my cousin.",1,
     opts=["A. has　B. with　C. in　D. of"], kind="介词短语作定语"),
   Q(8,"— Why not ______ to the park this weekend?\n— Good idea!",1,
     opts=["A. go　B. to go　C. going　D. went"], kind="Why not do"),
   Q(9,"He ______ in the village since he was born.",1,
     opts=["A. lives　B. lived　C. has lived　D. is living"], kind="现在完成时"),
   Q(10,"The old man is ______ weak ______ he can't walk any further.",1,
     opts=["A. so; that　B. such; that　C. too; to　D. very; that"], kind="so...that"),
   Q(11,"— Do you know ______ ?\n— Sorry, I don't know, either.",1,
     opts=["A. where does he live　B. where he lives",
           "C. where did he live　D. where he live"], kind="宾语从句语序"),
   Q(12,"The homework ______ by the students yesterday.",1,
     opts=["A. finished　B. was finished　C. is finished　D. finishes"], kind="被动语态"),
   Q(13,"We should do something to ______ the environment.",1,
     opts=["A. protect　B. protects　C. protecting　D. protected"], kind="动词用法"),
   Q(14,"He ran ______ fast that nobody could catch up with him.",1,
     opts=["A. such　B. so　C. very　D. too"], kind="so...that"),
   Q(15,"— I'm worried about the exam.\n— ______. You have worked hard.",1,
     opts=["A. Take it easy　B. Never mind　C. That's all right　D. Not at all"], kind="情景交际"),
 ]},
 {"name":"二、完形填空（每题1.5分，共15分）","questions":[
   Q(16,"阅读下面短文，从每题所给的选项中选出最佳答案。\nWhen I was young, my family was very poor. We lived in a small house in a village. My father was a farmer and my mother 16 care of us at home.\nAlthough life was hard, my parents never gave up hope. They often told me, 'Study hard, and your 17 will be better.'\nI remembered their words. I studied very hard. Every night I read books 18 the oil lamp. My parents 19 me a lot. They worked day and night to 20 me a chance to study.\nLater, I passed the exam and went to a good school in the city. When I left, my mother cried. She said, 'Be 21 to yourself and study well.'\nNow I am a teacher. I often tell my students my story. I tell them that 22 is the key to a better future. I also tell them to be 23 for what their parents have done for them.\nLooking back, I am 24 to my parents. Without their support, I could never have 25 my dream.\n16.",1.5,
     opts=["A. took　B. takes　C. is taking　D. will take"], kind="完形填空"),
   Q(17,"17.",1.5,
     opts=["A. past　B. future　C. school　D. house"], kind="完形填空"),
   Q(18,"18.",1.5,
     opts=["A. by　B. in　C. on　D. at"], kind="完形填空"),
   Q(19,"19.",1.5,
     opts=["A. helped　B. help　C. helps　D. helping"], kind="完形填空"),
   Q(20,"20.",1.5,
     opts=["A. give　B. gave　C. giving　D. gives"], kind="完形填空"),
   Q(21,"21.",1.5,
     opts=["A. good　B. bad　C. lazy　D. careless"], kind="完形填空"),
   Q(22,"22.",1.5,
     opts=["A. money　B. knowledge　C. luck　D. time"], kind="完形填空"),
   Q(23,"23.",1.5,
     opts=["A. sorry　B. thankful　C. angry　D. careful"], kind="完形填空"),
   Q(24,"24.",1.5,
     opts=["A. grateful　B. afraid　C. worried　D. tired"], kind="完形填空"),
   Q(25,"25.",1.5,
     opts=["A. remembered　B. forgotten　C. realized　D. lost"], kind="完形填空"),
 ]},
 {"name":"三、阅读理解（每题2分，共30分）","questions":[
   Q(26,"（A）\nDogs are the most popular pets in the world. Many people keep dogs as their friends.\nWhy are dogs so popular? First, dogs are very friendly. They like to stay with people. They are always happy to see their owners. Second, dogs are clever. They can understand simple instructions. Some dogs can even help blind people. Third, dogs can protect us. If a stranger comes into our home, a dog will bark to warn us.\nHowever, keeping a dog also means a lot of work. We need to feed it, walk it and take care of it. We should also take it to the vet when it is ill.\n（　）1. What is the most popular pet according to the passage?\nA. Cats.　B. Dogs.　C. Birds.　D. Fish.\n（　）2. Which is NOT a reason why dogs are popular?\nA. They are friendly.　B. They are clever.\nC. They can protect us.　D. They are easy to take care of.\n（　）3. What can some dogs do for blind people?\nA. Feed them.　B. Help them.　C. Walk with them.　D. Play with them.\n（　）4. What does a dog do when a stranger comes in?\nA. It runs away.　B. It barks to warn us.　C. It sleeps.　D. It hides.\n（　）5. What does the writer think of keeping a dog?\nA. It's easy.　B. It's free.　C. It needs a lot of work.　D. It's useless.",10,
     kind="阅读理解A"),
   Q(27,"（B）\nHave you ever heard of Zhang Guimei? She is a teacher in Yunnan Province.\nIn 2008, she set up a free high school for girls in a poor area. At that time, many girls there couldn't go to school because their families were poor. Zhang wanted to help them.\nShe worked very hard. Although she was ill, she never stopped working. She got up at 5 a.m. and went to bed after midnight every day. She visited students' homes to ask their parents to send their children to school.\nThanks to her, more than 1,800 girls have gone to college. Her school has changed their lives.\nShe said, 'I want to help these girls get a better future.'\nIn 2020, she was given the title of 'Role Model of the Times'.\n（　）1. Where does Zhang Guimei work?\nA. In Sichuan.　B. In Yunnan.　C. In Guizhou.　D. In Hunan.\n（　）2. When did she set up the free high school?\nA. In 2000.　B. In 2005.　C. In 2008.　D. In 2020.\n（　）3. Why couldn't many girls go to school?\nA. Because they didn't like school.　B. Because their families were poor.\nC. Because there were no schools.　D. Because they were too young.\n（　）4. How many girls have gone to college thanks to her?\nA. More than 800.　B. More than 1,000.　C. More than 1,800.　D. More than 2,800.\n（　）5. What does Zhang Guimei's story tell us?\nA. It's difficult to be a teacher.　B. We should help others selflessly.\nC. Girls are better than boys.　D. Money is very important.",10,
     kind="阅读理解B"),
   Q(28,"（C）任务型阅读\nIn recent years, more and more Chinese people have started to exercise. Many of them like running.\nRunning is a simple sport. You don't need expensive equipment. You only need a pair of good running shoes. You can run in a park, on a road or in a stadium.\nRunning is good for our health. It is good for the heart. It can help us keep a healthy weight. It can also make us feel relaxed and happy. After a long day's work, running can help us forget our trouble.\nHowever, we should run in a right way. Don't run too fast at the beginning. Warm up before running. Don't run on a full stomach. And don't run when you are tired or ill.\n1. What sport is becoming popular in China? (1)\n2. What do you need if you want to run? (2)\n3. What are the good points of running? (list two) (2)\n4. What should you do before running? (2)\n5. What's the main idea of the passage? (3)",10,
     kind="任务型阅读"),
 ]},
 {"name":"四、词汇与句型（共30分）","questions":[
   Q(29,"根据首字母提示补全单词。（每题1分，共10分）\n1. We should eat more fruit and v______.\n2. The doctor is e______. He has treated many patients.\n3. It's d______ to swim in the river alone.\n4. Our school has a big l______ with many books.\n5. The weather in Kunming is c______ all year round.\n6. I'm very i______ in history.\n7. Please answer my question in a loud v______.\n8. The Great Wall is a s______ of China.\n9. It's n______ to eat breakfast every day.\n10. My father d______ me to school every morning.",10,
     kind="词汇"),
   Q(30,"用括号内所给词的适当形式填空。（每题1分，共10分）\n1. Look! The bus ______ (come).\n2. My sister ______ (be) to the Great Wall twice.\n3. This book ______ (write) by Lu Xun.\n4. It's important ______ (protect) our environment.\n5. He is one of the ______ (tall) boys in his class.\n6. The more exercise you do, the ______ (healthy) you will be.\n7. My parents often encourage me ______ (study) hard.\n8. I'm used to ______ (get) up early.\n9. The window ______ (break) by the boy yesterday.\n10. There ______ (be) a lot of water on the floor.",10,
     kind="词形变化"),
   Q(31,"按要求完成句子。（每题2分，共10分）\n1. He has lived here for ten years.（改为一般疑问句）\n______ he ______ here for ten years?\n2. The book was written by Mo Yan.（对画线部分提问）\n______ was the book written ______?\n3. It is such an interesting book that I want to read it again.（改为同义句）\nThe book is ______ interesting ______ I want to read it again.\n4. He said to me, \"I will come here tomorrow.\"（改为宾语从句）\nHe told me that ______ ______ come there the next day.\n5. I don't know. What should I do?（合并为宾语从句）\nI don't know ______ ______ ______ do.",10,
     kind="句型转换"),
 ]},
 {"name":"五、书面表达（共30分）","questions":[
   Q(32,"（10分）请根据提示写一篇短文，介绍一次难忘的旅行。\n提示：时间、地点、人物、交通方式、看到的景物、感受。要求：词数80左右，语句通顺。",10,
     kind="书面表达"),
   Q(33,"（20分）请以「My English Learning」为题，写一篇短文，介绍你学习英语的情况。\n提示：①你对英语的看法；②你学习英语的方法（如听英文歌、看英文电影、背单词、读英文文章等）；③你在英语学习中遇到的困难；④今后的打算。\n要求：词数100左右；语句通顺，意思连贯；不得出现真实姓名。",20,
     kind="书面表达"),
 ]},
]
answers = [
 A(1,"A","last night 是明确的一般过去时标志。"),
 A(2,"B","宾语从句表示客观真理时，无论主句时态如何，从句都用一般现在时。"),
 A(3,"A","one of the + 最高级 + 复数名词，表示「最……的之一」。"),
 A(4,"A","had better 后接动词原形，You'd better 是 You had better 的缩写。"),
 A(5,"A","yet 用于疑问句和否定句，already 用于肯定句。"),
 A(6,"A","neither...nor... 连接两个主语时，谓语与就近主语一致，I 用 am。"),
 A(7,"B","with + 名词作定语，修饰 the girl，表示「留着长发的女孩」。"),
 A(8,"A","Why not + 动词原形，表示提出建议。"),
 A(9,"C","since he was born 是现在完成时的标志。"),
 A(10,"A","so + adj. + that 引导结果状语从句。"),
 A(11,"B","宾语从句必须用陈述语序，且主句为现在时，从句时态不变。"),
 A(12,"B","homework 是动作承受者，yesterday 表示过去，用一般过去时被动语态。"),
 A(13,"A","to 是动词不定式符号，后接动词原形。"),
 A(14,"B","so + adv. + that 引导结果状语从句，fast 是副词。"),
 A(15,"A","Take it easy 意为「别紧张」，符合语境。"),
 A(16,"A","叙述过去的情况，用一般过去时 took。"),
 A(17,"B","父母说「努力学习，你们的未来会更好」，符合语境。"),
 A(18,"A","by the oil lamp 意为「借着油灯（的光）」。"),
 A(19,"A","叙述过去的事情，用一般过去时 helped。"),
 A(20,"A","不定式符号 to 后接动词原形 give。"),
 A(21,"A","母亲叮嘱「对自己好一点，好好学习」，be good to yourself。"),
 A(22,"B","「知识是通向美好未来的钥匙」，符合语境。"),
 A(23,"B","be thankful for 意为「对……心怀感激」。"),
 A(24,"A","be grateful to sb. 意为「对某人感激」。"),
 A(25,"C","realize one's dream 意为「实现梦想」。"),
 A(26,"1. B（Dogs are the most popular pets）　2. D（文中说养狗需要很多工作，不是容易）　3. B（help blind people）　4. B（barks to warn us）　5. C（needs a lot of work）","评分：每题2分。"),
 A(27,"1. B（in Yunnan Province）　2. C（In 2008）　3. B（their families were poor）　4. C（more than 1,800 girls）　5. B（她的故事告诉我们要无私助人）","评分：每题2分。"),
 A(28,"1. Running.（1分）\n2. A pair of good running shoes.（2分）\n3. It is good for the heart / It can help us keep a healthy weight / It can make us feel relaxed and happy.（任答两点，2分）\n4. We should warm up before running.（2分）\n5. The passage tells us that running is good for our health and how to run in a right way.（3分）","评分：见上，意思相近即可。"),
 A(29,"1. vegetables　2. excellent　3. dangerous　4. library　5. comfortable　6. interested　7. voice　8. symbol　9. necessary　10. drives","评分：每题1分。"),
 A(30,"1. is coming　2. has been　3. was written　4. to protect　5. tallest　6. healthier　7. to study　8. getting　9. was broken　10. is","评分：每题1分。"),
 A(31,"1. Has; lived　2. Who; by　3. so; that　4. he; would　5. what I should","评分：每题2分。"),
 A(32,"范文：\nAn Unforgettable Trip\nLast summer, I went to Hainan with my parents. We went there by plane.\nHainan is a beautiful place. The sky was blue and the sea was clean. We walked on the beach and enjoyed the sunshine. We also swam in the sea. It was very exciting. In the evening, we ate delicious seafood.\nWe stayed there for five days. I took many photos. It was a wonderful trip. I will never forget it.","评分标准：要点完整4分，语言准确4分，书写规范2分。"),
 A(33,"范文：\nMy English Learning\nI think English is very important and useful. It is a bridge to the world.\nI have my own ways to learn English. First, I listen to English songs and watch English movies. This helps me improve my listening. Second, I keep a word notebook and try to remember ten new words every day. Third, I read English stories after class.\nOf course, I have some problems. Speaking is the most difficult for me. I'm afraid of making mistakes.\nIn the future, I will practice speaking more and be braver. I believe I can learn English well.","评分标准：\n一类（17—20分）：要点齐全，语言流畅，语法正确，衔接自然。\n二类（13—16分）：要点较全，语言基本通顺，有少量语法错误。\n三类（9—12分）：要点基本齐全，语言有较多错误，但能达意。\n四类（8分以下）：要点不全，语言错误多，影响理解。"),
]
out.append(save(m, p, answers, "能力提升C卷"))

# ================= D卷 =================
m = base("八年级英语", "第二学期期末教学质量监测", "（仁爱版　2025—2026学年　第二学期　满分120分　时间120分钟）", fs=120, dur=120)
p = [
 {"name":"一、单项选择（每题1分，共15分）","questions":[
   Q(1,"— ______ have you been a volunteer?\n— For three years.",1,
     opts=["A. How often　B. How long　C. How soon　D. How far"], kind="疑问词"),
   Q(2,"The teachers ______ to work hard for the students.",1,
     opts=["A. are encourage　B. are encouraged　C. encourage　D. encouraging"], kind="被动语态"),
   Q(3,"I'll call you as soon as I ______ home.",1,
     opts=["A. get　B. will get　C. got　D. am getting"], kind="时间状语从句"),
   Q(4,"— Must I finish the work today?\n— No, you ______.",1,
     opts=["A. mustn't　B. can't　C. needn't　D. shouldn't"], kind="情态动词"),
   Q(5,"This is the school ______ I visited last year.",1,
     opts=["A. which　B. where　C. what　D. who"], kind="定语从句"),
   Q(6,"He is ______ honest boy that everyone trusts him.",1,
     opts=["A. so an　B. such an　C. so a　D. such a"], kind="such...that"),
   Q(7,"— Would you like some tea?\n— ______. I'd like some coffee.",1,
     opts=["A. Yes, please　B. No, thanks　C. Never mind　D. That's right"], kind="情景交际"),
   Q(8,"The population of China ______ large, and most people ______ farmers in the past.",1,
     opts=["A. is; were　B. are; was　C. is; was　D. are; were"], kind="主谓一致"),
   Q(9,"We should try our best ______ the environment.",1,
     opts=["A. protect　B. to protect　C. protecting　D. protected"], kind="不定式作目的状语"),
   Q(10,"— I've never seen such a beautiful place.\n— ______.",1,
     opts=["A. So have I　B. Neither have I　C. So I have　D. Neither I have"], kind="倒装句"),
   Q(11,"The girl ______ is wearing a red skirt is my sister.",1,
     opts=["A. which　B. who　C. whom　D. whose"], kind="定语从句"),
   Q(12,"It is reported that a new hospital ______ in our city next year.",1,
     opts=["A. is built　B. will be built　C. builds　D. will build"], kind="一般将来时被动"),
   Q(13,"The teacher asked us ______ in class.",1,
     opts=["A. not talk　B. not to talk　C. don't talk　D. to not talk"], kind="不定式否定"),
   Q(14,"— What a nice day! How about ______ a picnic?\n— Great!",1,
     opts=["A. have　B. to have　C. having　D. had"], kind="How about doing"),
   Q(15,"He didn't go to bed ______ he finished his homework.",1,
     opts=["A. until　B. when　C. while　D. as"], kind="not...until"),
 ]},
 {"name":"二、完形填空（每题1.5分，共15分）","questions":[
   Q(16,"阅读下面短文，从每题所给的选项中选出最佳答案。\nHave you ever thought about how to spend your pocket money? Here are some good ideas for you.\nFirst, you can 16 some money. It's a good habit to save money. You can put your money in a bank 17 keep it for a rainy day.\nSecond, you can buy something 18 . You can buy books or stationery. These things can help you study better.\nThird, you can 19 your money to help others. You can give it to a charity. You can also buy some gifts for your parents. They will be very 20.\nFourth, you can learn something new 21 your money. You can take a course, such as a painting class. Learning new skills 22 you happier.\nRemember, money is not everything. But if you use it 23, it can bring you and others happiness. So think 24 before you spend your money. It's a good way to learn how to 25 money.\n16.",1.5,
     opts=["A. save　B. saves　C. saving　D. saved"], kind="完形填空"),
   Q(17,"17.",1.5,
     opts=["A. and　B. but　C. or　D. so"], kind="完形填空"),
   Q(18,"18.",1.5,
     opts=["A. useful　B. useless　C. boring　D. terrible"], kind="完形填空"),
   Q(19,"19.",1.5,
     opts=["A. take　B. use　C. spend　D. cost"], kind="完形填空"),
   Q(20,"20.",1.5,
     opts=["A. sad　B. angry　C. happy　D. tired"], kind="完形填空"),
   Q(21,"21.",1.5,
     opts=["A. in　B. on　C. with　D. for"], kind="完形填空"),
   Q(22,"22.",1.5,
     opts=["A. make　B. makes　C. made　D. making"], kind="完形填空"),
   Q(23,"23.",1.5,
     opts=["A. careful　B. carefully　C. careless　D. carelessly"], kind="完形填空"),
   Q(24,"24.",1.5,
     opts=["A. twice　B. two　C. second　D. twice times"], kind="完形填空"),
   Q(25,"25.",1.5,
     opts=["A. manage　B. manages　C. managing　D. managed"], kind="完形填空"),
 ]},
 {"name":"三、阅读理解（每题2分，共30分）","questions":[
   Q(26,"（A）\nThe smartphone has changed our lives greatly. It brings us a lot of convenience.\nWith a smartphone, we can do many things. We can call and message others easily. We can search for information on the Internet. We can take photos, listen to music and watch videos. We can also shop online and pay for things without cash.\nHowever, smartphones also bring problems. Some people spend too much time on their phones. They play games or watch videos for hours. This is bad for their eyes and health. Some students even use phones in class, which affects their study. Some people become less patient and talk less with their family.\nSo we should use smartphones properly. We shouldn't use them too much. We should spend more time with our family and friends.\n（　）1. What does the passage talk about?\nA. The history of smartphones.　B. The good and bad points of smartphones.\nC. How to buy a smartphone.　D. The price of smartphones.\n（　）2. Which is NOT mentioned as a use of smartphones?\nA. Calling others.　B. Searching for information.\nC. Driving a car.　D. Shopping online.\n（　）3. What problem can smartphones bring?\nA. They make us rich.　B. They are bad for our eyes and health.\nC. They make us smarter.　D. They help us study better.\n（　）4. What should we do with smartphones?\nA. Use them as much as possible.　B. Never use them.\nC. Use them properly.　D. Only use them for games.\n（　）5. What's the writer's attitude towards smartphones?\nA. Completely against.　B. Completely supportive.\nC. Objective (客观的).　D. Not clear.",10,
     kind="阅读理解A"),
   Q(27,"（B）\nYuan Longping is known as the 'Father of Hybrid Rice'. He was born in 1930 in Beijing.\nWhen Yuan Longping was young, he saw many people die of hunger. He decided to study agriculture and help people grow more food.\nAfter many years of hard work, he developed hybrid rice in the 1970s. This new kind of rice could produce much more than ordinary rice. It helped feed millions of people in China and other countries.\nYuan Longping worked in the fields even when he was old. He said, 'I have two dreams. One is to enjoy the cool under the rice crops taller than men. The other is to make hybrid rice cover the whole world.'\nHe passed away in 2021, but his spirit will live forever.\n（　）1. What is Yuan Longping known as?\nA. The Father of Rice.　B. The Father of Hybrid Rice.\nC. The Father of Agriculture.　D. The Father of Science.\n（　）2. Why did Yuan Longping decide to study agriculture?\nA. Because he liked plants.　B. Because he wanted to be famous.\nC. Because he saw people die of hunger.　D. Because his parents asked him to.\n（　）3. When did he develop hybrid rice?\nA. In the 1950s.　B. In the 1960s.　C. In the 1970s.　D. In the 1980s.\n（　）4. What was one of Yuan Longping's dreams?\nA. To be a rich man.　B. To enjoy the cool under tall rice crops.\nC. To travel around the world.　D. To write a book.\n（　）5. What can we learn from Yuan Longping?\nA. We should work hard and help others.　B. We should always rest.\nC. We should only care about ourselves.　D. We should give up easily.",10,
     kind="阅读理解B"),
   Q(28,"（C）任务型阅读\nChinese traditional festivals are an important part of Chinese culture. Each festival has its own meaning and customs.\nThe Spring Festival is the most important festival in China. It usually comes in January or February. Before the festival, families clean their houses and buy new clothes. On New Year's Eve, families get together and have a big dinner. Children can get red packets from their parents and relatives.\nThe Mid-Autumn Festival comes in September or October. On that day, families get together and eat mooncakes. People also enjoy the full moon at night. It is a time for family reunion.\nThe Dragon Boat Festival comes in May or June. People eat zongzi and watch dragon boat races. It is held to remember the great poet Qu Yuan.\n1. What is the most important festival in China? (1)\n2. What do families do before the Spring Festival? (2)\n3. What do people eat on the Mid-Autumn Festival? (2)\n4. Why do people hold the Dragon Boat Festival? (2)\n5. What's the main idea of the passage? (3)",10,
     kind="任务型阅读"),
 ]},
 {"name":"四、词汇与句型（共30分）","questions":[
   Q(29,"根据首字母提示补全单词。（每题1分，共10分）\n1. We should take a______ to reduce pollution.\n2. The f______ of the mountain is very beautiful.\n3. He is a p______ boy. He always helps others.\n4. It's i______ to keep the classroom clean.\n5. My h______ is playing basketball.\n6. China has a long h______ of about 5,000 years.\n7. We should r______ the rules of the school.\n8. The soup tastes d______. I want some more.\n9. He is p______ for the coming exam.\n10. Reading can make us s______.",10,
     kind="词汇"),
   Q(30,"用括号内所给词的适当形式填空。（每题1分，共10分）\n1. The room ______ (clean) every day.\n2. My father ______ (be) to Beijing twice.\n3. She is good at ______ (dance).\n4. The more you practice, the ______ (good) you will be.\n5. It's important for us ______ (keep) healthy.\n6. Look! The children ______ (play) games.\n7. The window ______ (break) by Tom yesterday.\n8. I'm looking forward to ______ (hear) from you.\n9. He is the boy ______ (who) won the game.\n10. If it ______ (rain) tomorrow, we will not go out.",10,
     kind="词形变化"),
   Q(31,"按要求完成句子。（每题2分，共10分）\n1. People use computers widely today.（改为被动语态）\nComputers ______ ______ widely today.\n2. He has studied English for five years.（对画线部分提问）\n______ ______ has he studied English?\n3. The box is so heavy that I can't carry it.（改为同义句）\nThe box is ______ heavy ______ me ______ carry.\n4. \"Where do you live?\" he asked me.（改为宾语从句）\nHe asked me ______ I ______.\n5. We should protect the environment.（改为同义句）\nWe ______ ______ protect the environment.",10,
     kind="句型转换"),
 ]},
 {"name":"五、书面表达（共30分）","questions":[
   Q(32,"（10分）请根据提示写一篇短文，介绍你最喜欢的传统节日。\n提示：节日名称、时间、人们通常做什么、你为什么喜欢。要求：词数80左右，语句通顺。",10,
     kind="书面表达"),
   Q(33,"（20分）请以「How to Use Mobile Phones Properly」为题，写一篇短文。\n提示：①手机给我们带来的便利；②过度使用手机带来的问题；③你的建议。\n要求：词数100左右；语句通顺，意思连贯；不得出现真实姓名。",20,
     kind="书面表达"),
 ]},
]
answers = [
 A(1,"B","回答是时间段「For three years」，用 How long 提问。"),
 A(2,"B","teachers 是动作承受者，用被动语态 are encouraged。"),
 A(3,"A","as soon as 引导时间状语从句，主将从现，从句用一般现在时。"),
 A(4,"C","以 Must 提问的疑问句，否定回答用 needn't，表示「不必」。"),
 A(5,"A","先行词 the school 是物，关系代词在从句中作宾语，用 which（或 that）。"),
 A(6,"B","honest 的 h 不发音，读音以元音音素开头，故用 such an。"),
 A(7,"B","根据回答「I'd like some coffee」可知拒绝了茶，用 No, thanks。"),
 A(8,"A","The population of China 作主语用单数 is；in the past 表示过去，用 were。"),
 A(9,"B","try one's best to do sth. 尽力做某事，to protect 作目的状语。"),
 A(10,"B","前面是「我从没见过」，我也没见过，用 Neither have I。"),
 A(11,"B","先行词 the girl 指人，关系代词作从句主语，用 who。"),
 A(12,"B","next year 表示将来，hospital 是动作承受者，用一般将来时被动语态 will be built。"),
 A(13,"B","ask sb. not to do sth. 要求某人不要做某事。"),
 A(14,"C","How about + 动名词，表示提出建议。"),
 A(15,"A","not...until... 结构，表示「直到……才……」。"),
 A(16,"A","情态动词 can 后接动词原形 save。"),
 A(17,"A","put your money in a bank 与 keep it for a rainy day 是并列关系，用 and。"),
 A(18,"A","买「有用的」东西，如书和文具。"),
 A(19,"B","use your money to help others 用你的钱帮助别人，符合语境。"),
 A(20,"C","父母收到孩子的礼物会「高兴」。"),
 A(21,"C","用钱学习新事物，with 表示「用（工具/手段）」。"),
 A(22,"B","动名词短语 Learning new skills 作主语，谓语用单数 makes。"),
 A(23,"B","修饰动词 use 用副词 carefully。"),
 A(24,"A","think twice 是固定搭配，意为「三思而后行」。"),
 A(25,"A","how to + 动词原形，manage money 意为「理财」。"),
 A(26,"1. B（讲手机的优缺点）　2. C（文中未提到开车）　3. B（bad for eyes and health）　4. C（use them properly）　5. C（作者既讲优点又讲缺点，态度客观）","评分：每题2分。"),
 A(27,"1. B（Father of Hybrid Rice）　2. C（he saw many people die of hunger）　3. C（in the 1970s）　4. B（enjoy the cool under the rice crops taller than men）　5. A（从他身上学到努力工作、帮助他人）","评分：每题2分。"),
 A(28,"1. The Spring Festival.（1分）\n2. They clean their houses and buy new clothes.（2分）\n3. They eat mooncakes.（2分）\n4. To remember the great poet Qu Yuan.（2分）\n5. The passage introduces three important Chinese traditional festivals and their customs.（3分）","评分：见上，意思相近即可。"),
 A(29,"1. actions　2. forest　3. polite　4. important　5. hobby　6. history　7. respect　8. delicious　9. preparing　10. smarter","评分：每题1分。"),
 A(30,"1. is cleaned　2. has been　3. dancing　4. better　5. to keep　6. are playing　7. was broken　8. hearing　9. who　10. rains","评分：每题1分。"),
 A(31,"1. are used　2. How long　3. too; for; to　4. where; lived　5. ought to / are supposed to","评分：每题2分。"),
 A(32,"范文：\nMy Favorite Festival\nMy favorite festival is the Spring Festival.\nIt usually comes in January or February. It is the most important festival in China. Before the festival, my family cleans the house and buys new clothes. On New Year's Eve, we get together and have a big dinner. I can also get red packets from my parents.\nI like it because I can stay with my family and enjoy delicious food. It is full of happiness and love.","评分标准：要点完整4分，语言准确4分，书写规范2分。"),
 A(33,"范文：\nHow to Use Mobile Phones Properly\nMobile phones bring us a lot of convenience. We can call others, search for information, shop online and pay for things easily.\nHowever, using phones too much can cause problems. It is bad for our eyes and health. Some students even use phones in class, which affects their study. Some people talk less with their family because of phones.\nSo I think we should use phones properly. We should not use them too long. We should spend more time with our family and friends. Only in this way can phones really help us.","评分标准：\n一类（17—20分）：要点齐全，语言流畅，语法正确，衔接自然。\n二类（13—16分）：要点较全，语言基本通顺，有少量语法错误。\n三类（9—12分）：要点基本齐全，语言有较多错误，但能达意。\n四类（8分以下）：要点不全，语言错误多，影响理解。"),
]
out.append(save(m, p, answers, "质量监测D卷"))

# ================= E卷 =================
m = base("八年级英语", "第一学期期末学业质量综合评价", "（仁爱版　2025—2026学年　第一学期　满分120分　时间120分钟）", fs=120, dur=120)
p = [
 {"name":"一、单项选择（每题1分，共15分）","questions":[
   Q(1,"My sister is ______ university student.",1,
     opts=["A. a　B. an　C. the　D. /"], kind="冠词"),
   Q(2,"There ______ a meeting tomorrow afternoon.",1,
     opts=["A. will have　B. is going to have　C. will be　D. is going to be"], kind="there be 将来时"),
   Q(3,"— ______ is the weather like today?\n— It's sunny.",1,
     opts=["A. How　B. What　C. Where　D. When"], kind="疑问词"),
   Q(4,"The students are busy ______ their homework.",1,
     opts=["A. do　B. to do　C. doing　D. did"], kind="be busy doing"),
   Q(5,"He ______ in this school since 2018.",1,
     opts=["A. teaches　B. taught　C. has taught　D. is teaching"], kind="现在完成时"),
   Q(6,"— How ______ is the river?\n— About 50 meters wide.",1,
     opts=["A. long　B. wide　C. deep　D. tall"], kind="疑问词"),
   Q(7,"This is ______ interesting story I have ever read.",1,
     opts=["A. a most　B. the most　C. most　D. more"], kind="最高级"),
   Q(8,"Let's ______ the meeting room.",1,
     opts=["A. to clean　B. cleaning　C. clean　D. cleaned"], kind="祈使句"),
   Q(9,"The boy is ______ to look after himself.",1,
     opts=["A. enough old　B. old enough　C. too old　D. so old"], kind="enough用法"),
   Q(10,"— I have a bad cold.\n— ______.",1,
     opts=["A. That's OK　B. I'm sorry to hear that　C. Thank you　D. You're welcome"], kind="情景交际"),
   Q(11,"Do you know when the train ______ ?",1,
     opts=["A. leaves　B. leave　C. left　D. leaving"], kind="宾语从句时态"),
   Q(12,"It's very hot today. Why not ______ swimming?",1,
     opts=["A. go　B. to go　C. going　D. went"], kind="Why not do"),
   Q(13,"He prefers reading books ______ watching TV.",1,
     opts=["A. than　B. to　C. for　D. with"], kind="prefer...to"),
   Q(14,"The accident ______ last Sunday.",1,
     opts=["A. happens　B. happened　C. is happening　D. will happen"], kind="一般过去时"),
   Q(15,"— Excuse me, could you tell me the way to the bank?\n— ______.",1,
     opts=["A. Yes, I could　B. Sorry, I'm new here too",
           "C. Thank you　D. That's all right"], kind="情景交际"),
 ]},
 {"name":"二、完形填空（每题1.5分，共15分）","questions":[
   Q(16,"阅读下面短文，从每题所给的选项中选出最佳答案。\nSports are important for everyone. They can make us 16 and healthy. Here is something about sports.\nFirst, sports can make our body 17. If we do sports every day, we won't get ill easily. Sports can also help us grow 18.\nSecond, sports can make us happy. When we play sports, our body produces something that makes us 19. After a day's study, playing sports is a good way to 20.\nThird, sports can teach us many things. In a team game, we learn to 21 with others. We learn to help each other and to work 22. We also learn that winning is not the only thing that 23.\nSo we should do sports often. We can 24 or run in the morning. We can play ball games after school. But remember, we should choose the right sport and do it 25, or we may get hurt.\n16.",1.5,
     opts=["A. strong　B. weak　C. tired　D. lazy"], kind="完形填空"),
   Q(17,"17.",1.5,
     opts=["A. small　B. strong　C. heavy　D. short"], kind="完形填空"),
   Q(18,"18.",1.5,
     opts=["A. taller　B. slower　C. worse　D. poorer"], kind="完形填空"),
   Q(19,"19.",1.5,
     opts=["A. sad　B. angry　C. happy　D. afraid"], kind="完形填空"),
   Q(20,"20.",1.5,
     opts=["A. relax　B. study　C. sleep　D. eat"], kind="完形填空"),
   Q(21,"21.",1.5,
     opts=["A. fight　B. talk　C. work　D. play"], kind="完形填空"),
   Q(22,"22.",1.5,
     opts=["A. alone　B. together　C. slowly　D. quickly"], kind="完形填空"),
   Q(23,"23.",1.5,
     opts=["A. matters　B. matter　C. mattered　D. mattering"], kind="完形填空"),
   Q(24,"24.",1.5,
     opts=["A. walk　B. walks　C. walking　D. walked"], kind="完形填空"),
   Q(25,"25.",1.5,
     opts=["A. careful　B. carefully　C. careless　D. carelessly"], kind="完形填空"),
 ]},
 {"name":"三、阅读理解（每题2分，共30分）","questions":[
   Q(26,"（A）\nReading is a good hobby for all kinds of reasons.\nFirst, reading is fun. You can always keep yourself happy if you like reading. You will never feel bored or tired.\nNext, you can read a book anywhere — in a car, on a plane, or even in the bathroom. All you need is a book!\nAnother good reason for reading is that it is useful. If you read as a hobby, you will get better and better at it. And you will read faster and find it easier to understand what you read. As your reading skills improve, you will probably find your schoolwork becomes much better.\nSome people say that reading is out of date. This is not true. You can read on computers, and the more you read, the better your computer skills will be.\nGood readers may become writers, too. They always have more things to write about.\n（　）1. What is the passage mainly about?\nA. Why reading is a good hobby.　B. How to read a book.\nC. Where to buy books.　D. When to read books.\n（　）2. What do you need if you want to read anywhere?\nA. A computer.　B. A phone.　C. A book.　D. A light.\n（　）3. What will happen if your reading skills improve?\nA. You will be tired.　B. Your schoolwork may become better.\nC. You will feel bored.　D. You will read more slowly.\n（　）4. Why is reading NOT out of date?\nA. Because books are cheap.　B. Because you can read on computers.\nC. Because nobody reads now.　D. Because reading is a job.\n（　）5. What may good readers become?\nA. Teachers.　B. Doctors.　C. Writers.　D. Engineers.",10,
     kind="阅读理解A"),
   Q(27,"（B）\nMa Long is a famous Chinese table tennis player. He was born in Liaoning Province in 1988.\nMa Long started to play table tennis when he was five years old. He worked very hard and became a member of the national team in 2003.\nMa Long has won many championships. He is called 'the Dragon' by his fans. In 2016, he won the gold medal at the Rio Olympic Games. In 2020, he won the gold medal again at the Tokyo Olympic Games.\nMa Long is not only a great player but also a good example. He is modest and hard-working. He often says, 'I will keep working hard and never give up.'\nHis story tells us that if we work hard, we can achieve our dreams.\n（　）1. What sport does Ma Long play?\nA. Basketball.　B. Football.　C. Table tennis.　D. Badminton.\n（　）2. When did Ma Long start to play table tennis?\nA. At 3.　B. At 5.　C. At 8.　D. At 10.\n（　）3. When did he become a member of the national team?\nA. In 2001.　B. In 2003.　C. In 2008.　D. In 2016.\n（　）4. What do his fans call him?\nA. The Tiger.　B. The Dragon.　C. The Lion.　D. The Eagle.\n（　）5. What can we learn from Ma Long?\nA. We should give up easily.　B. We should work hard and never give up.\nC. We should only play sports.　D. We should be proud.",10,
     kind="阅读理解B"),
   Q(28,"（C）任务型阅读\nXianning (咸宁) is a beautiful city in Hubei Province. It is known as the 'City of Osmanthus' (桂花之城) and the 'City of Hot Springs' (温泉之城).\nXianning is in the south of Hubei. It is not far from Wuhan. It takes about one hour to get to Wuhan by high-speed train. Xianning has a long history and rich culture. It is also famous for its beautiful natural scenery.\nThere are many places of interest in Xianning. Chibi (赤壁) is a famous ancient battlefield. It is well known because of the Battle of Red Cliffs. There are also many hot springs. Every year, many tourists come here to relax and enjoy themselves.\nThe people in Xianning are friendly and hard-working. They are working hard to make their hometown better and better.\n1. What is Xianning known as? (2)\n2. How long does it take to get to Wuhan from Xianning by high-speed train? (2)\n3. What is Chibi famous for? (2)\n4. Why do many tourists come to Xianning every year? (2)\n5. What's the main idea of the passage? (2)",10,
     kind="任务型阅读"),
 ]},
 {"name":"四、词汇与句型（共30分）","questions":[
   Q(29,"根据首字母提示补全单词。（每题1分，共10分）\n1. We should protect the e______ of our city.\n2. He is a c______ boy. He always has many new ideas.\n3. Don't be a______ of making mistakes.\n4. The Great Wall is a f______ place in China.\n5. My mother is c______ dinner in the kitchen.\n6. We have d______ kinds of food in the school dining hall.\n7. I'm t______. Let's have a rest.\n8. Beijing is the c______ of China.\n9. It's s______ of you to believe him.\n10. She sings very w______.",10,
     kind="词汇"),
   Q(30,"用括号内所给词的适当形式填空。（每题1分，共10分）\n1. Look! The students ______ (do) morning exercises.\n2. My father ______ (go) to work by car every day.\n3. She ______ (be) here since last Sunday.\n4. This is the ______ (interesting) book I have ever read.\n5. We should be ______ (friend) to others.\n6. He is used to ______ (get) up at six.\n7. The homework ______ (finish) yesterday.\n8. Thank you for ______ (help) me.\n9. There ______ (be) some milk in the glass.\n10. She is the girl ______ (who) sings best in our class.",10,
     kind="词形变化"),
   Q(31,"按要求完成句子。（每题2分，共10分）\n1. He goes to school on foot.（改为同义句）\nHe ______ ______ school.\n2. She has lived here for five years.（改为一般疑问句）\n______ she ______ here for five years?\n3. The box is too heavy for me to carry.（改为同义句）\nThe box is ______ heavy ______ I can't carry it.\n4. \"I am watching TV,\" he said.（改为宾语从句）\nHe said that ______ ______ watching TV.\n5. The children are playing football on the playground.（对画线部分提问）\n______ ______ the children playing football?",10,
     kind="句型转换"),
 ]},
 {"name":"五、书面表达（共30分）","questions":[
   Q(32,"（10分）请根据提示写一篇短文，介绍你的学校生活。\n提示：上学时间、课程、最喜欢的科目、课外活动、感受。要求：词数80左右，语句通顺。",10,
     kind="书面表达"),
   Q(33,"（20分）请以「My Summer Holiday Plan」为题，写一篇短文。\n提示：①假期打算做什么；②为什么这样安排；③你的期待。\n要求：词数100左右；语句通顺，意思连贯；不得出现真实姓名。",20,
     kind="书面表达"),
 ]},
]
answers = [
 A(1,"A","university 的读音以辅音音素 /j/ 开头，用 a。"),
 A(2,"D","There be 句型的将来时为 There will be 或 There is going to be，不能与 have 连用。"),
 A(3,"B","What's the weather like 是询问天气的固定句型。"),
 A(4,"C","be busy doing sth. 忙于做某事。"),
 A(5,"C","since 2018 是现在完成时的标志。"),
 A(6,"B","回答「About 50 meters wide」表示宽度，用 How wide 提问。"),
 A(7,"B","「我读过的最有趣的故事」，用最高级 the most interesting。"),
 A(8,"C","Let's 后接动词原形。"),
 A(9,"B","enough 修饰形容词时后置：old enough。"),
 A(10,"B","听到别人生病应说 I'm sorry to hear that。"),
 A(11,"A","宾语从句中，表示将来发生的动作，主句现在时，从句可用一般现在时表将来（火车时刻）。"),
 A(12,"A","Why not + 动词原形。"),
 A(13,"B","prefer A to B 表示「比起B更喜欢A」。"),
 A(14,"B","last Sunday 是一般过去时标志。"),
 A(15,"B","不能提供帮助时应礼貌回复，如 Sorry, I'm new here too。"),
 A(16,"A","做运动能让我们「强壮」和健康。"),
 A(17,"B","做运动能让身体「强壮」。"),
 A(18,"A","运动有助于我们长得「更高」。"),
 A(19,"C","运动时身体产生的物质让我们「快乐」。"),
 A(20,"A","学习一天后，运动是「放松」的好方法。"),
 A(21,"C","在团队运动中，我们学会与他人「合作」。"),
 A(22,"B","学会互相帮助、共同「协作」（work together）。"),
 A(23,"A","主语是 the only thing，谓语用单数 matters。"),
 A(24,"A","情态动词 can 后接动词原形 walk。"),
 A(25,"B","修饰动词 do 用副词 carefully。"),
 A(26,"1. A（讲读书是好爱好的原因）　2. C（All you need is a book）　3. B（your schoolwork becomes much better）　4. B（You can read on computers）　5. C（Good readers may become writers, too）","评分：每题2分。"),
 A(27,"1. C（table tennis）　2. B（At 5）　3. B（In 2003）　4. B（The Dragon）　5. B（work hard and never give up）","评分：每题2分。"),
 A(28,"1. It is known as the 'City of Osmanthus' and the 'City of Hot Springs'.（2分）\n2. About one hour.（2分）\n3. It is famous for the Battle of Red Cliffs (as an ancient battlefield).（2分）\n4. Because they come to relax in the hot springs and enjoy themselves.（2分）\n5. The passage introduces Xianning's location, culture, famous places and people.（2分）","评分：见上，意思相近即可。"),
 A(29,"1. environment　2. creative　3. afraid　4. famous　5. cooking　6. different　7. tired　8. capital　9. silly　10. well","评分：每题1分。"),
 A(30,"1. are doing　2. goes　3. has been　4. most interesting　5. friendly　6. getting　7. was finished　8. helping　9. is　10. who","评分：每题1分。"),
 A(31,"1. walks to　2. Has; lived　3. so; that　4. he; was　5. Where are","评分：每题2分。"),
 A(32,"范文：\nMy School Life\nI usually go to school at seven in the morning. We have four classes in the morning and three in the afternoon.\nMy favorite subject is English, because it is interesting and useful. Our English teacher is very kind.\nAfter class, I often play basketball with my friends. We also have many activities, such as art and music clubs.\nI like my school life very much. It is busy but happy.","评分标准：要点完整4分，语言准确4分，书写规范2分。"),
 A(33,"范文：\nMy Summer Holiday Plan\nThe summer holiday is coming. I have made a plan for it.\nFirst, I will do my homework carefully and review my lessons. I want to do better in the new term.\nSecond, I will read some English books and watch English movies to improve my English. I also want to learn to swim.\nThird, I will travel to Hainan with my parents. I have never seen the sea, so I am very excited about it.\nI hope my summer holiday will be meaningful and fun.","评分标准：\n一类（17—20分）：要点齐全，语言流畅，语法正确，衔接自然。\n二类（13—16分）：要点较全，语言基本通顺，有少量语法错误。\n三类（9—12分）：要点基本齐全，语言有较多错误，但能达意。\n四类（8分以下）：要点不全，语言错误多，影响理解。"),
]
out.append(save(m, p, answers, "综合评价E卷"))

print("已生成 %d 套：" % len(out))
for o in out: print(" -", o)
