# -*- coding: utf-8 -*-
"""四年级 英语（人教版PEP）期末试卷（5套）"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from paper_common import save, base, Q, A
out = []

# ================= A卷 =================
m = base("四年级英语", "第一学期期末质量检测", "（人教版PEP　三年级起点　2025—2026学年　第一学期）")
p = [
 {"name":"一、判断下列单词划线部分读音是否相同（相同写S，不同写D）（10分）","questions":[
   Q(1,"（　）name　cake",2), Q(2,"（　）cat　bag",2), Q(3,"（　）bike　five",2),
   Q(4,"（　）ship　big",2), Q(5,"（　）nose　note",2),
 ]},
 {"name":"二、看图选词（10分）","questions":[
   Q(1,"教室设施：classroom（　）　window（　）　blackboard（　）　light（　）　door（　）",5,
     opts=["A. 教室　B. 窗户　C. 黑板　D. 灯　E. 门"], blanks=5),
   Q(2,"学习用品：schoolbag（　）　notebook（　）　storybook（　）　maths book（　）　English book（　）",5,
     opts=["A. 书包　B. 笔记本　C. 故事书　D. 数学书　E. 英语书"], blanks=5),
 ]},
 {"name":"三、选出不同类的一项（10分）","questions":[
   Q(1,"（　）",2, opts=["A. window　B. door　C. red"]),
   Q(2,"（　）",2, opts=["A. notebook　B. storybook　C. strong"]),
   Q(3,"（　）",2, opts=["A. long　B. short　C. light"]),
   Q(4,"（　）",2, opts=["A. chair　B. desk　C. hair"]),
   Q(5,"（　）",2, opts=["A. he　B. she　C. long"]),
 ]},
 {"name":"四、单项选择（20分）","questions":[
   Q(1,"—— Where is my book?　—— ________ on the desk.",2, opts=["A. It's　B. They're　C. Is"]),
   Q(2,"—— What's in the classroom?　—— ________.",2, opts=["A. Many desks and chairs.　B. Yes, it is.　C. It's a desk."]),
   Q(3,"Let's ________ the classroom.",2, opts=["A. clean　B. cleans　C. cleaning"]),
   Q(4,"________ is she? —— She is my friend.",2, opts=["A. Who　B. What　C. Where"]),
   Q(5,"My friend has ________ hair.",2, opts=["A. long　B. a long　C. longs"]),
   Q(6,"He ________ glasses.",2, opts=["A. has　B. have　C. is"]),
   Q(7,"—— How many books?　—— ________.",2, opts=["A. Three.　B. Book.　C. Yes."]),
   Q(8,"She ________ my new friend.",2, opts=["A. is　B. are　C. am"]),
   Q(9,"—— Is this your pen?　—— Yes, ________.",2, opts=["A. it is　B. it isn't　C. they are"]),
   Q(10,"Let me ________.",2, opts=["A. help you　B. helps you　C. helping you"]),
 ]},
 {"name":"五、情景选择（15分）","questions":[
   Q(1,"你想知道对方的新朋友是谁，应该问：________",3, opts=["A. Who is your new friend?　B. Where are you?　C. How old are you?"]),
   Q(2,"你想说「我们打扫教室吧」，应该说：________",3, opts=["A. Let's clean the classroom.　B. The classroom is big.　C. I like the classroom."]),
   Q(3,"你想描述朋友「他又高又壮」，应该说：________",3, opts=["A. He is tall and strong.　B. She is tall and strong.　C. He has a book."]),
   Q(4,"你请别人帮你拿书，应该礼貌地说：________",3, opts=["A. Can you help me, please?　B. Give me the book!　C. I want the book."]),
   Q(5,"你想表达「他的书包是蓝色的」，应该说：________",3, opts=["A. His schoolbag is blue.　B. Her schoolbag is blue.　C. His schoolbag is blue?"]),
 ]},
 {"name":"六、连词成句（注意大小写和标点）（15分）","questions":[
   Q(1,"is / This / classroom / my / .",3, blanks=1),
   Q(2,"is / Where / book / my / ?",3, blanks=1),
   Q(3,"has / She / hair / long / .",3, blanks=1),
   Q(4,"many / How / books / do / you / have / ?",3, blanks=1),
   Q(5,"Let's / classroom / the / clean / !",3, blanks=1),
 ]},
 {"name":"七、阅读理解（判断正误，正确写T，错误写F）（20分）","questions":[
   Q(1,"阅读短文，判断下列句子正（T）误（F）。",20, blanks=5,
     opts=["　　Hello! I'm Amy. I have a new classroom. It's big and bright. There are forty desks and chairs in it. The blackboard is black. The window is big. I like my classroom very much. My desk is near the window. I have a new friend. Her name is Sarah. She is tall and thin. She has long hair.",
           "（1）Amy has a new classroom.（　）",
           "（2）There are thirty desks in the classroom.（　）",
           "（3）Amy's desk is near the window.（　）",
           "（4）Sarah is tall and thin.（　）",
           "（5）Sarah has short hair.（　）"]),
 ]},
]
a = [
 A(1,"S", "a在开音节中读/eɪ/。"),
 A(2,"S", "a在闭音节中读/æ/。"),
 A(3,"S", "i在开音节中读/aɪ/。"),
 A(4,"S", "i在闭音节中读/ɪ/。"),
 A(5,"S", "o在开音节中读/əʊ/。"),
 A(1,"A B C D E", "classroom教室、window窗户、blackboard黑板、light灯、door门。"),
 A(2,"A B C D E", "schoolbag书包、notebook笔记本、storybook故事书、maths book数学书、English book英语书。"),
 A(1,"C", "red是颜色，其余是教室设施。"),
 A(2,"C", "strong是形容词，其余是书。"),
 A(3,"C", "light是名词，其余是形容词。"),
 A(4,"C", "hair是身体部位，其余是家具。"),
 A(5,"C", "long是形容词，其余是代词。"),
 A(1,"A", "单数book用It's。"),
 A(2,"A", "What's in the classroom 回答具体物品。"),
 A(3,"A", "Let's后接动词原形。"),
 A(4,"A", "问人用Who。"),
 A(5,"A", "hair前用形容词long。"),
 A(6,"A", "He用has。"),
 A(7,"A", "How many答数量。"),
 A(8,"A", "She用is。"),
 A(9,"A", "Is this...? 肯定答Yes, it is。"),
 A(10,"A", "Let me后接动词原形。"),
 A(1,"A", "询问他人用Who is...。"),
 A(2,"A", "提议用Let's...。"),
 A(3,"A", "He is tall and strong。"),
 A(4,"A", "礼貌请求用Can you help me, please。"),
 A(5,"A", "形容男性的His。"),
 A(1,"This is my classroom.", "注意语序与句号。"),
 A(2,"Where is my book?", "疑问词Where句首大写。"),
 A(3,"She has long hair.", "注意语序。"),
 A(4,"How many books do you have?", "How many + 复数名词。"),
 A(5,"Let's clean the classroom!", "祈使句用感叹号。"),
 A(1,"（1）T；（2）F（forty）；（3）T；（4）T；（5）F（long hair）", "逐句对照短文。"),
]
out.append(save(m, p, a, "期末质量检测A卷")); print("英语A卷完成")

# ================= B卷 =================
m = base("四年级英语", "上学期期末学业水平测试", "（人教版PEP　三年级起点　2025—2026学年　第一学期）")
p = [
 {"name":"一、判断下列单词划线部分读音是否相同（相同写S，不同写D）（10分）","questions":[
   Q(1,"（　）like　kite",2), Q(2,"（　）big　pig",2), Q(3,"（　）cute　tube",2),
   Q(4,"（　）bus　cut",2), Q(5,"（　）he　these",2),
 ]},
 {"name":"二、看图选词（10分）","questions":[
   Q(1,"朋友外貌：friend（　）　tall（　）　thin（　）　strong（　）　quiet（　）",5,
     opts=["A. 朋友　B. 高的　C. 瘦的　D. 强壮的　E. 安静的"], blanks=5),
   Q(2,"家庭成员：parents（　）　uncle（　）　aunt（　）　cousin（　）　baby（　）",5,
     opts=["A. 父母　B. 叔叔/舅舅　C. 姑姑/姨　D. 堂/表兄弟姐妹　E. 婴儿"], blanks=5),
 ]},
 {"name":"三、选出不同类的一项（10分）","questions":[
   Q(1,"（　）",2, opts=["A. tall　B. thin　C. desk"]),
   Q(2,"（　）",2, opts=["A. uncle　B. aunt　C. light"]),
   Q(3,"（　）",2, opts=["A. quiet　B. friendly　C. window"]),
   Q(4,"（　）",2, opts=["A. he　B. she　C. his"]),
   Q(5,"（　）",2, opts=["A. parents　B. friends　C. teacher"]),
 ]},
 {"name":"四、单项选择（20分）","questions":[
   Q(1,"—— Who's that man?　—— ________ my uncle.",2, opts=["A. He's　B. She's　C. It's"]),
   Q(2,"—— Is she your aunt?　—— No, ________.",2, opts=["A. she isn't　B. she is　C. he isn't"]),
   Q(3,"My friend ________ a big nose.",2, opts=["A. has　B. have　C. is"]),
   Q(4,"How many people ________ in your family?",2, opts=["A. are there　B. is there　C. have"]),
   Q(5,"—— What's your father's job?　—— He is a ________.",2, opts=["A. doctor　B. tall　C. friendly"]),
   Q(6,"These ________ my parents.",2, opts=["A. are　B. is　C. am"]),
   Q(7,"—— How many ________ ?　—— Five.",2, opts=["A. people　B. peoples　C. a people"]),
   Q(8,"She ________ quiet.",2, opts=["A. is　B. are　C. has"]),
   Q(9,"Come ________ meet my family!",2, opts=["A. and　B. or　C. but"]),
   Q(10,"—— ____________ ? —— He's my brother.",2, opts=["A. Who's he　B. Who's she　C. What's he"]),
 ]},
 {"name":"五、情景选择（15分）","questions":[
   Q(1,"你想介绍「这是我的妈妈」，应该说：________",3, opts=["A. This is my mother.　B. She is my mother?　C. My mother is here."]),
   Q(2,"你想知道对方家里有几口人，应该问：________",3, opts=["A. How many people are there in your family?　B. How are you?　C. Where is your family?"]),
   Q(3,"你想问「你爸爸是做什么的」，应该说：________",3, opts=["A. What's your father's job?　B. Who's your father?　C. Where is your father?"]),
   Q(4,"你想说「我家有四口人」，应该说：________",3, opts=["A. There are four people in my family.　B. I have four families.　C. My family is four."]),
   Q(5,"别人向你介绍他的家人，你应该礼貌地说：________",3, opts=["A. Nice to meet you.　B. Goodbye.　C. Sorry."]),
 ]},
 {"name":"六、连词成句（15分）","questions":[
   Q(1,"is / This / family / my / .",3, blanks=1),
   Q(2,"many / How / people / there / are / ?",3, blanks=1),
   Q(3,"has / He / hair / short / .",3, blanks=1),
   Q(4,"is / job / What / your / father's / ?",3, blanks=1),
   Q(5,"my / These / are / parents / .",3, blanks=1),
 ]},
 {"name":"七、阅读理解（判断正误，正确写T，错误写F）（20分）","questions":[
   Q(1,"阅读短文，判断下列句子正（T）误（F）。",20, blanks=5,
     opts=["　　Hello! I'm Mike. Come and meet my family! My family has six people. My grandpa is a farmer. My grandma is a teacher. My father is a doctor. My mother is a nurse. I have a sister. She is a student. I love my family.",
           "（1）Mike's family has six people.（　）",
           "（2）Mike's grandpa is a teacher.（　）",
           "（3）Mike's father is a doctor.（　）",
           "（4）Mike's mother is a farmer.（　）",
           "（5）Mike has a sister.（　）"]),
 ]},
]
a2 = [
 A(1,"S", "i在开音节中读/aɪ/。"),
 A(2,"S", "i在闭音节中读/ɪ/。"),
 A(3,"S", "u在开音节中读/juː/。"),
 A(4,"S", "u在闭音节中读/ʌ/。"),
 A(5,"S", "e在开音节中读/iː/。"),
 A(1,"A B C D E", "friend朋友、tall高、thin瘦、strong强壮、quiet安静。"),
 A(2,"A B C D E", "parents父母、uncle叔叔、aunt姑姑、cousin堂表兄弟姐妹、baby婴儿。"),
 A(1,"C", "desk是家具，其余是形容词。"),
 A(2,"C", "light是物品，其余是家人称谓。"),
 A(3,"C", "window是物品，其余是形容词。"),
 A(4,"C", "his是物主代词，其余是人称代词。"),
 A(5,"C", "teacher是单数，其余是复数。"),
 A(1,"A", "男性用He's。"),
 A(2,"A", "否定答No, she isn't。"),
 A(3,"A", "My friend用has。"),
 A(4,"A", "How many people are there。"),
 A(5,"A", "问职业答职业名词。"),
 A(6,"A", "These用are。"),
 A(7,"A", "people单复数同形。"),
 A(8,"A", "quiet前用is。"),
 A(9,"A", "Come and meet用and。"),
 A(10,"A", "男性提问用Who's he。"),
 A(1,"A", "介绍他人用This is...。"),
 A(2,"A", "询问人口用How many people are there。"),
 A(3,"A", "询问职业用What's... job。"),
 A(4,"A", "There are four people in my family。"),
 A(5,"A", "初次见面说Nice to meet you。"),
 A(1,"This is my family.", "注意语序与句号。"),
 A(2,"How many people are there?", "How many + 复数名词。"),
 A(3,"He has short hair.", "注意语序。"),
 A(4,"What is your father's job?", "疑问词句首大写。"),
 A(5,"These are my parents.", "These用are。"),
 A(1,"（1）T；（2）F（farmer）；（3）T；（4）F（nurse）；（5）T", "逐句对照短文。"),
]
out.append(save(m, p, a2, "学业水平测试B卷")); print("英语B卷完成")

# ================= C卷 =================
m = base("四年级英语", "下学期期末综合检测", "（人教版PEP　三年级起点　2025—2026学年　第二学期）")
p = [
 {"name":"一、判断下列单词划线部分读音是否相同（相同写S，不同写D）（10分）","questions":[
   Q(1,"（　）car　farm",2), Q(2,"（　）for　horse",2), Q(3,"（　）her　bird",2),
   Q(4,"（　）nurse　hurt",2), Q(5,"（　）apple　cat",2),
 ]},
 {"name":"二、看图选词（10分）","questions":[
   Q(1,"食物：beef（　）　chicken（　）　noodles（　）　soup（　）　vegetable（　）",5,
     opts=["A. 牛肉　B. 鸡肉　C. 面条　D. 汤　E. 蔬菜"], blanks=5),
   Q(2,"餐具：knife（　）　fork（　）　chopsticks（　）　spoon（　）　bowl（　）",5,
     opts=["A. 刀　B. 叉子　C. 筷子　D. 勺子　E. 碗"], blanks=5),
 ]},
 {"name":"三、选出不同类的一项（10分）","questions":[
   Q(1,"（　）",2, opts=["A. beef　B. chicken　C. knife"]),
   Q(2,"（　）",2, opts=["A. fork　B. spoon　C. soup"]),
   Q(3,"（　）",2, opts=["A. noodles　B. rice　C. horse"]),
   Q(4,"（　）",2, opts=["A. bedroom　B. kitchen　C. vegetable"]),
   Q(5,"（　）",2, opts=["A. parents　B. fridge　C. phone"]),
 ]},
 {"name":"四、单项选择（20分）","questions":[
   Q(1,"—— What would you like?　—— ________ like some noodles.",2, opts=["A. I'd　B. I　C. I'm"]),
   Q(2,"—— Can I have some soup?　—— ________",2, opts=["A. Sure. Here you are.　B. I'm fine.　C. Goodbye."]),
   Q(3,"I'd like ________ beef.",2, opts=["A. some　B. a　C. an"]),
   Q(4,"—— What's for dinner?　—— ________.",2, opts=["A. Some rice and fish.　B. It's red.　C. Yes, please."]),
   Q(5,"—— How much is it?　—— ________ ten yuan.",2, opts=["A. It's　B. They're　C. Is"]),
   Q(6,"We ________ a new fridge.",2, opts=["A. have　B. has　C. is"]),
   Q(7,"—— Where is the cat?　—— ________ under the chair.",2, opts=["A. It's　B. They're　C. Is"]),
   Q(8,"________ are my glasses?",2, opts=["A. Where　B. What　C. Who"]),
   Q(9,"Dinner ________ ready!",2, opts=["A. is　B. are　C. am"]),
   Q(10,"Help ________ , please.",2, opts=["A. yourself　B. you　C. your"]),
 ]},
 {"name":"五、情景选择（15分）","questions":[
   Q(1,"你想请客人随便吃，应该说：________",3, opts=["A. Help yourself, please.　B. Give me your hand.　C. You are hungry."]),
   Q(2,"服务员问你要吃什么，你应该回答：________",3, opts=["A. I'd like some chicken, please.　B. I'm fine.　C. It's a chicken."]),
   Q(3,"你想知道某件东西多少钱，应该问：________",3, opts=["A. How much is it?　B. How many is it?　C. What is it?"]),
   Q(4,"你想说「晚餐准备好了」，应该说：________",3, opts=["A. Dinner is ready!　B. Dinner is nice.　C. I like dinner."]),
   Q(5,"你想问「你能帮我吗」，应该礼貌地说：________",3, opts=["A. Can you help me, please?　B. Give me a hand!　C. You must help me."]),
 ]},
 {"name":"六、连词成句（15分）","questions":[
   Q(1,"like / would / I / soup / some / .",3, blanks=1),
   Q(2,"I / soup / have / Can / some / ?",3, blanks=1),
   Q(3,"is / the / Where / cat / ?",3, blanks=1),
   Q(4,"a / We / fridge / new / have / .",3, blanks=1),
   Q(5,"like / What / you / would / ?",3, blanks=1),
 ]},
 {"name":"七、阅读理解（判断正误，正确写T，错误写F）（20分）","questions":[
   Q(1,"阅读短文，判断下列句子正（T）误（F）。",20, blanks=5,
     opts=["　　Hello! I'm Kate. This is my home. We have a new house. There are six rooms. There is a living room, a kitchen, two bedrooms, a study and a bathroom. My bedroom is nice. There is a bed, a desk and a computer in it. I like my home.",
           "（1）Kate has a new house.（　）",
           "（2）There are five rooms in the house.（　）",
           "（3）There are two bedrooms.（　）",
           "（4）Kate's bedroom has a computer.（　）",
           "（5）Kate doesn't like her home.（　）"]),
 ]},
]
a3 = [
 A(1,"S", "ar读/ɑː/。"),
 A(2,"S", "or读/ɔː/。"),
 A(3,"S", "er/ir都读/ɜː/。"),
 A(4,"S", "ur读/ɜː/。"),
 A(5,"S", "a在闭音节读/æ/。"),
 A(1,"A B C D E", "beef牛肉、chicken鸡肉、noodles面条、soup汤、vegetable蔬菜。"),
 A(2,"A B C D E", "knife刀、fork叉、chopsticks筷子、spoon勺子、bowl碗。"),
 A(1,"C", "knife是餐具，其余是食物。"),
 A(2,"C", "soup是食物，其余是餐具。"),
 A(3,"C", "horse是动物，其余是食物。"),
 A(4,"C", "vegetable是食物，其余是房间。"),
 A(5,"A", "parents是家人，其余是物品。"),
 A(1,"A", "I'd like缩写。"),
 A(2,"A", "Can I have 的应答。"),
 A(3,"A", "beef不可数用some。"),
 A(4,"A", "问晚餐答食物。"),
 A(5,"A", "单数It's ten yuan。"),
 A(6,"A", "We用have。"),
 A(7,"A", "cat单数用It's。"),
 A(8,"A", "询问位置用Where。"),
 A(9,"A", "Dinner用is。"),
 A(10,"A", "Help yourself是固定搭配。"),
 A(1,"A", "请人自便用Help yourself。"),
 A(2,"A", "点餐用I'd like...。"),
 A(3,"A", "询问价格用How much。"),
 A(4,"A", "Dinner is ready。"),
 A(5,"A", "礼貌请求用Can you help me。"),
 A(1,"I would like some soup.", "注意语序与句号。"),
 A(2,"Can I have some soup?", "情态动词开头。"),
 A(3,"Where is the cat?", "疑问词句首大写。"),
 A(4,"We have a new fridge.", "注意语序。"),
 A(5,"What would you like?", "疑问句首词大写。"),
 A(1,"（1）T；（2）F（six）；（3）T；（4）T；（5）F", "逐句对照短文。"),
]
out.append(save(m, p, a3, "综合检测C卷")); print("英语C卷完成")

# ================= D卷 =================
m = base("四年级英语", "期末复习质量检测", "（人教版PEP　三年级起点　2025—2026学年　第二学期）")
p = [
 {"name":"一、判断下列单词划线部分读音是否相同（相同写S，不同写D）（10分）","questions":[
   Q(1,"（　）red　bed",2), Q(2,"（　）he　pen",2), Q(3,"（　）hot　dog",2),
   Q(4,"（　）milk　kite",2), Q(5,"（　）blue　bus",2),
 ]},
 {"name":"二、看图选词（10分）","questions":[
   Q(1,"天气：cold（　）　cool（　）　warm（　）　hot（　）　sunny（　）",5,
     opts=["A. 冷的　B. 凉的　C. 温暖的　D. 热的　E. 晴朗的"], blanks=5),
   Q(2,"衣着：coat（　）　sweater（　）　jacket（　）　dress（　）　shirt（　）",5,
     opts=["A. 外套　B. 毛衣　C. 夹克　D. 连衣裙　E. 衬衫"], blanks=5),
 ]},
 {"name":"三、选出不同类的一项（10分）","questions":[
   Q(1,"（　）",2, opts=["A. cold　B. hot　C. coat"]),
   Q(2,"（　）",2, opts=["A. sweater　B. jacket　C. sunny"]),
   Q(3,"（　）",2, opts=["A. rainy　B. windy　C. dress"]),
   Q(4,"（　）",2, opts=["A. warm　B. cool　C. coat"]),
   Q(5,"（　）",2, opts=["A. shirt　B. skirt　C. snowy"]),
 ]},
 {"name":"四、单项选择（20分）","questions":[
   Q(1,"—— What's the weather like today?　—— ________.",2, opts=["A. It's sunny.　B. It's a coat.　C. Yes, it is."]),
   Q(2,"—— Can I wear my new shirt today?　—— ________",2, opts=["A. Yes, you can.　B. Yes, I can.　C. No, I can't."]),
   Q(3,"It's cold ________.",2, opts=["A. today　B. tomorrow?　C. yesterday"]),
   Q(4,"—— What are you doing?　—— I'm ________.",2, opts=["A. reading　B. read　C. reads"]),
   Q(5,"Take ________ umbrella, please.",2, opts=["A. an　B. a　C. the"]),
   Q(6,"—— How's the weather in Beijing?　—— ________",2, opts=["A. It's windy.　B. It's a coat.　C. I'm fine."]),
   Q(7,"It's ________ today. Put on your coat.",2, opts=["A. cold　B. hot　C. sunny"]),
   Q(8,"—— ________ is the weather? —— It's rainy.",2, opts=["A. How　B. What　C. Where"]),
   Q(9,"These ________ my new shoes.",2, opts=["A. are　B. is　C. am"]),
   Q(10,"—— Are these your pants?　—— Yes, ________.",2, opts=["A. they are　B. it is　C. I am"]),
 ]},
 {"name":"五、情景选择（15分）","questions":[
   Q(1,"你想知道今天的天气怎么样，应该问：________",3, opts=["A. What's the weather like today?　B. How are you today?　C. What's this?"]),
   Q(2,"天气很冷，你提醒朋友穿外套，应该说：________",3, opts=["A. It's cold. Put on your coat.　B. It's hot. Take off your coat.　C. It's sunny. Let's go."]),
   Q(3,"你想说「今天我能穿我的新衬衫吗」，应该说：________",3, opts=["A. Can I wear my new shirt today?　B. I like my new shirt.　C. My shirt is new."]),
   Q(4,"外面下雨了，你提醒朋友带伞，应该说：________",3, opts=["A. It's rainy. Take an umbrella.　B. It's sunny. Let's play.　C. It's cold. Wear a coat."]),
   Q(5,"你正在读书，别人问你在做什么，你应该回答：________",3, opts=["A. I'm reading.　B. I read a book.　C. I like reading."]),
 ]},
 {"name":"六、连词成句（15分）","questions":[
   Q(1,"weather / like / What's / the / ?",3, blanks=1),
   Q(2,"cold / It's / today / .",3, blanks=1),
   Q(3,"wear / Can / shirt / I / my / ?",3, blanks=1),
   Q(4,"are / doing / What / you / ?",3, blanks=1),
   Q(5,"an / Take / umbrella / .",3, blanks=1),
 ]},
 {"name":"七、阅读理解（判断正误，正确写T，错误写F）（20分）","questions":[
   Q(1,"阅读短文，判断下列句子正（T）误（F）。",20, blanks=5,
     opts=["　　Good morning! This is the weather report. It's cold and snowy in Harbin. It's windy in Beijing. It's sunny and warm in Sanya. It's rainy in Shanghai. Please take an umbrella in Shanghai. Thank you for watching.",
           "（1）It's cold and snowy in Harbin.（　）",
           "（2）It's sunny in Beijing.（　）",
           "（3）It's sunny and warm in Sanya.（　）",
           "（4）It's rainy in Shanghai.（　）",
           "（5）You need an umbrella in Harbin.（　）"]),
 ]},
]
a4 = [
 A(1,"S", "e在闭音节读/e/。"),
 A(2,"D", "he中e读/iː/，pen中e读/e/。"),
 A(3,"S", "o在闭音节读/ɒ/。"),
 A(4,"D", "milk中i读/ɪ/，kite中i读/aɪ/。"),
 A(5,"D", "blue中u读/uː/，bus中u读/ʌ/。"),
 A(1,"A B C D E", "cold冷、cool凉、warm温暖、hot热、sunny晴朗。"),
 A(2,"A B C D E", "coat外套、sweater毛衣、jacket夹克、dress连衣裙、shirt衬衫。"),
 A(1,"C", "coat是衣物，其余是天气。"),
 A(2,"C", "sunny是天气，其余是衣物。"),
 A(3,"C", "dress是衣物，其余是天气。"),
 A(4,"C", "coat是衣物，其余是天气。"),
 A(5,"C", "snowy是天气，其余是衣物。"),
 A(1,"A", "问天气答天气。"),
 A(2,"A", "Can I...? 问「我」，答「你」，用Yes, you can。"),
 A(3,"A", "today今天。"),
 A(4,"A", "现在进行时用reading。"),
 A(5,"A", "umbrella元音开头用an。"),
 A(6,"A", "问天气答天气。"),
 A(7,"A", "穿外套说明天冷。"),
 A(8,"A", "How is the weather? 固定问法。"),
 A(9,"A", "These用are。"),
 A(10,"A", "Are these...? 答Yes, they are。"),
 A(1,"A", "询问天气用What's the weather like。"),
 A(2,"A", "冷天提醒穿外套。"),
 A(3,"A", "Can I wear...。"),
 A(4,"A", "雨天提醒带伞。"),
 A(5,"A", "现在进行时答I'm reading。"),
 A(1,"What's the weather like?", "注意语序与问号。"),
 A(2,"It's cold today.", "It指代天气。"),
 A(3,"Can I wear my shirt?", "情态动词句首大写。"),
 A(4,"What are you doing?", "现在进行时问句。"),
 A(5,"Take an umbrella.", "祈使句。"),
 A(1,"（1）T；（2）F（windy）；（3）T；（4）T；（5）F（Shanghai）", "逐句对照短文。"),
]
out.append(save(m, p, a4, "复习质量检测D卷")); print("英语D卷完成")

# ================= E卷 =================
m = base("四年级英语", "期末学业质量监测", "（人教版PEP　三年级起点　2025—2026学年　全学年）")
p = [
 {"name":"一、判断下列单词划线部分读音是否相同（相同写S，不同写D）（10分）","questions":[
   Q(1,"（　）cake　name",2), Q(2,"（　）bike　pig",2), Q(3,"（　）nose　box",2),
   Q(4,"（　）cute　bus",2), Q(5,"（　）three　see",2),
 ]},
 {"name":"二、看图选词（10分）","questions":[
   Q(1,"农场动物：horse（　）　cow（　）　sheep（　）　hen（　）　goat（　）",5,
     opts=["A. 马　B. 奶牛　C. 绵羊　D. 母鸡　E. 山羊"], blanks=5),
   Q(2,"蔬菜：tomato（　）　potato（　）　carrot（　）　onion（　）　green beans（　）",5,
     opts=["A. 西红柿　B. 土豆　C. 胡萝卜　D. 洋葱　E. 豆角"], blanks=5),
 ]},
 {"name":"三、选出不同类的一项（10分）","questions":[
   Q(1,"（　）",2, opts=["A. horse　B. cow　C. tomato"]),
   Q(2,"（　）",2, opts=["A. potato　B. carrot　C. sheep"]),
   Q(3,"（　）",2, opts=["A. hen　B. goat　C. onion"]),
   Q(4,"（　）",2, opts=["A. blackboard　B. window　C. animal"]),
   Q(5,"（　）",2, opts=["A. he　B. his　C. she"]),
 ]},
 {"name":"四、单项选择（20分）","questions":[
   Q(1,"—— What are these?　—— ________ horses.",2, opts=["A. They're　B. It's　C. Is"]),
   Q(2,"—— How many horses are there?　—— ________ twelve.",2, opts=["A. There are　B. There is　C. It is"]),
   Q(3,"—— Are these tomatoes?　—— Yes, ________.",2, opts=["A. they are　B. it is　C. I am"]),
   Q(4,"Are ________ carrots?",2, opts=["A. these　B. this　C. it"]),
   Q(5,"—— What are those?　—— They ________ goats.",2, opts=["A. are　B. is　C. am"]),
   Q(6,"I'd like some ________, please.",2, opts=["A. potatoes　B. potato　C. a potato"]),
   Q(7,"—— How many ________ do you have? —— Six.",2, opts=["A. sheep　B. sheeps　C. a sheep"]),
   Q(8,"The ________ is white and black.",2, opts=["A. cow　B. cows　C. a cow"]),
   Q(9,"—— ________ are they? —— They are on the farm.",2, opts=["A. Where　B. What　C. Who"]),
   Q(10,"Are these ________ ?",2, opts=["A. green beans　B. a green bean　C. green bean"]),
 ]},
 {"name":"五、情景选择（15分）","questions":[
   Q(1,"你想问「这些是什么」，应该说：________",3, opts=["A. What are these?　B. What is this?　C. Where are these?"]),
   Q(2,"你想知道农场上有多少只羊，应该问：________",3, opts=["A. How many sheep are there?　B. How many sheeps?　C. What are the sheep?"]),
   Q(3,"你想说「这些是土豆」，应该说：________",3, opts=["A. These are potatoes.　B. This is a potato.　C. These is a potato."]),
   Q(4,"你想确认「那些是山羊吗」，应该说：________",3, opts=["A. Are those goats?　B. Is that a goat?　C. What are those?"]),
   Q(5,"你想表达「我想要一些蔬菜」，应该说：________",3, opts=["A. I'd like some vegetables.　B. I like vegetable.　C. I have vegetables."]),
 ]},
 {"name":"六、连词成句（15分）","questions":[
   Q(1,"are / What / these / ?",3, blanks=1),
   Q(2,"many / How / horses / are / there / ?",3, blanks=1),
   Q(3,"are / These / potatoes / .",3, blanks=1),
   Q(4,"le / would / some / I / carrots / .",3, blanks=1),
   Q(5,"those / Are / goats / ?",3, blanks=1),
 ]},
 {"name":"七、阅读理解（判断正误，正确写T，错误写F）（20分）","questions":[
   Q(1,"阅读短文，判断下列句子正（T）误（F）。",20, blanks=5,
     opts=["　　Welcome to my grandpa's farm! It's very big. There are many animals on the farm. There are ten cows, twelve sheep and twenty hens. There are also some ducks. Look! These are tomatoes and potatoes. Those are carrots and green beans. I like the farm.",
           "（1）Grandpa's farm is very big.（　）",
           "（2）There are ten sheep on the farm.（　）",
           "（3）There are twenty hens on the farm.（　）",
           "（4）There are some ducks on the farm.（　）",
           "（5）These are tomatoes and potatoes.（　）"]),
 ]},
]
a5 = [
 A(1,"S", "a在开音节读/eɪ/。"),
 A(2,"D", "bike中i读/aɪ/，pig中i读/ɪ/。"),
 A(3,"D", "nose中o读/əʊ/，box中o读/ɒ/。"),
 A(4,"D", "cute中u读/juː/，bus中u读/ʌ/。"),
 A(5,"S", "ee读/iː/。"),
 A(1,"A B C D E", "horse马、cow奶牛、sheep绵羊、hen母鸡、goat山羊。"),
 A(2,"A B C D E", "tomato西红柿、potato土豆、carrot胡萝卜、onion洋葱、green beans豆角。"),
 A(1,"C", "tomato是蔬菜，其余是动物。"),
 A(2,"C", "sheep是动物，其余是蔬菜。"),
 A(3,"C", "onion是蔬菜，其余是动物。"),
 A(4,"C", "animal是动物，其余是教室设施。"),
 A(5,"B", "his是物主代词，其余是人称代词。"),
 A(1,"A", "复数用They're。"),
 A(2,"A", "复数用There are。"),
 A(3,"A", "Are these...? 答Yes, they are。"),
 A(4,"A", "复数指示代词用these。"),
 A(5,"A", "They用are。"),
 A(6,"A", "some后接可数名词复数。"),
 A(7,"A", "sheep单复数同形。"),
 A(8,"A", "单数The cow用is。"),
 A(9,"A", "询问位置用Where。"),
 A(10,"A", "green beans用复数。"),
 A(1,"A", "复数提问用What are these。"),
 A(2,"A", "How many sheep are there。"),
 A(3,"A", "复数用These are potatoes。"),
 A(4,"A", "确认那些用Are those...。"),
 A(5,"A", "想要蔬菜用I'd like some vegetables。"),
 A(1,"What are these?", "疑问词句首大写，句末问号。"),
 A(2,"How many horses are there?", "How many + 复数名词。"),
 A(3,"These are potatoes.", "注意语序与句号。"),
 A(4,"I would like some carrots.", "注意语序。"),
 A(5,"Are those goats?", "一般疑问句句首大写。"),
 A(1,"（1）T；（2）F（twelve）；（3）T；（4）T；（5）T", "逐句对照短文。"),
]
out.append(save(m, p, a5, "学业质量监测E卷")); print("英语E卷完成")

for f in out:
    print("已生成:", f)
