# -*- coding: utf-8 -*-
"""三年级 英语（人教版PEP）期末试卷（5套）"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from paper_common import save, base, Q, A
out = []

# ================= A卷 =================
m = base("三年级英语", "第一学期期末质量检测", "（人教版PEP　三年级起点　2025—2026学年　第一学期）")
p = [
 {"name":"一、写出下列字母的大写或小写形式（10分）","questions":[
   Q(1,"A（　）　b（　）　D（　）　e（　）　G（　）　h（　）　J（　）　k（　）　M（　）　n（　）",10, blanks=10),
 ]},
 {"name":"二、按字母表顺序排列下列字母（5分）","questions":[
   Q(1,"d　f　b　e　c　→ ＿＿＿＿＿＿＿＿＿",5, blanks=1),
 ]},
 {"name":"三、看图选词（将正确答案的序号填在括号里）（10分）","questions":[
   Q(1,"文具类：pen（　）　ruler（　）　eraser（　）　crayon（　）　book（　）",5, opts=["A. 铅笔　B. 直尺　C. 橡皮　D. 蜡笔　E. 书"], blanks=5),
   Q(2,"颜色类：red（　）　blue（　）　green（　）　yellow（　）　black（　）",5, opts=["A. 红色　B. 蓝色　C. 绿色　D. 黄色　E. 黑色"], blanks=5),
 ]},
 {"name":"四、选出不同类的一项（10分）","questions":[
   Q(1,"（　）",2, opts=["A. pen　B. ruler　C. red"]),
   Q(2,"（　）",2, opts=["A. cat　B. dog　C. book"]),
   Q(3,"（　）",2, opts=["A. head　B. arm　C. black"]),
   Q(4,"（　）",2, opts=["A. one　B. three　C. bird"]),
   Q(5,"（　）",2, opts=["A. father　B. mum　C. milk"]),
 ]},
 {"name":"五、单项选择（20分）","questions":[
   Q(1,"—— Hello! What's your name?　—— ________",2, opts=["A. I'm fine.　B. My name is Amy.　C. Goodbye."]),
   Q(2,"—— Good morning!　—— ________",2, opts=["A. Good morning!　B. Good night!　C. Thank you."]),
   Q(3,"—— What's this?　—— ________ a pen.",2, opts=["A. It's　B. This　C. That"]),
   Q(4,"This is ________ apple.",2, opts=["A. a　B. an　C. the"]),
   Q(5,"—— How many books?　—— ________",2, opts=["A. Three.　B. Red.　C. Yes."]),
   Q(6,"—— How old are you?　—— ________",2, opts=["A. I'm nine.　B. Nine books.　C. Fine, thanks."]),
   Q(7,"—— Nice to meet you.　—— ________",2, opts=["A. Nice to meet you, too.　B. I'm nine.　C. Goodbye."]),
   Q(8,"Let's ________ to school!",2, opts=["A. go　B. goes　C. going"]),
   Q(9,"—— What colour is it?　—— It's ________.",2, opts=["A. a ruler　B. blue　C. three"]),
   Q(10,"—— May I have a look?　—— ________",2, opts=["A. Sure. Here you are.　B. I'm sorry.　C. Goodbye."]),
 ]},
 {"name":"六、情景选择（15分）","questions":[
   Q(1,"早上见到老师，你应该说：________",3, opts=["A. Good morning!　B. Good night!　C. Goodbye!"]),
   Q(2,"你想知道对方的名字，应该问：________",3, opts=["A. How are you?　B. What's your name?　C. How old are you?"]),
   Q(3,"别人帮了你，你应该说：________",3, opts=["A. Thank you.　B. Sorry.　C. Here you are."]),
   Q(4,"你想邀请同学一起去公园，应该说：________",3, opts=["A. Let's go to the park!　B. I like the park.　C. It's a park."]),
   Q(5,"你想看别人的东西，应该礼貌地问：________",3, opts=["A. May I have a look?　B. Give me!　C. It's mine."]),
 ]},
 {"name":"七、连词成句（注意大小写和标点）（15分）","questions":[
   Q(1,"is / This / my / pen / . → ＿＿＿＿＿＿＿＿＿＿",3, blanks=1),
   Q(2,"your / What / is / name / ? → ＿＿＿＿＿＿＿＿＿＿",3, blanks=1),
   Q(3,"are / How / you / ? → ＿＿＿＿＿＿＿＿＿＿",3, blanks=1),
   Q(4,"like / I / bananas / . → ＿＿＿＿＿＿＿＿＿＿",3, blanks=1),
   Q(5,"to / Nice / meet / you / . → ＿＿＿＿＿＿＿＿＿＿",3, blanks=1),
 ]},
 {"name":"八、阅读理解（判断正误，正确写T，错误写F）（15分）","questions":[
   Q(1,"阅读短文，判断下列句子正（T）误（F）。",15, blanks=5,
     opts=["　　Hello! I'm Lily. I'm nine. This is my friend, Tom. He is ten. I have a red bag. Tom has a blue bag. We like apples and milk.",
           "（1）Lily is ten.（　）",
           "（2）Tom is Lily's friend.（　）",
           "（3）Lily's bag is blue.（　）",
           "（4）Tom has a blue bag.（　）",
           "（5）They like apples and milk.（　）"]),
 ]},
]
a = [
 A(1,"a；B；d；E；g；H；j；K；m；N", "注意字母占格与书写规范。"),
 A(1,"b c d e f", "按字母表顺序排列。"),
 A(1,"A B C D E", "pen铅笔、ruler直尺、eraser橡皮、crayon蜡笔、book书。"),
 A(2,"A B C D E", "red红、blue蓝、green绿、yellow黄、black黑。"),
 A(1,"C", "red是颜色，其余是文具。"),
 A(2,"C", "book是文具，其余是动物。"),
 A(3,"C", "black是颜色，其余是身体部位。"),
 A(4,"C", "bird是动物，其余是数字。"),
 A(5,"C", "milk是食物，其余是家人称谓。"),
 A(1,"B", "问名字答 My name is...。"),
 A(2,"A", "Good morning 对应 Good morning。"),
 A(3,"A", "It's a pen. 用 It's。"),
 A(4,"B", "apple 元音开头用 an。"),
 A(5,"A", "How many 回答数量。"),
 A(6,"A", "How old 回答年龄。"),
 A(7,"A", "Nice to meet you 的标准应答。"),
 A(8,"A", "Let's 后接动词原形。"),
 A(9,"B", "问颜色答颜色词。"),
 A(10,"A", "May I... 的礼貌应答。"),
 A(1,"A", "早上问候用 Good morning。"),
 A(2,"B", "询问名字用 What's your name。"),
 A(3,"A", "感谢用 Thank you。"),
 A(4,"A", "邀请用 Let's...。"),
 A(5,"A", "礼貌请求用 May I have a look。"),
 A(1,"This is my pen.", "句首字母大写，句末句号。"),
 A(2,"What is your name?", "疑问句句首 What 大写。"),
 A(3,"How are you?", "问候语。"),
 A(4,"I like bananas.", "主语 I 大写。"),
 A(5,"Nice to meet you.", "固定表达。"),
 A(1,"（1）F（nine）；（2）T；（3）F（red）；（4）T；（5）T", "仔细对照短文信息。"),
]
out.append(save(m, p, a, "期末质量检测A卷")); print("英语A卷完成")

# ================= B卷 =================
m = base("三年级英语", "上学期期末学业水平测试", "（人教版PEP　三年级起点　2025—2026学年　第一学期）")
p = [
 {"name":"一、写出下列字母的大写或小写形式（10分）","questions":[
   Q(1,"B（　）　c（　）　F（　）　g（　）　I（　）　l（　）　O（　）　p（　）　R（　）　s（　）",10, blanks=10),
 ]},
 {"name":"二、按字母表顺序排列下列字母（5分）","questions":[
   Q(1,"h　j　g　k　i　→ ＿＿＿＿＿＿＿＿＿",5, blanks=1),
 ]},
 {"name":"三、看图选词（10分）","questions":[
   Q(1,"动物类：cat（　）　dog（　）　duck（　）　pig（　）　bird（　）",5, opts=["A. 猫　B. 狗　C. 鸭子　D. 猪　E. 鸟"], blanks=5),
   Q(2,"身体部位：head（　）　face（　）　eye（　）　ear（　）　nose（　）",5, opts=["A. 头　B. 脸　C. 眼睛　D. 耳朵　E. 鼻子"], blanks=5),
 ]},
 {"name":"四、选出不同类的一项（10分）","questions":[
   Q(1,"（　）",2, opts=["A. one　B. two　C. cat"]),
   Q(2,"（　）",2, opts=["A. red　B. blue　C. pen"]),
   Q(3,"（　）",2, opts=["A. arm　B. leg　C. yellow"]),
   Q(4,"（　）",2, opts=["A. bread　B. cake　C. dog"]),
   Q(5,"（　）",2, opts=["A. sister　B. brother　C. ruler"]),
 ]},
 {"name":"五、单项选择（20分）","questions":[
   Q(1,"—— How are you?　—— ________",2, opts=["A. I'm fine, thank you.　B. I'm nine.　C. My name is Amy."]),
   Q(2,"—— Good afternoon!　—— ________",2, opts=["A. Good afternoon!　B. Good morning!　C. Good evening!"]),
   Q(3,"—— What's that?　—— ________ an eraser.",2, opts=["A. It's　B. This　C. I'm"]),
   Q(4,"I have ________ orange.",2, opts=["A. a　B. an　C. the"]),
   Q(5,"—— How many pens?　—— ________",2, opts=["A. Five.　B. Blue.　C. Yes, I do."]),
   Q(6,"—— Let's paint!　—— ________",2, opts=["A. OK!　B. Thank you.　C. Goodbye."]),
   Q(7,"________ is my mother.",2, opts=["A. She　B. He　C. It"]),
   Q(8,"I ________ apples.",2, opts=["A. like　B. likes　C. liking"]),
   Q(9,"—— What colour is your bag?　—— It's ________.",2, opts=["A. green　B. a bag　C. nice"]),
   Q(10,"—— Thank you!　—— ________",2, opts=["A. You're welcome.　B. Sorry.　C. OK."]),
 ]},
 {"name":"六、情景选择（15分）","questions":[
   Q(1,"下午见到同学，你应该说：________",3, opts=["A. Good afternoon!　B. Good morning!　C. Good night!"]),
   Q(2,"你想知道对方的年龄，应该问：________",3, opts=["A. How old are you?　B. How are you?　C. What's your name?"]),
   Q(3,"你想表达「我喜欢熊猫」，应该说：________",3, opts=["A. I like pandas.　B. I like red.　C. I have a panda."]),
   Q(4,"你不小心撞到别人，应该说：________",3, opts=["A. Sorry.　B. Thank you.　C. Here you are."]),
   Q(5,"你想请别人看你的新书包，应该说：________",3, opts=["A. Look at my new bag!　B. Give me the bag.　C. It's a bag."]),
 ]},
 {"name":"七、连词成句（15分）","questions":[
   Q(1,"is / This / friend / my / . → ＿＿＿＿＿＿＿＿＿＿",3, blanks=1),
   Q(2,"old / How / you / are / ? → ＿＿＿＿＿＿＿＿＿＿",3, blanks=1),
   Q(3,"colour / What / it / is / ? → ＿＿＿＿＿＿＿＿＿＿",3, blanks=1),
   Q(4,"have / I / a / pencil / . → ＿＿＿＿＿＿＿＿＿＿",3, blanks=1),
   Q(5,"are / Here / you / . → ＿＿＿＿＿＿＿＿＿＿",3, blanks=1),
 ]},
 {"name":"八、阅读理解（判断正误，正确写T，错误写F）（15分）","questions":[
   Q(1,"阅读短文，判断下列句子正（T）误（F）。",15, blanks=5,
     opts=["　　Hi! I'm Mike. I'm eight. I have a dog. It's black and white. I like it very much. My sister is nine. She likes cats. We like bread and juice.",
           "（1）Mike is nine.（　）",
           "（2）Mike has a dog.（　）",
           "（3）The dog is black and white.（　）",
           "（4）Mike's sister likes dogs.（　）",
           "（5）They like bread and juice.（　）"]),
 ]},
]
a2 = [
 A(1,"b；C；f；G；i；L；o；P；r；S", "注意字母所占格位。"),
 A(1,"g h i j k", "按字母表顺序。"),
 A(1,"A B C D E", "cat猫、dog狗、duck鸭、pig猪、bird鸟。"),
 A(2,"A B C D E", "head头、face脸、eye眼睛、ear耳朵、nose鼻子。"),
 A(1,"C", "cat是动物，其余是数字。"),
 A(2,"C", "pen是文具，其余是颜色。"),
 A(3,"C", "yellow是颜色，其余是身体部位。"),
 A(4,"C", "dog是动物，其余是食物。"),
 A(5,"C", "ruler是文具，其余是家人称谓。"),
 A(1,"A", "How are you 的标准应答。"),
 A(2,"A", "Good afternoon 对应 Good afternoon。"),
 A(3,"A", "问 that 用 It's 回答。"),
 A(4,"B", "orange 元音开头用 an。"),
 A(5,"A", "How many 答数量。"),
 A(6,"A", "Let's... 的应答用 OK!。"),
 A(7,"A", "mother 用 She。"),
 A(8,"A", "主语 I 用动词原形 like。"),
 A(9,"A", "问颜色答颜色词。"),
 A(10,"A", "Thank you 的应答是 You're welcome。"),
 A(1,"A", "下午问候用 Good afternoon。"),
 A(2,"A", "问年龄用 How old are you。"),
 A(3,"A", "表达喜好用 I like...。"),
 A(4,"A", "道歉用 Sorry。"),
 A(5,"A", "请人看用 Look at...。"),
 A(1,"This is my friend.", "注意语序与句号。"),
 A(2,"How old are you?", "疑问句首词大写，句末问号。"),
 A(3,"What colour is it?", "固定问句。"),
 A(4,"I have a pencil.", "主谓宾顺序。"),
 A(5,"Here you are.", "固定表达，句末句号。"),
 A(1,"（1）F（eight）；（2）T；（3）T；（4）F（cats）；（5）T", "逐句对照短文。"),
]
out.append(save(m, p, a2, "学业水平测试B卷")); print("英语B卷完成")

# ================= C卷 =================
m = base("三年级英语", "下学期期末综合检测", "（人教版PEP　三年级起点　2025—2026学年　第二学期）")
p = [
 {"name":"一、写出下列字母的大写或小写形式（10分）","questions":[
   Q(1,"E（　）　f（　）　H（　）　i（　）　K（　）　m（　）　P（　）　q（　）　T（　）　u（　）",10, blanks=10),
 ]},
 {"name":"二、按字母表顺序排列下列字母（5分）","questions":[
   Q(1,"n　p　l　o　m　→ ＿＿＿＿＿＿＿＿＿",5, blanks=1),
 ]},
 {"name":"三、看图选词（10分）","questions":[
   Q(1,"食物类：bread（　）　cake（　）　rice（　）　egg（　）　fish（　）",5, opts=["A. 面包　B. 蛋糕　C. 米饭　D. 鸡蛋　E. 鱼"], blanks=5),
   Q(2,"家庭成员：father（　）　mother（　）　brother（　）　sister（　）　grandma（　）",5, opts=["A. 爸爸　B. 妈妈　C. 哥哥/弟弟　D. 姐姐/妹妹　E. 奶奶"], blanks=5),
 ]},
 {"name":"四、选出不同类的一项（10分）","questions":[
   Q(1,"（　）",2, opts=["A. rice　B. bread　C. head"]),
   Q(2,"（　）",2, opts=["A. father　B. mother　C. fish"]),
   Q(3,"（　）",2, opts=["A. eleven　B. twelve　C. green"]),
   Q(4,"（　）",2, opts=["A. duck　B. cake　C. bird"]),
   Q(5,"（　）",2, opts=["A. pencil　B. ruler　C. juice"]),
 ]},
 {"name":"五、单项选择（20分）","questions":[
   Q(1,"—— What would you like?　—— ________",2, opts=["A. I'd like some rice.　B. I'm nine.　C. It's red."]),
   Q(2,"—— Can I have some juice?　—— ________",2, opts=["A. Sure. Here you are.　B. I'm fine.　C. Goodbye."]),
   Q(3,"I like ________.",2, opts=["A. banana　B. bananas　C. a bananas"]),
   Q(4,"—— Who's that man?　—— ________ my father.",2, opts=["A. He's　B. She's　C. It's"]),
   Q(5,"—— How many cakes?　—— ________",2, opts=["A. Two.　B. Cake.　C. Orange."]),
   Q(6,"—— Happy birthday!　—— ________",2, opts=["A. Thank you!　B. Happy New Year!　C. Sorry."]),
   Q(7,"________ this your sister?",2, opts=["A. Is　B. Are　C. Am"]),
   Q(8,"Let's ________ the cake.",2, opts=["A. eat　B. eats　C. eating"]),
   Q(9,"—— Do you like fish?　—— Yes, I ________.",2, opts=["A. do　B. like　C. don't"]),
   Q(10,"—— Thank you very much.　—— ________",2, opts=["A. You're welcome.　B. Here you are.　C. Good.</br>"]),
 ]},
 {"name":"六、情景选择（15分）","questions":[
   Q(1,"你想问对方要不要吃点面包，应该说：________",3, opts=["A. Would you like some bread?　B. What's this?　C. How are you?"]),
   Q(2,"你在商店里想买果汁，应该礼貌地说：________",3, opts=["A. Can I have some juice, please?　B. I want juice!　C. Juice is nice."]),
   Q(3,"你想介绍自己的妈妈给别人，应该说：________",3, opts=["A. This is my mother.　B. My mother is here.　C. I have a mother."]),
   Q(4,"你想知道对方是否喜欢苹果，应该问：________",3, opts=["A. Do you like apples?　B. What colour is it?　C. How many apples?"]),
   Q(5,"别人祝你生日快乐，你应该说：________",3, opts=["A. Thank you!　B. Happy birthday!　C. You're welcome."]),
 ]},
 {"name":"七、连词成句（15分）","questions":[
   Q(1,"like / I / some / rice / would / . → ＿＿＿＿＿＿＿＿＿＿",3, blanks=1),
   Q(2,"you / Do / cats / like / ? → ＿＿＿＿＿＿＿＿＿＿",3, blanks=1),
   Q(3,"is / This / father / my / . → ＿＿＿＿＿＿＿＿＿＿",3, blanks=1),
   Q(4,"many / How / are / apples / there / ? → ＿＿＿＿＿＿＿＿＿＿",3, blanks=1),
   Q(5,"have / Can / I / some / juice / ? → ＿＿＿＿＿＿＿＿＿＿",3, blanks=1),
 ]},
 {"name":"八、阅读理解（判断正误，正确写T，错误写F）（15分）","questions":[
   Q(1,"阅读短文，判断下列句子正（T）误（F）。",15, blanks=5,
     opts=["　　Hello! I'm Sarah. I'm a girl. I have a happy family. My father is a teacher. My mother is a doctor. I have a brother. He is five. We like eggs and milk. My father likes rice.",
           "（1）Sarah is a boy.（　）",
           "（2）Sarah's father is a teacher.（　）",
           "（3）Sarah's mother is a doctor.（　）",
           "（4）Sarah has a sister.（　）",
           "（5）Sarah's father likes rice.（　）"]),
 ]},
]
a3 = [
 A(1,"e；F；h；I；k；M；p；Q；t；U", "注意大小写与占格。"),
 A(1,"l m n o p", "按字母表顺序。"),
 A(1,"A B C D E", "bread面包、cake蛋糕、rice米饭、egg鸡蛋、fish鱼。"),
 A(2,"A B C D E", "father爸爸、mother妈妈、brother兄弟、sister姐妹、grandma奶奶。"),
 A(1,"C", "head是身体部位，其余是食物。"),
 A(2,"C", "fish是食物，其余是家人称谓。"),
 A(3,"C", "green是颜色，其余是数字。"),
 A(4,"B", "cake是食物，其余是动物。"),
 A(5,"C", "juice是饮料，其余是文具。"),
 A(1,"A", "What would you like 回答 I'd like...。"),
 A(2,"A", "Can I have 的应答用 Sure. Here you are。"),
 A(3,"B", "喜欢某类事物用复数 bananas。"),
 A(4,"A", "man 用 He's。"),
 A(5,"A", "How many 答数量。"),
 A(6,"A", "生日祝福应答 Thank you。"),
 A(7,"A", "this 单数用 Is。"),
 A(8,"A", "Let's 后接动词原形。"),
 A(9,"A", "Do you...? 用 Yes, I do. 回答。"),
 A(10,"A", "Thank you 应答 You're welcome。"),
 A(1,"A", "询问是否需要用 Would you like...。"),
 A(2,"A", "礼貌购物用 Can I have..., please。"),
 A(3,"A", "介绍他人用 This is...。"),
 A(4,"A", "询问喜好用 Do you like...。"),
 A(5,"A", "接受祝福说 Thank you。"),
 A(1,"I would like some rice.", "注意语序与句号。"),
 A(2,"Do you like cats?", "助动词 Do 句首大写，句末问号。"),
 A(3,"This is my father.", "注意语序。"),
 A(4,"How many apples are there?", "How many + 复数名词。"),
 A(5,"Can I have some juice?", "情态动词 Can 句首大写。"),
 A(1,"（1）F（girl）；（2）T；（3）T；（4）F（brother）；（5）T", "逐句对照短文信息。"),
]
out.append(save(m, p, a3, "综合检测C卷")); print("英语C卷完成")

# ================= D卷 =================
m = base("三年级英语", "期末复习质量检测", "（人教版PEP　三年级起点　2025—2026学年　第二学期）")
p = [
 {"name":"一、写出下列字母的大写或小写形式（10分）","questions":[
   Q(1,"C（　）　d（　）　G（　）　j（　）　L（　）　n（　）　Q（　）　r（　）　V（　）　w（　）",10, blanks=10),
 ]},
 {"name":"二、按字母表顺序排列（5分）","questions":[
   Q(1,"t　v　r　u　s　→ ＿＿＿＿＿＿＿＿＿",5, blanks=1),
 ]},
 {"name":"三、看图选词（10分）","questions":[
   Q(1,"数字：six（　）　seven（　）　eight（　）　nine（　）　ten（　）",5, opts=["A. 6　B. 7　C. 8　D. 9　E. 10"], blanks=5),
   Q(2,"饮料：milk（　）　water（　）　juice（　）　tea（　）　coffee（　）",5, opts=["A. 牛奶　B. 水　C. 果汁　D. 茶　E. 咖啡"], blanks=5),
 ]},
 {"name":"四、选出不同类的一项（10分）","questions":[
   Q(1,"（　）",2, opts=["A. five　B. six　C. fish"]),
   Q(2,"（　）",2, opts=["A. milk　B. water　C. head"]),
   Q(3,"（　）",2, opts=["A. grandma　B. grandpa　C. green"]),
   Q(4,"（　）",2, opts=["A. apple　B. orange　C. cake"]),
   Q(5,"（　）",2, opts=["A. black　B. brown　C. book"]),
 ]},
 {"name":"五、单项选择（20分）","questions":[
   Q(1,"—— What's your name?　—— ________",2, opts=["A. My name is Li Ming.　B. I'm fine.　C. I'm nine."]),
   Q(2,"—— How many eggs?　—— ________",2, opts=["A. Six.　B. Egg.　C. Yes."]),
   Q(3,"That is ________ elephant.",2, opts=["A. a　B. an　C. the"]),
   Q(4,"—— Is she your sister?　—— No, ________.",2, opts=["A. she isn't　B. she is　C. he isn't"]),
   Q(5,"—— What would you like to drink?　—— ________",2, opts=["A. Some juice, please.　B. I'm nine.　C. It's a duck."]),
   Q(6,"I like ________ and ________.",2, opts=["A. bread; milk　B. breads; milks　C. a bread; a milk"]),
   Q(7,"—— Where is my book?　—— ________ on the desk.",2, opts=["A. It's　B. They're　C. Is"]),
   Q(8,"—— Let's go to the zoo!　—— ________",2, opts=["A. Great!　B. Sorry.　C. Here you are."]),
   Q(9,"—— How are you today?　—— ________",2, opts=["A. Very well, thank you.　B. I'm nine.　C. My name is Tom."]),
   Q(10,"—— Do you like milk?　—— No, I ________.",2, opts=["A. don't　B. do　C. am not"]),
 ]},
 {"name":"六、情景选择（15分）","questions":[
   Q(1,"你想知道对方是否要吃蛋糕，应该说：________",3, opts=["A. Would you like some cake?　B. What's this?　C. How old are you?"]),
   Q(2,"你想说自己喜欢吃香蕉，应该说：________",3, opts=["A. I like bananas.　B. I like the banana.　C. Bananas like me."]),
   Q(3,"你给别人递东西时，应该说：________",3, opts=["A. Here you are.　B. Thank you.　C. Goodbye."]),
   Q(4,"你迟到了，应该对老师说：________",3, opts=["A. I'm sorry I'm late.　B. How are you?　C. Nice to meet you."]),
   Q(5,"你想知道「这是什么」，应该说：________",3, opts=["A. What's this?　B. How many?　C. What colour?"]),
 ]},
 {"name":"七、连词成句（15分）","questions":[
   Q(1,"like / I / eggs / . → ＿＿＿＿＿＿＿＿＿＿",3, blanks=1),
   Q(2,"you / Would / like / tea / some / ? → ＿＿＿＿＿＿＿＿＿＿",3, blanks=1),
   Q(3,"that / is / Who / girl / ? → ＿＿＿＿＿＿＿＿＿＿",3, blanks=1),
   Q(4,"is / colour / What / it / ? → ＿＿＿＿＿＿＿＿＿＿",3, blanks=1),
   Q(5,"have / I / can / some / water / ? → ＿＿＿＿＿＿＿＿＿＿",3, blanks=1),
 ]},
 {"name":"八、阅读理解（判断正误，正确写T，错误写F）（15分）","questions":[
   Q(1,"阅读短文，判断下列句子正（T）误（F）。",15, blanks=5,
     opts=["　　Hello! My name is Tom. I have a new pencil box. It's blue. I have two pencils, a ruler and an eraser. I like my pencil box. I have a cat. It's white. I like it, too.",
           "（1）Tom has a new pencil box.（　）",
           "（2）Tom's pencil box is red.（　）",
           "（3）Tom has three pencils.（　）",
           "（4）Tom has a white cat.（　）",
           "（5）Tom likes his cat.（　）"]),
 ]},
]
a4 = [
 A(1,"c；D；g；J；l；N；q；R；v；W", "注意字母书写规范。"),
 A(1,"r s t u v", "按字母表顺序。"),
 A(1,"A B C D E", "six6、seven7、eight8、nine9、ten10。"),
 A(2,"A B C D E", "milk牛奶、water水、juice果汁、tea茶、coffee咖啡。"),
 A(1,"C", "fish是食物，其余是数字。"),
 A(2,"C", "head是身体部位，其余是饮品。"),
 A(3,"C", "green是颜色，其余是家人称谓。"),
 A(4,"C", "cake不是水果，其余是水果。"),
 A(5,"C", "book是文具，其余是颜色。"),
 A(1,"A", "问名字答 My name is...。"),
 A(2,"A", "How many 答数量。"),
 A(3,"B", "elephant 元音开头用 an。"),
 A(4,"A", "否定回答 No, she isn't。"),
 A(5,"A", "询问想喝什么答饮品。"),
 A(6,"A", "不可数名词/泛指用原形。"),
 A(7,"A", "单数 book 用 It's。"),
 A(8,"A", "Let's... 的应答用 Great!。"),
 A(9,"A", "How are you 答 Very well, thank you。"),
 A(10,"A", "Do you...? 否定回答 No, I don't。"),
 A(1,"A", "询问需要吗用 Would you like...。"),
 A(2,"A", "表达喜好用 I like...（可数名词用复数）。"),
 A(3,"A", "递东西用 Here you are。"),
 A(4,"A", "道歉用 I'm sorry。"),
 A(5,"A", "询问物品用 What's this?。"),
 A(1,"I like eggs.", "注意句首大写、句末句号。"),
 A(2,"Would you like some tea?", "疑问句首词大写，句末问号。"),
 A(3,"Who is that girl?", "特殊疑问词 Who 句首大写。"),
 A(4,"What colour is it?", "固定问句。"),
 A(5,"Can I have some water?", "情态动词开头。"),
 A(1,"（1）T；（2）F（blue）；（3）F（two）；（4）T；（5）T", "逐句对照短文。"),
]
out.append(save(m, p, a4, "复习质量检测D卷")); print("英语D卷完成")

# ================= E卷 =================
m = base("三年级英语", "期末学业质量监测", "（人教版PEP　三年级起点　2025—2026学年　全学年）")
p = [
 {"name":"一、写出下列字母的大写或小写形式（10分）","questions":[
   Q(1,"D（　）　e（　）　I（　）　j（　）　M（　）　o（　）　R（　）　t（　）　X（　）　y（　）",10, blanks=10),
 ]},
 {"name":"二、按字母表顺序排列（5分）","questions":[
   Q(1,"x　z　v　y　w　→ ＿＿＿＿＿＿＿＿＿",5, blanks=1),
 ]},
 {"name":"三、看图选词（10分）","questions":[
   Q(1,"文具类：pen（　）　pencil（　）　book（　）　bag（　）　ruler（　）",5, opts=["A. 钢笔　B. 铅笔　C. 书　D. 书包　E. 直尺"], blanks=5),
   Q(2,"动物类：panda（　）　monkey（　）　tiger（　）　bear（　）　elephant（　）",5, opts=["A. 熊猫　B. 猴子　C. 老虎　D. 熊　E. 大象"], blanks=5),
 ]},
 {"name":"四、选出不同类的一项（10分）","questions":[
   Q(1,"（　）",2, opts=["A. cake　B. bread　C. cat"]),
   Q(2,"（　）",2, opts=["A. eye　B. ear　C. egg"]),
   Q(3,"（　）",2, opts=["A. blue　B. black　C. bear"]),
   Q(4,"（　）",2, opts=["A. four　B. five　C. fish"]),
   Q(5,"（　）",2, opts=["A. mum　B. dad　C. milk"]),
 ]},
 {"name":"五、单项选择（20分）","questions":[
   Q(1,"—— Hello, I'm Sam.　—— ________",2, opts=["A. Hello, I'm Amy.　B. I'm fine.　C. Goodbye."]),
   Q(2,"—— What's this in English?　—— ________ a duck.",2, opts=["A. It's　B. This　C. I'm"]),
   Q(3,"I have ________ orange bag.",2, opts=["A. a　B. an　C. /"]),
   Q(4,"—— How many boys?　—— ________",2, opts=["A. Eight.　B. Boy.　C. Yes."]),
   Q(5,"—— Is this your pen?　—— Yes, ________.",2, opts=["A. it is　B. it isn't　C. they are"]),
   Q(6,"She is ________ sister.",2, opts=["A. I　B. my　C. me"]),
   Q(7,"—— What would you like?　—— ________",2, opts=["A. Some cake, please.　B. I'm nine.　C. It's red."]),
   Q(8,"Let's ________ a song.",2, opts=["A. sing　B. sings　C. singing"]),
   Q(9,"—— Happy New Year!　—— ________",2, opts=["A. Happy New Year!　B. Sorry.　C. Here you are."]),
   Q(10,"—— Are you nine?　—— ________",2, opts=["A. Yes, I am.　B. Yes, I do.　C. Yes, it is."]),
 ]},
 {"name":"六、情景选择（15分）","questions":[
   Q(1,"你想问「你叫什么名字」，应该说：________",3, opts=["A. What's your name?　B. How are you?　C. How old are you?"]),
   Q(2,"你想说「我给你看看我的新书」，应该说：________",3, opts=["A. Look at my new book!　B. This is a book.　C. I like books."]),
   Q(3,"你想知道对方喜欢什么颜色，应该问：________",3, opts=["A. What colour do you like?　B. How many colours?　C. What's this?"]),
   Q(4,"朋友送你礼物，你应该说：________",3, opts=["A. Thank you!　B. Sorry.　C. Goodbye."]),
   Q(5,"你想表达「这真是一个大动物园」，应该说：________",3, opts=["A. What a big zoo!　B. It's a zoo.　C. I like zoos."]),
 ]},
 {"name":"七、连词成句（15分）","questions":[
   Q(1,"is / my / This / schoolbag / . → ＿＿＿＿＿＿＿＿＿＿",3, blanks=1),
   Q(2,"English / this / in / What's / ? → ＿＿＿＿＿＿＿＿＿＿",3, blanks=1),
   Q(3,"you / like / Do / monkeys / ? → ＿＿＿＿＿＿＿＿＿＿",3, blanks=1),
   Q(4,"I / some / have / Can / bread / ? → ＿＿＿＿＿＿＿＿＿＿",3, blanks=1),
   Q(5,"old / How / sister / is / your / ? → ＿＿＿＿＿＿＿＿＿＿",3, blanks=1),
 ]},
 {"name":"八、阅读理解（判断正误，正确写T，错误写F）（15分）","questions":[
   Q(1,"阅读短文，判断下列句子正（T）误（F）。",15, blanks=5,
     opts=["　　Hi! I'm Kate. Welcome to my home! This is my family. There are five people in my family. They are my grandpa, grandma, father, mother and me. I like my family very much. I have a brother, too. But he is not at home now.",
           "（1）Kate is at home.（　）",
           "（2）There are four people in Kate's family.（　）",
           "（3）Kate has a brother.（　）",
           "（4）Kate's brother is at home now.（　）",
           "（5）Kate likes her family.（　）"]),
 ]},
]
a5 = [
 A(1,"d；E；i；J；m；O；r；T；x；Y", "注意字母大小写与占格。"),
 A(1,"v w x y z", "按字母表顺序。"),
 A(1,"A B C D E", "pen钢笔、pencil铅笔、book书、bag书包、ruler直尺。"),
 A(2,"A B C D E", "panda熊猫、monkey猴子、tiger老虎、bear熊、elephant大象。"),
 A(1,"C", "cat是动物，其余是食物。"),
 A(2,"C", "egg是食物，其余是身体部位。"),
 A(3,"C", "bear是动物，其余是颜色。"),
 A(4,"C", "fish是动物/食物，其余是数字。"),
 A(5,"C", "milk是食物，其余是家人称谓。"),
 A(1,"A", "自我介绍后答 Hello, I'm...。"),
 A(2,"A", "What's this 用 It's 回答。"),
 A(3,"B", "orange 元音开头用 an。"),
 A(4,"A", "How many 答数量。"),
 A(5,"A", "Is this...? 肯定答 Yes, it is。"),
 A(6,"B", "my sister 我的姐妹。"),
 A(7,"A", "What would you like 答想要的东西。"),
 A(8,"A", "Let's 后接动词原形。"),
 A(9,"A", "节日祝福的应答。"),
 A(10,"A", "Are you...? 答 Yes, I am。"),
 A(1,"A", "询问名字用 What's your name。"),
 A(2,"A", "请人看用 Look at...。"),
 A(3,"A", "询问喜好用 What colour do you like。"),
 A(4,"A", "接受礼物说 Thank you。"),
 A(5,"A", "感叹句用 What a big zoo!。"),
 A(1,"This is my schoolbag.", "注意语序与句号。"),
 A(2,"What's this in English?", "固定问句。"),
 A(3,"Do you like monkeys?", "助动词 Do 句首大写。"),
 A(4,"Can I have some bread?", "情态动词开头。"),
 A(5,"How old is your sister?", "How old 询问年龄。"),
 A(1,"（1）T；（2）F（five）；（3）T；（4）F（not at home）；（5）T", "逐句对照短文信息。"),
]
out.append(save(m, p, a5, "学业质量监测E卷")); print("英语E卷完成")

for f in out:
    print("已生成:", f)
